### ISSUE TITLE
INPUT number type with min/max does not limit range

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1008]
When a number INPUT is used with min/max limiters, the min and max limit the range when using the built-in arrow keys, but a user can override that by typing in a number outside the range.  Seems like the point of the range should be to limit the range.

**Comment by mousewax** [comment]
I am taking suggestions as to how we should handle it. I had previously put forward three solutions. There are undoubtedly many more. 

1. Mark the field with an error if it's not a number or outside the range and POSSIBLY disable the submit button.
2. In the UI detect if it's a number AND outside the range and then adjust it to either the min or max before submitting.
3. On the back-end detect if it's a number AND outside the range and then adjust it to either the min or max after submitting.

**Comment by rogerl50** [comment]
3, and document in the wiki.

**Comment by bjalder26** [comment]
What about if it just passed a variable that indicated it was outside of the range.  For example, what if it returned 0 if within range, or a negative number indicating how far below the range it is, or a positive number indicating how far above the range it is.  Then in the JSON they could recall the routine if they want, or subtract the amount returned to bring it within range.

**Comment by rogerl50** [comment]
Totally agree with @96LawDawg . If the designer specified a range, there was a reason for it. No need to make it more complicated than that IMO.

**Comment by mousewax** [comment]
This is the web browser functioning as intended. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

> Warning: Logically, you should not be able to enter characters inside a number input other than numbers. There seems to be some disagreement about this among browsers; see bug 1398528.

I will add some front end to display a warning, but the input will adjust numbers to be within the range on the back-end and on re-display.

**Comment by mousewax** [comment]
<img width="261" alt="image" src="https://user-images.githubusercontent.com/12822213/145695596-482d5d83-2540-407a-a820-ad6674655cd4.png">

It still lets you submit, but will warn when it's invalid.
