### ISSUE TITLE
Method to Reorganize Order of Variants

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#101]
As a game developer I need a way to change the order of variants in a VTT file.  Right now, the only way to do that is to create a new file and upload each variant individually in the order you want.  Moving forward with the new UI, it would be good to be able to drag and drop variants in the order you want them.

**Comment by RaphaelAlvez** [comment]
Could you propose a priority for this?
I know the pain it is but that is already planned for the overhaul. I just want to know if this should be worked before that.

**Comment by robartsd** [comment]
I'd say the deck editor is a higher priority than overhauling library management, but that's just my opinion. Neither are blocking me from accomplishing what I want to do, but I think the deck editor overhaul will enable more people doing more things with the platform than overhauling library management would.

**Comment by 96LawDawg** [comment]
If that is in the plan for the UI redesign, then this should be closed.  I agree it is not a priority.  I just wanted to make sure it was in the plan.  Sounds like it is.  Closed.

**Comment by RaphaelAlvez** [comment]
Not closed... I'll put it on the project list. The feature is not discarded neither ready
