### ISSUE TITLE
INPUT crashes client

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#1010]
While trying to write a routine that would disable a button in preparation for input (so that only one person could click it), I wrote the following:
```JSON
"clickRoutine": [
    {
      "func": "CALL",
      "routine": "disableClickRoutine"
    },
    {
      "func": "CALL",
      "routine": "getNameRoutine"
    },
    {
      "func": "SET",
      "collection": "thisButton",
      "property": "clickable",
      "value": true
    }
  ],
  "disableClickRoutine": [
    {
      "func": "SET",
      "collection": "thisButton",
      "property": "clickable",
      "value": false
    }
  ],
  "getNameRoutine": [
    {
      "func": "INPUT",
      "fields": [
        {
          "type": "title",
          "text": "Please sit down",
          "css": "background-color:var(--VTTblue);color:white;"
        },
        {
          "type": "string",
          "label": "Name",
          "variable": "name",
          "css": "color:black",
          "value": ""
        }
      ],
      "cancelButtonIcon": "thumbs_down",
      "cancelButtonText": "Cancel",
      "confirmButtonIcon": "thumbs_up",
      "confirmButtonText": "OK"
    }
  ],
```
When I click Cancel, the client crashes at the line `variables[a.variable] = result.variable;` in the code for 'CALL' with the error `Uncaught (in promise) TypeError: result is undefined`.

Clicking Cancel on a simple INPUT that is part of the `clickRoutine` directly does not cause a crash; the issue seems to be around the return `result` variable from the `CALL`.

**Comment by bjalder26** [comment]
Yeah.
![image](https://user-images.githubusercontent.com/78324099/145688906-c62e670c-a650-41e1-ba5f-4b9461366762.png)

![image](https://user-images.githubusercontent.com/78324099/145688898-1665e8a6-a04c-498f-b824-ef0d1f7db116.png)

**Comment by mousewax** [comment]
Check for the behavior on this PR test server. I couldn't replicate it, but I may not be doing it right.

http://212.47.248.129:4009/pr-test

**Comment by rogerl50** [comment]
> Check for the behavior on this PR test server. I couldn't replicate it, but I may not be doing it right.
> 
> http://212.47.248.129:4009/pr-test

I still got the same error. Did you use the clickRoutine I posted above? And click Cancel?

**Comment by 96LawDawg** [comment]
I get the error.  But it isn't a typical crash.  It still lets me sort of kind of do a few things and some of them are really, really slow.  But there is something going on that F5 fixes after pressing Roger's demo button.

**Comment by rogerl50** [comment]
OK, but I think it's clear from @bjalder26 's post what the problem is. I think this was introduced in #976, but I'm not sure.

**Comment by bjalder26** [comment]
> OK, but I think it's clear from @bjalder26 's post what the problem is. I think this was introduced in #976, but I'm not sure.

I think yes and no.  Routines were never called this way before, so there wasn't a way in the CALL code to catch if what was returned was undefined.  It seems easy enough to fix, but I don't know what the proper way to fix it would be.  Maybe it should check if const result is undefined first, or maybe an empty object should be returned.  I don't really know.  If I were to guess, I'd guess the former, which would be really easy to do.
