### ISSUE TITLE
Need a way to ensure single-access button

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#1011]
If a button posts in INPUT dialog, the button is still active for other players to press. This is often not the desired behavior. There doesn't seem to be a simple way to ensure that that can't happen, but it seems like a common problem. Disabling the button in the `clickRoutine` doesn't work, as the disable will not take effect until the routine finishes.

**Comment by robartsd** [comment]
This will not likely be solved anytime soon (if ever). A potential workaround for game designers is to have the button disable itself then start a timer which will trigger the actual routine that needs the INPUT.

**Comment by bjalder26** [comment]
What if you used a changeRoutine to bring up the INPUT dialog, and the changeRoutine was triggered by changing the clickable property of the button to false?

**Comment by bjalder26** [comment]
I made a timer that can be used as a workaround for this issue.  The idea is that a routine in the timer can be called with the variables `delay`, `routine`, `widget` and `arguments`, and the timer will wait the delay amount of milliseconds, then perform a call using the passed variables.

Calling the routine would look like this (notice arguments can be passed in the arguments yoDawgMeme.jpg):

```json
    {
      "func": "CALL",
      "routine": "delayCallRoutine",
      "widget": "delaycall",
      "arguments": {
        "delay": 10000,
        "routine": "incrementRoutine",
        "widget": "button1",
        "arguments": {
          "passedvariable": 1
        }
      }
    }
```
https://virtualtabletop.io/vwuu

I believe LawDawg will put a version in a future tutorial.

**Comment by rogerl50** [comment]
> I made a timer that can be used as a workaround for this issue. The idea is that a routine in the timer can be called with the variables `delay`, `routine`, `widget` and `arguments`, and the timer will wait the delay amount of milliseconds, then perform a call using the passed variables.
> 
> Calling the routine would look like this (notice arguments can be passed in the arguments yoDawgMeme.jpg):
> 
> ```json
>     {
>       "func": "CALL",
>       "routine": "delayCallRoutine",
>       "widget": "delaycall",
>       "arguments": {
>         "delay": 10000,
>         "routine": "incrementRoutine",
>         "widget": "button1",
>         "arguments": {
>           "passedvariable": 1
>         }
>       }
>     }
> ```
> 
> https://virtualtabletop.io/vwuu
> 
> I believe LawDawg will put a version in a future tutorial.

Nice.
