### ISSUE TITLE
Label's textarea should have a spellcheck property (defaulting to `false`)

### ISSUE THREAD

**Issue by robartsd** [ArnoldSmith86/virtualtabletop#1017]
In some games, players use labels to enter values that are evaluated by other players. Not spelling correctly can be a clue that a player is guessing. Browser automatic indication of spelling errors can impact game play. This would add the spellcheck attribute set to false to the label's textarea by default. Game designers would be able to turn on automatic spell check by setting the value to true.

**Comment by 96LawDawg** [comment]
Closed by #1511
