### ISSUE TITLE
Pile overlay card count is wrong

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#1021]
https://github.com/ArnoldSmith86/virtualtabletop/blob/58a5886efdba58af2b40900c11bfe678d3a66b88/client/js/widgets/pile.js#L78

That should show the number of cards. Not the potentially overridden text.

**Comment by 96LawDawg** [comment]
Fixed when the pile overlay was redone.  Somewhere.  Sometime.
