### ISSUE TITLE
Deck edit upload buttons look weird

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#104]
The icon update made the upload asset buttons when editing a card deck look really weird.

**Comment by RaphaelAlvez** [comment]
this one? 
![image](https://user-images.githubusercontent.com/73476656/104439080-7a81f480-556f-11eb-9993-e57deb5d0219.png)

I didn't touch it because it was supposed to be removed with the deck editor overhaul

**Comment by bjalder26** [comment]
Can this issue be closed?
![image](https://user-images.githubusercontent.com/78324099/125509641-ebc89718-4ff1-41a4-9cd6-926516454e0d.png)
