### ISSUE TITLE
Widget DOM element ID should follow HTML specification

### ISSUE THREAD

**Issue by robartsd** [ArnoldSmith86/virtualtabletop#1044]
[HTML5 specifies that the `id` attribute](https://www.w3.org/TR/2011/WD-html5-20110525/elements.html#the-id-attribute) be unique in the document and contain no space characters (space, tab, line feed, carriage return).

I propose that we prefix the widget ID with `w_` (eliminate possible collision with interface element IDs) and escape characters not allowed in CSS identifiers (more restrictive than HTML id).

**Comment by robartsd** [comment]
Perhaps we should kill two birds with one stone and escape all characters that are not allowed in CSS identifiers when generating the widget's DOM id. Then #951 would not need its own escape.

**Comment by bjalder26** [comment]
As an alternative, would it make sense to just go back in and prefix all the html IDs with something unlikely to be used that we could also prohibit from widget IDs?

**Comment by robartsd** [comment]
My plan is to use SharePoint style underscore escapes (`_x0000_`) for any characters in the widget ID that are not the un-escaped ASCII characters allowed in CSS identifiers (letters, digits, underscore, hyphen) with the underscore character itself escaped simply by doubling it. The hardest part will be rewriting mousehandling.js as it uses the assumption that DOM element id = Widget.id quite a bit. To avoid potential collisions the id of widget stylesheets will also be changed (prefixing the escaped id instead of suffixing the id). Since the id will always be prefixed, I won't need to worry about the special rules for characters allowed at the beginning of a CSS identifier.
