### ISSUE TITLE
option to redirect INPUT function to specific players

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#1046]
as described in discord (https://discord.com/channels/770758631146782780/793626590848352306/923169648894169098) i would like to invoke the INPUT overlay while determining which player gets the prompt.

**Comment by RaphaelAlvez** [comment]
> as described in discord (https://discord.com/channels/770758631146782780/793626590848352306/923169648894169098) i would like to invoke the INPUT overlay while determining which player gets the prompt.

This is duplicated from #780
