### ISSUE TITLE
Recalling cards from deleted holders produces error with enterRoutine

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1051]
I was working on making stacks of cards that can be dragged around as a group (not in a pile).  Think solitaire or rummy games.  I added a holder at the bottom of each card to attach another card to using an enterRoutine.  Eventually I got that working.  However, when recalling the cards stacked that way, it would recall the bottom card in the stack with all the child cards as a group and would freeze the room.  Demo at https://virtualtabletop.io/wqu4.  Screenshot of the widget tree and console after pressing recall attached.

<img width="427" alt="Screenshot 2021-12-28 093155" src="https://user-images.githubusercontent.com/76912527/147582026-23ed7954-ea39-4231-9ef8-5932752210ce.png">

<img width="412" alt="Screenshot 2021-12-28 092756" src="https://user-images.githubusercontent.com/76912527/147582032-31351160-3d9b-438f-a195-4601cfa6e803.png">

I was able to get around the problem by adding a couple of lines to the recall button to SET `"parent":null` for all cards in that deck before recalling.  I could also get around the problem by removing the enterRoutine.  That routine really isn't necessary once all the cards have holders.  But that combination of an enterRoutine and recalling cards in holders produces an error for whatever reason.

**Comment by robartsd** [comment]
I think the problem is that your code is putting a new copy of the holder on the card every time a card enters, then deleting the old copy if there are more than one. Sometimes the holder deleted was the old parent of a recalled card that has not been processed yet. The old parent being deleted before processing the recall is causing the crash. Certainly VTT should not crash.

**Comment by 96LawDawg** [comment]
Sure.  That makes sense.  I'll rename the issue.

**Comment by bjalder26** [comment]
Yeah, oldParent is undefined, and it is trying to perform onChildRemove on it. 
![image](https://user-images.githubusercontent.com/78324099/147591225-5bb27908-f06d-4df4-9f47-6ef5424f1136.png)

I guess we don't often deal with holders that get deleted, so this hasn't been noticed until now.
