### ISSUE TITLE
substr should invoke substring

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#1053]
`substr` is deprecated in JavaScript, I guess replaced by `slice` and/or `substring`. We should either simply replace the call to substr in compute.js by a call to substring, or we should change the name of the function in VTT as well. The latter would require a fileupdater.

**Comment by robartsd** [comment]
Removing `substr` from VTT could be difficult as `substr` supports negative starting index but `substring` does not. We should keep `substr` behavior as is, but probably should also support `substring`. Should not be a problem to implement `substr` using `substring` but should not be necessary as the specification requires `substr` be implemented for [web browsers](https://tc39.es/ecma262/#sec-additional-ecmascript-features-for-web-browsers).

**Comment by ArnoldSmith86** [comment]
Yeah, hell will freeze over before browsers remove `substr`.
