### ISSUE TITLE
collections created in called routines don't work

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#1055]
https://virtualtabletop.io/be6c
in this room, clicking the `DEAL` button, crashes the client. the button calls a routine in `codeLibrary` that uses the `result` collection. without the result collection nothing breaks, but no collection is returned.

**Comment by 96LawDawg** [comment]
The title is slightly incorrect.  Card collections do not seem to work, but collections of other widgets do.  I created a "Pin Collection" button in that same room that does work.  But the debugger shows a LOT of strange stuff happening before the collection is created.  Something strange is definitely going on.

**Comment by bjalder26** [comment]
![image](https://user-images.githubusercontent.com/78324099/148110862-b646fe93-b58b-453a-9aad-29344111cd60.png)
I think using a replacer function to replace objects would fix this.
https://careerkarma.com/blog/converting-circular-structure-to-json/

**Comment by robartsd** [comment]
For collections, we don't need (or even want) a deep copy - the widget objects themselves should not be copied; just the references to the widget objects.
