### ISSUE TITLE
time stamp for saved changes

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#1065]
sometimes i find myself not remembering when the last saved state was. you could always save the changes in a new variant and then load the older version but it would save some time. also having a timestamp could be useful to know what features were available to the designer at the time of editing the game

**Comment by RaphaelAlvez** [comment]
@ArnoldSmith86 maybe this should go into #1223 no idea where...

**Comment by 96LawDawg** [comment]
Option to do essentially this was implemented by #1902.
