### ISSUE TITLE
problems in debug output propagate to children

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#1066]
Problems bubble up with red arrows but apparently they are also inherited to children which doesn't seem correct:

![Untitled](https://user-images.githubusercontent.com/73538315/148445020-95b1bd55-e232-4e95-bcc8-478f8e55155f.png)

**Comment by rogerl50** [comment]
I don't see any red arrows *at all* in that screenshot.

Can you post a room with instructions as to how to generate the incorrect output?

**Comment by ArnoldSmith86** [comment]
> I don't see any red arrows _at all_ in that screenshot.

:smile:

I'm pretty sure it has nothing to do with the arrows. It's just that the "problem" class added to the entry affects the children. It's just that nobody thought about that because something that has problems usually does not have children.

https://virtualtabletop.io/hqla

1. Take a seat.
2. Click "New Game".

**Comment by rogerl50** [comment]
Interesting. This problem has existed since the debugger was introduced. The red color is inherited by the children.
