### ISSUE TITLE
LABEL inc by null freezes room

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1069]
Example:

```JSON
 {
      "func": "LABEL",
      "label": "mkvg",
      "value": null,
      "mode": "inc"
    }
   ```
This will freeze the room.

**Comment by bjalder26** [comment]
![image](https://user-images.githubusercontent.com/78324099/150649667-40f8757e-b179-437e-9497-d24429bbed4b.png)

It looks like we just need to add `|| this.get('text') !== null` to the if statement in setText.
