### ISSUE TITLE
CALL result returns null instead of 0

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1070]
Example:

```JSON
"clickRoutine": [
    {
      "func": "CALL",
      "routine": "testRoutine"
    }
  ],
  "testRoutine": [
    "var result = 0"
  ]
```
The expected result is 0, but the value returned is null.  This will probably require a minor fileupdater, but it should be fixed.

**Comment by rogerl50** [comment]
This is the offending line:
```
    return { variable: variables.result || null, collection: collections.result || [] };
```
Why would this require a fileupdater?

**Comment by 96LawDawg** [comment]
Maybe it wouldn't.  I just assumed it would because there could be a game out there now that works because of a null return and the designer just didn't recognize what was going.  That has happened to me before (not with this example but a few of the earlier file updater things).

**Comment by ArnoldSmith86** [comment]
Hmm. A fileupdater for this would probably be kinda ugly. There could be a lot of dynamic stuff happening so the fileupdater can't know which routine could possibly be `CALL`ed. Adding a `if(result === 0) result = null` at the end of each and every routine seems like very ugly overkill though.

Finding out which routines need that check is probably more work than this warrants. So maybe we just change it without a fileupdater. It's probably unlikely enough that this causes major issues.
