### ISSUE TITLE
Giving widget id "options" causes strange behavior

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1071]
In a blank room, add some objects such as a checker, a pawn, a label, and a button.  Reassign the id of each one as "options" and you can see the strangeness.  I first noticed this when renaming a button to "options" and it changed the drag behavior.

**Comment by robartsd** [comment]
Probably related to #1044. The UI has an element with id of "options"

**Comment by rogerl50** [comment]
Should the `SET` code also query the DOM to see if the new id exists in the DOM?

**Comment by ArnoldSmith86** [comment]
Not really. Widgets should have their own "namespace" (so a prefix or something like it) to prevent conflicts.

**Comment by robartsd** [comment]
In #1044 I proposed a prefix of 'w_' for widget DOM id.

**Comment by bjalder26** [comment]
> In a blank room, add some objects such as a checker, a pawn, a label, and a button. Reassign the id of each one as "options" and you can see the strangeness. I first noticed this when renaming a button to "options" and it changed the drag behavior.

I believe I used "options" as a span name in the AUDIO PR (maybe that wasn't a good idea).
