### ISSUE TITLE
moving a card half out the hand doesn't update owner

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#1072]
Very bad bug and couldn't be easier to reproduce:

Pull a card out of your hand until the hand is no longer the drop target but the card still overlaps the hand. If you let go there, no leave is triggered so the cards in the hand don't rearrange and the owner of the card is not removed. However, the parent _does_ get removed.

So with a second move you can put it anywhere and it's still _your_ card. Putting it into any holder resets the owner.

This was probably broken by #903 because before that it was impossible to put cards "onto" a holder without putting it into the holder.

**Comment by robartsd** [comment]
That make sense. I believe the fix should be making the code for leave and the code for hoverTarget use the exact same criteria.

**Comment by ArnoldSmith86** [comment]
Hmm, yeah, that sounds like a reasonable solution. If I find some time among the other critical bug fixes, I'll assign the issue to me and start working on it.
