### ISSUE TITLE
Allow multiple globalUpdateRoutines to be executed

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#1075]
As far as i understand this, right now only one globalUpdateRoutine can fire at once. but especially with propertyGlobalUpdateRoutines, this is very limiting.

**Comment by ArnoldSmith86** [comment]
Multiple routines will be executed for the same property change.

But a `globalUpdateRoutine` will currently _never_ be called when triggered _inside_ of any `globalUpdateRoutine` (even if it's in a sub-routine or for a completely different property).

Just trying to describe what's happening. I'm not saying I don't want this to be changed.

**Comment by Ingegneus** [comment]
I think i got this all wrong. i did set up a few tests but i probably messed those up so my results didn't reflect the behaviour well. the original issue that i had doesn't exist.
