### ISSUE TITLE
Temporary way to make Tutorials and Assets more Accessible

### ISSUE THREAD

**Issue by Casbuild** [ArnoldSmith86/virtualtabletop#108]
I suggest the tutorials and assets are posted to the PL at the bottom labeled "Similar to Tutorials". Assets could be listed as a tutorial to make game pieces which would be nice because it would group it with the rest of the tutorials.

I know there is a plan to create a better way to access the tutorials and assets, but until that is up this would be a simple add that would be very helpful.

**Comment by 96LawDawg** [comment]
I suggest Casbuild post this here to see what people think.  I have created rooms to host tutorials at https://virtualtabletop.io/Tutorials and Assets at https://virtualtabletop.io/Assets.  But putting them at the bottom of the library is not a bad interim solution until the UI is updated.

**Comment by Casbuild** [comment]
This also allows multiple people to use tutorials or assets at once without needing to download and upload each one and prevents someone from overwriting/deleting them by accident.

**Comment by 96LawDawg** [comment]
Here is a mock-up of how this would look (using a local test server).  The only change I had to make was to move the tutorial files from the tutorial sub-directory into the main library directory.  Thoughts?

![Mock Up Tutorials in Library](https://user-images.githubusercontent.com/76912527/104537237-32021f80-55df-11eb-90ec-2a59c36db79d.jpg)

**Comment by RaphaelAlvez** [comment]
This morning I spent a couple of hours trying to make the tutorials page. I'm stuck at making the add buttons work. Everything else is in place. If Arnold can't help me tomorrow an i keep stuck I would say this is probably the best option
