### ISSUE TITLE
Automatically assume clickable:true if widget has clickRoutine

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1083]
Adding a clickRoutine to a holder has no effect.  There is no way to click the holder.

**Comment by ArnoldSmith86** [comment]
Did you set `clickable` to `true`?

**Comment by 96LawDawg** [comment]
Of course not.  Thanks for being kind about it.  I know you were thinking "what a moron.  He didn't set `clickable` to `true`".  And if you weren't thinking that, now I am.  Bad moron.  Bad moron.  Get your act together.

All better.  Thanks!

**Comment by ArnoldSmith86** [comment]
We all lost time to that, don't worry. Maybe we just assume `clickable: true` if a `clickRoutine` was provided?

**Comment by rogerl50** [comment]
> We all lost time to that, don't worry. Maybe we just assume `clickable: true` if a `clickRoutine` was provided?

That sounds like a great suggestion.

**Comment by ArnoldSmith86** [comment]
It's also a _really_ simple fileupdater that would just add `clickable: false` to any widget that defaulted to `false` before the change, doesn't set it explicitly and has a `clickRoutine` (which will in practice probably affect exactly `0` widgets).

**Comment by 96LawDawg** [comment]
That is a good idea.  I thought about holders and `clickable: false` is definitely the right default.  But your idea is a good solution.  I'm reopening the issue with a new name.

**Comment by rogerl50** [comment]
> It's also a _really_ simple fileupdater that would just add `clickable: false` to any widget that defaulted to `false` before the change, doesn't set it explicitly and has a `clickRoutine` (which will in practice probably affect exactly `0` widgets).

You mean *except* for @96LawDawg's widgets.

**Comment by RaphaelAlvez** [comment]
This but then how would we lock a button if we can't use clickable:false

**Comment by robartsd** [comment]
I'm not sure why any widget defaults to clickable false. Does a holder without a click routine behave any differently with clickable false vs. clickable true?

**Comment by 96LawDawg** [comment]
> Does a holder without a click routine behave any differently with clickable false vs. clickable true?

I don't think so.  A holder without a `clickRoutine` doesn't do anything when you click on it.  `clickable` doesn't make any difference.

> I'm not sure why any widget defaults to clickable false.

For holders, I think it makes sense.  A holder often contains widgets which you clicking to drag or interact with.  You don't want the holder to accidentally be the target of your click.  But unless you have intentionally put a `clickRoutine` there knowing the risks, then it doesn't matter if the player clicks there.  So I guess my argument doesn't make that much sense.

**Comment by 96LawDawg** [comment]
> This but then how would we lock a button if we can't use clickable:false

The point is not to override `clickable:false` if set.  Just change the default behavior (I think).

**Comment by ArnoldSmith86** [comment]
I think setting the default to `clickable: true` for everything is the better approach. We just have to make sure that widgets without click behavior don't steal clicks from their parents.

**Comment by robartsd** [comment]
> I think setting the default to `clickable: true` for everything is the better approach. We just have to make sure that widgets without click behavior don't steal clicks from their parents.

Yes, but it is a fairly rare edge case that a widget without a click behavior has a parent with a click behavior. Does setting clickable false cause a widget to bubble clicks up to parents currently?

**Comment by 96LawDawg** [comment]
> > I think setting the default to `clickable: true` for everything is the better approach. We just have to make sure that widgets without click behavior don't steal clicks from their parents.
> 
> Yes, but it is a fairly rare edge case that a widget without a click behavior has a parent with a click behavior. Does setting clickable false cause a widget to bubble clicks up to parents currently?

No. Clicking a child widget when clickable is false and when it is true do not make any difference.  There is no "bubble up."

**Comment by RaphaelAlvez** [comment]
the most stupid open issue....
