### ISSUE TITLE
Comments in code

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#1088]
Right now, the way I do comments in code is either
```JSON
  "Note: ..."
```
or
```JSON
  {
    "Note": "...",
    "func": "IF",
    ...
  }
```
The first of these is preferable in many cases, at least to me, since it's a more logical place to put the description of a whole routine. But it shows up as an error in the JSON editor, since such things are expected to parse as `"var foo = ..."`.

Should we consider allowing syntax of the form `"Note[^:]*: ..."` to parse as a comment (that is, to be ignored)?

**Comment by 96LawDawg** [comment]
Yes

**Comment by robartsd** [comment]
We already have comments using `//` after expressions, but these still show up as errors if on a line by themselves. I'm okay with `Note:` for full line comments, but would prefer `//`.
