### ISSUE TITLE
Moving widgets changes parentage

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#11]
If a widget that is inside a holder is moved manually in the UI, it loses its parentage and resides on the desktop. It does not happen if the xy coordinates are edited in the raw JSON. I'm somewhat less sure whether it happens if the xy coordinates are changed with a SET. At the very least, this needs to be clarified in the documentation. But it seems unreasonable that adjusting position of a widget inside a holder moves it out of the holder; that means that really the only way to adjust position is manually via editing the JSON.

This is particularly annoying when, if editing in the base editor, you happen to move the widget by a half pixel or so when trying to double-click it for editing. I've taken to looking carefully at each parented widget I open to make sure it hasn't lost its parent,

**Comment by ArnoldSmith86** [comment]
This doesn't address your problem but `SET` does not touch the `parent` (unless you explicitly set the parent).

**Comment by larkob** [comment]
The wiki now clearly mentions that MOVEXY moves widget out of wherever they are and places them onto the `floor`.

As @rogerl50 mentioned a problem with moving it manuall in the UI, I've labeled this issue as a UI bug.
