### ISSUE TITLE
TestCafe does not work with seat widgets

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1101]
Putting a seat widget in a room and clicking on that seat as part of the TestCafe run causes a different checksum to be created every time.  See #1100 for an example of how that happened.

**Comment by robartsd** [comment]
TestCafe always plays under player name "TestCafe", but player color is not set. The seat is probably getting a different color every time as the random color is chosen by the server, not the client.
