### ISSUE TITLE
ambiguous z values

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#1111]
So, I found a potentially big problem:

1. Open https://virtualtabletop.io/1mxx (red is on top)
2. Press the button (orange is on top)
3. Open https://virtualtabletop.io/1mxx (red is on top)

When two widgets have the same `z`+`layer`+`parent`, the actual z order of them is determined by the order in the DOM.

When loading a room, the order in the DOM is the order in which the widgets are defined in the JSON (so usually the one added first is below the one added afterwards).

Changing a parent in the game moves the DOM element to the new parent but it puts it all the way at the end.

In practice this could happen with normal shuffling, I think.

1. Player 1 shuffles cards.
2. Player 2 joins afterwards.
3. The order of the cards is not the same for both of them (unless player 1 reloads the page).

Now, I'm not too sure if this is actually a problem. Mouse interactions and for example `MOVE`s apply a unique z value so those should not be affected. A `SHUFFLE` applies random z values to all children which can produce the same value for multiple widgets. _But_ if you shuffle, the order is obviously not important. Unless the cards are face up.

Hmm, I think `SHUFFLE` should make sure that z values are unique.

**Comment by robartsd** [comment]
I agree that SHUFFLE should make sure that z values are unique. It might also need to check the Z value of children that are filtered out. Should SHUFFLE be allowed to change the z values of widgets that are not part of the SHUFFLE (usually buttons attached to the holder)? SHUFFLE collection also has the issue that while it changes z values of all the widgets in the collection those changes could interact with the z values of other siblings of those widgets.

Perhaps SHUFFLE should create a random order for the items it is shuffling, then loop through those widget in that order setting z using `Widget.bringToFront()`. This would mean z values increase much more quickly in a room.

**Comment by ArnoldSmith86** [comment]
> Perhaps SHUFFLE should create a random order for the items it is shuffling, then loop through those widgets in that order setting z using `Widget.bringToFront()`. This would mean z values increase much more quickly in a room.

That's pretty much what I was thinking. How fast z values increase, doesn't matter, because there's the reset code already.
