### ISSUE TITLE
GET with "sum" on an empty collection should return zero.

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#112]
`COUNT` on an empty collection properly returns zero, but `GET` with "sum" on some property seems to return nothing. I'm using that result in a `COMPUTE` operation, and that operand gets turned into 1. The following `clickRoutine` in a button in an otherwise empty room shows the problem (with "debug": true):
```JSON
    {
      "func": "SELECT",
      "property": "id",
      "value": "foo",
      "collection": "bar"
    },
    {
      "func": "COUNT",
      "collection": "bar",
      "variable": "count"
    },
    {
      "func": "GET",
      "collection": "bar",
      "property": "foo",
      "aggregation": "sum",
      "variable": "sum"
    }
```

**Comment by robartsd** [comment]
I'm not sure that zero is the correct response to a "sum" of an empty collection, but turning nothing to a 1 is a problem. Nothing should either be treated as 0 or cause an error if a number is expected.

**Comment by rogerl50** [comment]
I'm not sure that zero is the correct answer either. But an empty collection returns 0 in a `COUNT`, so this would at least be consistent. I don't think that an causing an error would be helpful unless there is some way to process the error - my example is actually a reasonable use case that needs support. Another alternative would be to add a default value. Again, though, I do think any behavioral change like that should be mirrored in `COUNT` for consistency.

**Comment by ArnoldSmith86** [comment]
IMO the answer for both is obviously `0`.

**Comment by robartsd** [comment]
The count of items in an empty set _is_ zero, the sum of items in an empty set is null. Treating nulls as zeros is much better than treating nulls as ones. In any case current behavior is a bug, but causing "count" to return nothing when given an empty set would also be a bug. I suppose allowing "sum" to silently change nothing to zero might be the best approach, if it is too difficult to change how the null value works later in the process. Designers that care to distinguish between sets that sum to zero and empty sets could always check "count".

**Comment by rogerl50** [comment]
> Designers that care to distinguish between sets that sum to zero and empty sets could always check "count".

They could, but the problem is that acting on that knowledge is difficult without a convenient IF statement. A mathematician (which I am) would argue that an empty sum is also zero.
