### ISSUE TITLE
changing `id` doesn't update `inheritFrom`, `linkedToSeat`, `onlyVisibleForSeat`

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#1125]
Changing the `id` of a widget _does_ update `parent` of its children and `deck` of its cards.

It could also update the ID in routines but I feel like that's too dangerous.

**Comment by robartsd** [comment]
> It could also update the ID in routines but I feel like that's too dangerous.

Perhaps the editor could scan for the ID in routines and prompt?
