### ISSUE TITLE
Empty rooms are still created with version 1

### ISSUE THREAD

**Issue by robartsd** [ArnoldSmith86/virtualtabletop#1130]
[Empty state version number in room.mjs](https://github.com/ArnoldSmith86/virtualtabletop/blob/main/server/room.mjs#L239) should probabaly match [version number in fileupdater.mjs](https://github.com/ArnoldSmith86/virtualtabletop/blob/main/server/fileupdater.mjs#L1).

**Comment by ArnoldSmith86** [comment]
In theory, probably. In practice it doesn't make a difference. It's just one simple `if` and a `for` that iterates over an empty array.

**Comment by robartsd** [comment]
> In theory, probably. In practice it doesn't make a difference. It's just one simple `if` and a `for` that iterates over an empty array.

Yes, but doesn't fileupdater not get called until the room is unloaded then loaded again? If an empty state gets worked on as version 1, then saved, is it possible that fileupdater could mistakenly make changes that would not be needed or even apply an outdated default that should not be applied?

**Comment by ArnoldSmith86** [comment]
Hmm, it should be called immediately. But maybe it isn't.

**Comment by robartsd** [comment]
You're right, empty state is called through fileupdater to create the room state.
