### ISSUE TITLE
sortWidgets() and shuffleWidgets() functions do not need to belong to Widget class

### ISSUE THREAD

**Issue by robartsd** [ArnoldSmith86/virtualtabletop#1135]
Utility functions for sorting and shuffling widgets were created as methods of the Widget class, but there is no real need for them to belong to the widget class. These should probably be moved from widget.js to main.js.

**Comment by RaphaelAlvez** [comment]
What??? is there any other function like this in main.js?
this is used in routines and I don't recall it being used in a higher level
