### ISSUE TITLE
CSS dynamic variables

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1147]
When I was testing the new `dragging` property, I set up a widget with the following css:

```JSON
"css": {
    "default": {
      "background-color": "${PROPERTY dragColor}"
    }
  }
```

`dragColor` was a custom property set on the widget by another routine.  It was either the `playerColor` or it was null.  The css handled the switch from null to the color just fine.  But when the `dragColor` changed back to null, the css dynamic variable didn't react.  If instead of going to null, I set the `dragColor` to "white", it worked fine.  If I set the `dragColor` to false, it worked fine.

Refreshing the browser window when `dragColor` was null did reset the background.  Not sure if this is intended behavior or an issue when css dynamic variables encounter a null.  @robartsd ?

**Comment by robartsd** [comment]
@ArnoldSmith86 wrote the code for CSS dynamic variables, so he would be more familiar with how it works. Based on what you describe, my guess is that properties being deleted from a widget (setting a property to `null` causes it to be deleted) are not checked to see if those properties are used in the CSS. I'm pretty sure that this is unintended, since the display should always be the same after a refresh.

**Comment by robartsd** [comment]
I'm also experiencing a problem using CSS dynamic variables if the CSS property for a card comes from the deck.

**Comment by ArnoldSmith86** [comment]
> I'm also experiencing a problem using CSS dynamic variables if the CSS property for a card comes from the deck.

Do you have an example?

**Comment by robartsd** [comment]
I'm working on `transportationDeck` for [Fun with Transit](https://virtualtabletop.io/T2R_NewYork). `css` property in `cardTypes` or `cardDefaults` does not work, but same property set directly in the card does work. I'll work on a test case.

**Comment by ArnoldSmith86** [comment]
If it works in the PR, we don't need a test case, I guess.

**Comment by robartsd** [comment]
Sorry, I was mistaken. I was not using the correct syntax.
