### ISSUE TITLE
`classes` in `cardDefaults` do not get applied by the initial delta

### ISSUE THREAD

**Issue by robartsd** [ArnoldSmith86/virtualtabletop#1151]
Setting `classes` in `cardDefaults` does not apply the classes to the card unless the deck gets opened in the JSON editor. I discovered this issue when attempting to build a deck in which I wanted all the card types except one to have a particular class. Setting `classes` in each card type does work.

**Comment by 96LawDawg** [comment]
See additional information in (now closed because of duplicate #1193).

**Comment by robartsd** [comment]
In `applyDeltaToDOM()`, I think something similar to `applyForCardType` needs to happen for properties in `cardDefaults` when `delta.deck` is not undefined.
