### ISSUE TITLE
Seats and `TURN` need to support skipping a player

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1170]
In a game I was building, I came across a need to add a feature to seats.  In the game, players can leave the round early (but still sit in their seats).  Using `TURN`, there is no easy way to keep skipping a player.  It would be nice to have a property `skipTurn` that is true or false and defaults to false.  If true, then that player will be excluded from being selected during a `TURN`.

There is a workaround (and is apparently what was intended when seats were designed).  It works like this (just documenting how to do it).  When the condition exists for a player to be skipped, set the property `hideTurn` to true.  All that does is make sure the seat does not glow.  It does not actually skip the turn.  To skip the turn, you have to change the `source` property of seats using something like:

```JSON
{
      "func": "SELECT",
      "type": "seat",
      "property": "hideTurn",
      "relation": "!=",
      "value": true,
      "collection": "seatTurn"
    },
    {
      "func": "TURN",
      "source": "seatTurn"
    }
```

**Comment by robartsd** [comment]
Great workaround. Could also use a custom `skipTurn` property instead of `hideTurn` then if somehow the turn gets set to the seat that should have been skipped, it will be shown instead of hidden. I do like the idea of defining `skipTurn` in the engine though.

**Comment by RaphaelAlvez** [comment]
workaround.... puff.... this was added exactly for this situation 😒

hideTurn was added because our seat is inspired by some early seat that were created using basic widgets. Those seats did not have turn indication.

**Comment by 96LawDawg** [comment]
Yes, but I know you read the comment that hiding does not actually skip.  If you hide a turn and don't use my "workaround" then it is nobody's turn.

**Comment by 96LawDawg** [comment]
All good.  There is a workaround that I think you helped me with.  We can close the issue if you really want.  But both @robartsd and I at least think it is worth making a solution someday.
