### ISSUE TITLE
Scoreboard widget

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1171]
Since we can dream whatever we want, I have decided I want a scoreboard widget.  This could take a variety of forms, but here's what I was thinking of ...  I have made several games where scores are increased or decreased after each round.  For a simple example, think of the card games hearts or spades.  A manual counter can be used in these situations, but are susceptible to errors.  Say your score is 382.  You want to increase that by 17.  But partway through the update you forget where you were.  There is no way to go back.  And with automatic scorekeeping, you have to just trust the computer and can't see the previous entry (which also makes debugging harder).  If there are multiple scores changing at the end of a round, seeing whether people's scores went up or down and by what amount is much harder than it is in person with pencil and paper.

So my idea is to replicate the piece of paper concept.  Think something like a counter, but below it would be an "Enter" button.  You can click on the plus or minus buttons to change the counter, or type as you currently can, or change it programmatically.  When the score is right, press Enter and it will be recorded in a small sequential log.  You scroll through the log using a little scroll bar and you can go back and see all the score entries.  The score entry and log would be in the same window.  If you start hitting plus or minus or typing a score, the log disappears and the typical label area shows.  This wouldn't have to be much larger than the current counter. I don't think this would be too hard to make (says the guy that doesn't code anything) and I can think of probably a dozen games that would benefit from it.

Of course, a completely different scoreboard widget might be something that displays a box with a list of all `playerNames` and the current scores.  Could be sorted by seat number, by alpha, or by score.  That is a bit more complicated than my other suggestion and would not be as useful as the other suggestion because you can already look at the counters under a player's name/seat and see what the scores are.

**Comment by robartsd** [comment]
Game designer implementation would be a composite widget with the history of scores stored as an array in some widget property:

- counter (label with +/- buttons)
- record entry button - automation gets the history array, pushes the current counter value to the end of the array, saves the array
- show history button - unhides the history display widget and initializes it's text to display the last n entries
- history display widget - just a basic widget to show the history text
- buttons to scroll history - changes history display widget to show a different subset of array entries
- hide history button - hides the history display widget

**Comment by 96LawDawg** [comment]
And a reset button to erase the history.

**Comment by RaphaelAlvez** [comment]
I really like the idea of keeping the history just like in paper. this is the first composed widget that I would like to see implemented in a long time

**Comment by rogerl50** [comment]
I'm envisioning a simple widget that displays the history. For each player, the history contains a record of the amount by which his/her score was increased and "committed" (i.e. saved). Showing the history displays both that record and also the total score for each player. Changing the score is done via widgets that are not part of the score widget itself, but rather programmatically affect the widget contents. The game designer then has the option of allowing updates to the total score, or adding a per-turn score, using different properties of the scoreboard widget.

**Comment by 96LawDawg** [comment]
> The widget itself would probably just consist of a holder with additional properties. 

No need for a holder probably.  Just another basic widget.  Otherwise I agree with everything you suggest and it sounds like it would meet the need of what I originally suggested.

**Comment by rogerl50** [comment]
@96LawDawg A little more detail. I'm envisioning a widget that has four display states: none (you want to hide it), a button-appearing object that by default just says "Scores", a totals-only display, and a detailed display. The form of the display is described by a property of the widget.

The widget maintains a list of by-turn (or whatever) scores for each player together with the total for each player. There are functions provided that allow you to add a new turn score for a given player (which then gets added to his/her total score), or simply to set or modify a player's total score. I think this gives you pretty much all the flexibility you need.

This would be implemented by a new function that allows you to set the display state of the widget, add or remove players by name, and do the score modification described above.

Suggestions or comments?

**Comment by 96LawDawg** [comment]
> @96LawDawg A little more detail. I'm envisioning a widget that has four display states: none (you want to hide it), a button-appearing object that by default just says "Scores", a totals-only display, and a detailed display. The form of the display is described by a property of the widget.
> 
> The widget maintains a list of by-turn (or whatever) scores for each player together with the total for each player. There are functions provided that allow you to add a new turn score for a given player (which then gets added to his/her total score), or simply to set or modify a player's total score. I think this gives you pretty much all the flexibility you need.
> 
> This would be implemented by a new function that allows you to set the display state of the widget, add or remove players by name, and do the score modification described above.
> 
> Suggestions or comments?

I don't understand the need for the first display state (hidden).  If I want to hide something, I just move it offscreen or set scale to 0 or cover it or link it to a seat or whatever.  I mean, that state would make it easier, but I don't see that it is necessary.

Would the individual scores be stored in some type of array in the widget.  Like: "Player1": [0,5,9,22]?

As far as adding and removing players, we need to take seats into account.  If there are no seats, then I'm not sure how a function would add a name.  Click on a button and it gets the playerName and adds it?  For seats, we can just access the "player" variable in the seat.  Would be nice if there was a direct (in the code - no room designer intervention required) link between sitting in a seat and adding the player to the scoreboard widget.

Would also be nice to have a function to sort the display: by seat number (default), alpha by name, or total score (low to high or high to low).

**Comment by rogerl50** [comment]
> 
> I don't understand the need for the first display state (hidden). If I want to hide something, I just move it offscreen or set scale to 0 or cover it or link it to a seat or whatever. I mean, that state would make it easier, but I don't see that it is necessary.
Agree

> 
> Would the individual scores be stored in some type of array in the widget. Like: "Player1": [0,5,9,22]?
> 
I've been thinking more about this as well. My current line of thinking would put each player's score as a property in their seat.

> As far as adding and removing players, we need to take seats into account. If there are no seats, then I'm not sure how a function would add a name. Click on a button and it gets the playerName and adds it? For seats, we can just access the "player" variable in the seat. Would be nice if there was a direct (in the code - no room designer intervention required) link between sitting in a seat and adding the player to the scoreboard widget.
With the approach above, there would be no need to add players - every player would have a score.

> 
> Would also be nice to have a function to sort the display: by seat number (default), alpha by name, or total score (low to high or high to low).
Sure. It would be nice :smiley:

Putting the scores in the seats really reduces the scoreboard widget to a display widget. Not a bad thing, just an observation.

Some games use turn-by-turn scoring, while others just keep a total score. I guess I'd propose to leave this up to the game designer. The total score summary would always be available, but the game designer would not make the detail display available if there are no turn-by-turn scores. This would put the burden of keeping the turns straight on the game designer (which is where it belongs). Thus in a totals-only game, each player might have a counter to adjust his/her score, while in a turn-based game, the "next turn" button or "next player" button could have the side effect of adding the score for the current turn to the player's score array.

More thoughts?

**Comment by 96LawDawg** [comment]
All that sounds great.  And I like forcing integration with seats.  In this way, the scoreboard is really just an optional add-on to seats and simplifies things.  No seats = no scoreboard widget.  I'm fine with that.

@rogerl50, you planning on coding this yourself or are we just fleshing out details for someone else to code later?

**Comment by rogerl50** [comment]
> @rogerl50, you planning on coding this yourself or are we just fleshing out details for someone else to code later?

If by "coding this yourself" you mean "writing code and then having @ArnoldSmith86 fix it so it works", then yes, I'm coding it myself. :rofl:

**Comment by RaphaelAlvez** [comment]
> > @rogerl50, you planning on coding this yourself or are we just fleshing out details for someone else to code later?
> 
> If by "coding this yourself" you mean "writing code and then having @ArnoldSmith86 fix it so it works", then yes, I'm coding it myself. :rofl:
> 

Widgets creation is a part of code tht I'm familiar with. I can definitely help with this.

Main problem might be with the html type of this widget that might be different from others. I imagine you are going to use a table

**Comment by RaphaelAlvez** [comment]
Ok so if we are making this a widget here are the most important stuff it needs to address (In my opinion and by topics):

# real life equivalent
- this is not a personal counter (example: not for monster counter in KoT or life points in MTG)
- This is related to a piece of paper where the group keeps track of each round score
- some games use tally with just one cell per player and other use the sum+round in each cell on a new row each round
- some games have cards 

# features it needs to have
- readable and **GET**table format for data
- sortable
- resetable from a template
- new round sum values from a template
- simple calculations per cell:
    - sumColumn[1,5], sumLine[1,] (not including heading)
    - previousValue + PROPERTY value OF counter1
- values should be saved as numbers or strings. Not formulas
- css customization
- scrolling 

# Routines
- reset
- sort
- new round

# extra stuff
- display player turn 
- hide old rounds
- shorthand for select widgets with property x value y and get sum of value
- tally count
- live preview of round points
- hide unused seats line
