### ISSUE TITLE
add and/or remove classes with a timeout function

### ISSUE THREAD

**Issue by robartsd** [ArnoldSmith86/virtualtabletop#1173]
As can be seen in #1167 briefly setting a class can be a great trigger for css animations and transitions. It would be great if we had a generalized solution for game designers to have a class set then removed with a timeout without persisting in the synced state. A client joining just after the message gets sent would not be aware of it at all even if previously connected clients have not processed the timeout removing the class.

**Comment by robartsd** [comment]
Perhaps there should be an `animatePropertyChanges` property. It would accept an array indicating properties that cause classes to be temporarily added when a widget property changes (`delta[propery name] !== undefined` for any delta after the initial delta). Triggers could also be specified as objects:
```
"animatePropertyChange": [
  {
    "property":"property name",
    "className":"customAnimationClass",
    "duration": 2000
  }
}
```
This would add "customAnimationClass" to the widget every time "property name" changes then remove it after 2 seconds. If an element is not an object, it would be taken as "property", className would use a default value of `animate_${escapeID(property)}`, and duration would use a default value of 1000.

**Comment by flackr** [comment]
I filed #1425 for creating web animations which may also support some of these use cases.

Note that for the purposes of starting css animations or transitions you don't even need to wait any time - you can call a property which forces a style recalculation like `Element.offsetTop` and then immediately change the value to the new value. I've done this here to allow transitions between parent changes: https://github.com/ArnoldSmith86/virtualtabletop/pull/1423/files#diff-cda5cc45823227e11eaa23e3e718a50f300e3fa6183280043e48e4e55b78024dR183
