### ISSUE TITLE
Child widgets of pawns are not visible

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1187]
I don't know why you would want to do this.  I just did it when playing around with something.  But if you make a pawn (`"classes":"classicPiece"`), then the child widget is only visible through the pawn itself.  I tried playing with the overflow property of the css of the pawn and the child, but didn't have any luck other than making a scrollbar.  Not sure if this is a "bug", but it is NOT a result of the way that the new pawn is structured.  I went back to a really old PR test room with legacy pawns and the problem happened with it also.

**Comment by robartsd** [comment]
Can't fix. Creating shapes with clip-path or mask in css effectively makes the element `overflow:hidden`

**Comment by 96LawDawg** [comment]
Closed by #1506
