### ISSUE TITLE
COMPUTE does not work with operand3

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#119]
For a simple addition operation, I tried to follow the sample on the wiki.
{
  "func": "COMPUTE",
  "operation": "+",
  "operand1": 2,
  "operand2": 3,
  "operand3": 3,
  "variable": "result"
}

That only adds operand1 and operand2.  The result is 5 when it should be 8.

**Comment by larkob** [comment]
The add operation only has two operands, so operand3 cannot be used. I'll try to make it more obvious in the documentation, but this is not a bug. Only `slice` and `substr` use operand3.

**Comment by larkob** [comment]
@96LawDawg Please let me know if the documentation is better now and close the issue once everything is addressed.

**Comment by 96LawDawg** [comment]
That clears it up.  I was wondering about operand3 when I was putting the first tutorial together, but never got around to testing it.  Thanks.  Issue closed.
