### ISSUE TITLE
spinner backgroundCSS does not work with urlPrefix

### ISSUE THREAD

**Issue by robartsd** [ArnoldSmith86/virtualtabletop#1190]
It appears that the backgroundCSS property of spinner was overlooked when wrapping css properties with mapAssetURLs().

**Comment by 96LawDawg** [comment]
True, but you can accomplish the same thing by using `spinnerCSS` and `css`.  See the examples in the Spinner tutorial variant 3 (customizing the arrow) and variant 5 (styling examples).  It's been so long I can't really remember, but it seems like `backgroundCSS` never did much of anything.

**Comment by robartsd** [comment]
I don't think it is related to this issue, but the spinner in the 4th column of styling examples crashes the client when attempting to spin (Chrome on ChromOS).
