### ISSUE TITLE
Font classes in decks do not load properly

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1193]
Using `"classes":"gothic_font"` in a deck does not work on initial room load.  To get it to work, you have to open the deck in the JSON Editor which works on all the cards instantly, or move the card to the hand which works on only the moved cards.  Strange that moving to the hand has this effect.  An identical holder without `"childrenPerOwner":true` does not trigger the font to load correctly.  You can see this happening in https://virtualtabletop.io/Crow.

I thought this might somehow be related to #1172 but it is not, at least not directly.  I went back to an earlier PR test room and the same problem exists.  But something with that same section of code may still be off??  You know I don't know what I'm talking about, but I'm trying to be helpful. 😃

**Comment by robartsd** [comment]
I believe this is a duplicate of #1151 classes in cardDefaults does not work. I had not discovered the hand workaround but had observed the JSON editor workaround.

**Comment by 96LawDawg** [comment]
Agree.  Didn't see/don't remember that one.  Closing this one because of duplication.
