### ISSUE TITLE
`"holder":["foobar"]` crashes client 

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1197]
I was trying to `COUNT` a specific holder.  I had been working with collections so much, instead of just putting the name of the holder in the holder property, I tried to use the brackets [ ] like you do to make an anonymous collection.  That froze the room.  I always say you can't fix stupid (that would be me), but maybe the code can be fixed to avoid that or at least treat it as an anonymous collection so the room doesn't freeze.

**Comment by robartsd** [comment]
Even if we don't make it work, we should make it so that it does not crash the client.

**Comment by 96LawDawg** [comment]
I forgot about this error and did it again.  This time, I opened it up on my client and got the console feedback to help whoever drafts the fix for this.
![Screenshot 2022-06-13 155038](https://user-images.githubusercontent.com/76912527/173443336-2dd1de05-8b58-4af3-9e54-c7e816692a76.png)

**Comment by rogerl50** [comment]
There are many other cases of this specific issue (e.g. RECALL). But there are lots of places in the `evaluateRoutine` code where things can crash. For example,
```JSON
  "clickRoutine": [
    {
      "func": "CALL",
      "routine": [
        "fooRoutine"
      ]
    }
  ],
  "fooRoutine": []
```
dies trying to evaluate `a.routine.match(/Routine$/)`.
