### ISSUE TITLE
`owner` is broken for hands with piles

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#1202]
The public library game `Animal Race` has a hand in the top left that has a pile of cards in it.

When dragging a card out of it, its `owner` is not reset so nobody can see it (until it gets dropped into a holder). It does however still work for the last card.

A recent PR changed the order of `parent = null` and `owner = null`. That's probably the cause but I didn't look into it yet.

**Comment by robartsd** [comment]
`Widget.moveStart()` sets `this.currentParent = widgets.get(this.get('parent'))`. Perhaps `this.currentParent` should actually be `widgets.get(this.get('_ancestor'))`.

**Comment by robartsd** [comment]
I'm not finding the PR you mention that changed the order (I'm assuming this is in `Widget.checkParent()` - perhaps I'm not looking for the change you mention in the correct part of the code).

**Comment by ArnoldSmith86** [comment]
I was probably thinking of #1139 . Since that code change is in `MOVE`, it does not seem like it's the culprit.

**Comment by robartsd** [comment]
`currentParent` is used in:

- `Holder.onChildAdd()`
  - tests if holder is already the child's parent
- `Widget.checkParent()`
  - checks `currentParent.get('childrenPerOwner')` (this is where the raised issue has problems)
- - calls `currentParent.dispenseCard()` (`Pile.onChildRemove()` also calls `dispenseCard()` if the pile is in a holder)
  - deletes currentParent
- `Widget.moveToHolder()`
  - sets currentParent if needed
  - calls checkParent(true) if currentParent is not holder
- `Widget.moveStart()`
  - sets currentParent
- `Widget.move()`
  - compares hoverTarget to currentParent
