### ISSUE TITLE
Custom Properties with `inheritFrom`

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1210]
This is just a minor thing in the JSON Editor view that does not impact development or gameplay in any way.  But custom properties in seat widgets are not colored orange and sorted the way custom properties are in other widgets.  They are colored yellow and put at the top of the JSON.

**Comment by ArnoldSmith86** [comment]
Do you have an example?

A quick test didn't show the issue:

![image](https://user-images.githubusercontent.com/73538315/168465594-4ca1c8ef-89dc-49d4-90e9-1f5f0076de56.png)

**Comment by 96LawDawg** [comment]
So it turns out this isn't a seat issue.  But it is an `inheritFrom` issue.  An a widget with inheritFrom, the custom properties are yellow.

![Annotation 2022-05-15 092246](https://user-images.githubusercontent.com/76912527/168477705-51038467-bec1-45ef-b82d-6f8baae6e632.png)

**Comment by ArnoldSmith86** [comment]
Yeah, that seems more like it. It's a feature that widgets with `inheritFrom` are displayed differently (so the editor doesn't add non-existent properties to the text) but it shouldn't be a problem to make custom properties orange anyway.
