### ISSUE TITLE
JSON editor CSS prompts

### ISSUE THREAD

**Issue by robartsd** [ArnoldSmith86/virtualtabletop#1221]
From @96LawDawg 's comment in PR #1196 :

Maybe we should also change the JSON Editor prompt for css from "" to {}. I don't know about other people, but I much prefer to use the object form now. Much easier to read.

But if we do that, we would also have to tweak the way the JSON Editor suggests a few common CSS properties (background, border-radius, border, color, and font-size). We should probably get rid of border-radius as a suggested CSS property since borderRadius is now a default widget property and the wiki says it is the preferred format.

**Comment by rogerl50** [comment]
Do we still want the various --wc??? tags that are currently in the CSS code to appear in the new object-focused CSS edit stuff? For example, if the widget is a button, currently one gets `'--wcMain: #1f5ca6', '--wcMainOH: #0d2f5e', '--wcBorder: #0d2f5e', '--wcBorderOH: #1f5ca6', '--wcFont: #ffffff', '--wcFontOH: #ffffff'` as options in the editor.
