### ISSUE TITLE
client crash when loading deck assets

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#1224]
1. Add the "Decks" assets from the public library.
2. Load a few different variants.
3. Watch the client crash (reload the page).

**Comment by 96LawDawg** [comment]
I can't replicate the problem.  Maybe it is step 2.  What do you mean by load a few different variants?

**Comment by ArnoldSmith86** [comment]
https://user-images.githubusercontent.com/73538315/169714539-e99747a4-b44b-4a77-845f-cfea50689701.mp4

**Comment by 96LawDawg** [comment]
That's what I thought you meant.  Doesn't crash for me in Edge or Chrome.

**Comment by rogerl50** [comment]
I tried exactly that and did not get a crash (in production). What I *did* get is many many messages saying "Could not add widget "<something>" because its parent "<something else>" does not exist!"
