### ISSUE TITLE
moving cards to seat creates a problem

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#1253]
it seems like the pile creation code is not checking the owner of the cards and creates one pile with a owner and includes the cards with the correct onwer set to them but in the worng pile (this pile have a different owner)

**Comment by mousewax** [comment]
[Times_Up__Title_Recall.zip](https://github.com/ArnoldSmith86/virtualtabletop/files/9031882/Times_Up__Title_Recall.zip)

**Comment by 96LawDawg** [comment]
Most likely related to #1116
