### ISSUE TITLE
multi select should support dragging

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#1255]
maybe add that ctrl drag would drag all select widgets

also maybe area select

**Comment by rogerl50** [comment]
For ctrl-drag, what I think you are saying is: if there are several widgets selected (i.e. outlined in yellow), then ctrl-mousemove after a ctrl-mousedown on any one of those widgets will move all of them (unless they are `movableInEdit: false`). And ctrl-drag on a non-selected widget will be the same as a drag. Is that right?

**Comment by rogerl50** [comment]
> Ctrl drag is already a feature that allows you to drag widgets with movable false. Not sure if it works with movable in edit false

Huh. DIdn't know that. After some experimentation, it looks to me as though drag is controlled by 'movable' while ctrl-drag is controlled by 'movableInEdit'. So when in the JSON editor, I think that the functionality you want is:
```
when (drag or ctrl-drag)
    if target is selected (yellow) then
        move_targets <- all selected widgets that can be moved depending on whether the ctrl key is down
   else
        move_targets <- the widget under the mouse, if it can be moved, otherwise empty
   move all move_targets
```
Is that right?

**Comment by 96LawDawg** [comment]
This is implemented in the new editor UI.
