### ISSUE TITLE
`MOVE` from hand takes cards from other players hands

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1259]
Bug is as stated.  Likely related to other recent issues on the subject (like #1259) and as discussed in #933.

**Comment by 96LawDawg** [comment]
Was going to start looking at Raphel's changes to #933, but wanted to look at this one first again.  Still broken, but wanted to explain what it does.  Create a hand that makes piles.  Open two browsers and move a few cards into each hand.  Add a move button to MOVE from the hand to another holder.  The button moves entire piles and not cards.

**Comment by RaphaelAlvez** [comment]
> Was going to start looking at Raphel's changes to #933, but wanted to look at this one first again.  Still broken, but wanted to explain what it does.  Create a hand that makes piles.  Open two browsers and move a few cards into each hand.  Add a move button to MOVE from the hand to another holder.  The button moves entire piles and not cards.

This does work on 933 now. 933 does not fix 2 piles per owners.

**Comment by 96LawDawg** [comment]
> > Was going to start looking at Raphel's changes to #933, but wanted to look at this one first again.  Still broken, but wanted to explain what it does.  Create a hand that makes piles.  Open two browsers and move a few cards into each hand.  Add a move button to MOVE from the hand to another holder.  The button moves entire piles and not cards.
> 
> This does work on 933 now. 933 does not fix 2 piles per owners.

#933 does not exactly fix this.  MOVE from hand is broken in the sense that pressing a button with a MOVE routine sometimes takes card from your hand, sometimes from another player's hand.  I can't figure out the pattern.  Doesn't matter if the cards are in piles in the hand or not.  But to me, I should not be able to press a MOVE button and take a card from some other player's hand.  I could probably prevent this through a series of checks and JSON, but don't you think the default should be that MOVE only takes cards from my own hand?

But #933 does fix the pile problem that is present on production.  As I said above, right now, MOVE from a hand with piles takes the whole pile.  In #933, it only takes 1 card.

**Comment by 96LawDawg** [comment]
But, on further reflection, if I SORT my hand, it sorts all player hands.  If I FLIP my hand, it flips all player hands.  This is no different.  And it would be a file updater.  And I've never even used this because why not just drag from your hand.  So we could close this issue as a non-issue.

**Comment by 96LawDawg** [comment]
This does not need to be fixed.
