### ISSUE TITLE
JSON Editor Bug in Wide View

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1283]
There is a problem when using the Wide View version of the JSON Editor.  I have 2 videos below that show how this happens.  It only seems to be a problem in deeply nested routines.  I have not been able to duplicate it other than in my poker room, but I have not tried many other rooms.  I have uploaded my current poker room file to https://virtualtabletop.io/elmq.  Here is what happens.

In video 1, inside of a deeply nested routine, I copy a snippet and paste it somewhere inside the middle of a routine.  It turns into white text because I have not reselected the widget.  But I should still be able to work with the widget the way it is, and until recently I could.  But as you can see in the video, when I try to select JSON text to edit, the highlighter does not work property.  When in narrow view, it works as it should.

In video 2, I paste the same snippet at the end of an area.  Again it turns white.  I try to position the cursor to delete the extra trailing comma.  That used to work.  Now it doesn't.  Once I position the cursor in the video, I press the delete key and you can see it moving strangely.  In the narrow view, it works fine.

Please help.  This caused significant frustration for me recently.  I switched to the narrow view to fix the problem, but I don't like working in the narrow view, especially with deeply nested JSON.  This definitely came about as a result of some of the recent changes to the JSON editor from @rogerl50.  I went back to PR 1222 (before the full-time JSON tree was made available).  Things worked as expected in that PR.

https://user-images.githubusercontent.com/76912527/181935603-9c4248a8-77cb-49dd-9590-ec6d677d6b9f.mp4

https://user-images.githubusercontent.com/76912527/181935610-0961dfce-da06-4ef3-ad0d-b061879677ea.mp4

**Comment by ArnoldSmith86** [comment]
Should be easy to find and fix. I'll have a look when I have some time.

**Comment by rogerl50** [comment]
I'll take a look, but probably not until Thursday or Friday. Sorry.

**Comment by 96LawDawg** [comment]
That's fine.  Thanks.  @ArnoldSmith86 has already started a bit and DM'd me.  He noticed that it seems to be browser specific.  I have the problem in Chrome and Edge in Windows.  No problem in Firefox.  He doesn't seem to have the problem in Linux.  Just wanted to put that stuff here in the issue so everyone knows.

**Comment by 96LawDawg** [comment]
Using `git bisect` I traced the problem to commit 88e7e1bd1592deccbaa6a5ea79406b97e48ad075 in #1245.

**Comment by rogerl50** [comment]
I wonder if there is some difference in grid support among these browsers

**Comment by 96LawDawg** [comment]
You may be on to something there.  According to the CSS compatability guidelines, as far as I can tell, there shouldn't be any meaningful difference in the code you used.  However, I figured out how to display the grids in the console.  There is some difference in the width of the dividing scrollbar.  In Firefox, there are 2 numbers stacked on top of each other and the visible numbers are 5 and -2.  In Edge, there is only one number on each side of the scrollbar and they are 4 and -3.  All the other numbers in both browsers are the same.  That is a possible source of the problem.

![FF Grid](https://user-images.githubusercontent.com/76912527/182051533-b6f376be-6f20-4513-89b2-e0141082484f.jpg)

![Edge Grid](https://user-images.githubusercontent.com/76912527/182051536-4ef8265b-daa3-4982-b88c-69bec89d9277.jpg)

**Comment by ArnoldSmith86** [comment]
I still can't reproduce this. A few things you can check:

- After it breaks, check (and post) the results of `$('#jeTextHighlight').innerText == $('#jeText').innerText`, `$('#jeTextHighlight').scrollTop` and `$('#jeText').scrollTop` in the console.
- Your video 1 suggests that it already breaks before pasting but it might be unrelated: you copy some text, then you deselect it, press ENTER and then paste. After pressing ENTER, the cursor already seems to be in the wrong place (in the line after the empty line). Can you check if highlighting text already leads to wrong results at that point?
- Please try the same thing further up the text. Try and see if there's a certain line after which this occurs. In the beginning I had some slight asynchronous behavior when long lines caused different line-breaks in the two texts or similar things.
- Please do a few more tests in the commit you posted as the culprit and the one before it in order to be more certain that it's the correct one.

**Comment by 96LawDawg** [comment]
> * After it breaks, check (and post) the results of `$('#jeTextHighlight').innerText == $('#jeText').innerText`, `$('#jeTextHighlight').scrollTop` and `$('#jeText').scrollTop` in the console.

I don't know how to do that.  When I look at the console in Edge, there are no entries, errors or warning when I cut and paste.  Where should I look and do I have to do anything to trigger it?

> * Your video 1 suggests that it already breaks before pasting but it might be unrelated: you copy some text, then you deselect it, press ENTER and then paste. After pressing ENTER, the cursor already seems to be in the wrong place (in the line after the empty line). Can you check if highlighting text already leads to wrong results at that point?

Yes, it breaks after pressing ENTER and before pasting anything.

> * Please try the same thing further up the text. Try and see if there's a certain line after which this occurs. In the beginning I had some slight asynchronous behavior when long lines caused different line-breaks in the two texts or similar things.

The first place it breaks is in the first `IF`.  The first `thenRoutine` is fine.  It breaks in the `thenRoutine` under the `elseRoutine`.

> * Please do a few more tests in the commit you posted as the culprit and the one before it in order to be more certain that it's the correct one.

I tried a different route this time, using `checkout`.  The first commit in #1245 is af7b7d7.  I did a `git checkout` of that commit.  The copy/paste/highlight works as it should.  The second commit is 88e7e1b (the one the bisect identified previously).  I did a `git checkout` there and the highlight was broken.

**Comment by 96LawDawg** [comment]
> * After it breaks, check (and post) the results of `$('#jeTextHighlight').innerText == $('#jeText').innerText`, `$('#jeTextHighlight').scrollTop` and `$('#jeText').scrollTop` in the console.

The first one gives a result of 1924 and the second one 1909.  I don't know what this means, but I assume that the difference is the problem because it shows that the invisible text and colored text are NOT being highlighted at the same place.  Just for fun, I also did this before making it break and the numbers were the same (1909).

**Comment by 96LawDawg** [comment]
To me, one of the strangest aspects about this is that it does NOT break in the narrow view JSON editor mode.  Which completely undercuts Rogers and my idea above that maybe the grid is off.  Because moving into the wide view doesn't change the grid.  I just did the console grid overlay thing in narrow and wide view.  They are the same.  I didn't think of the other day when I was posting.  And I just did the console `$('#jeText').scrollTop` stuff in narrow view, but of course the numbers are the same because the narrow view doesn't break the highlighting.

**Comment by 96LawDawg** [comment]
Here's another really stupid (and damn frustrating) thing.  I can't seem to get the error to happen in anything except my poker room and only on that one button (claimbutton).  I thought maybe it was because of the nested structure.  The problem appears in this sort of situation: IF --> elseRoutine --> IF and then in the following thenRoutine and elseRoutine.  But there is another button in my poker room (addBet) that has a similar structure.  No problem in that button.  Yoink has a button (nextRound) that has a similar structure.  No problem there.

The only thing obvious I could see different about the routines is my notes in the function before the IF statement.  It is
```JSON
 {
      "Note": "Now fill in the name and assets information for each player.",
      "Note1": "If player is folded or if seat is empty, move holder offscreen.",
      "func": "SELECT",
      "property": "id",
      "value": "panelP1"
    },
```
This is a holdeover from the days before we had better note notation.  Now here is where the actual mindfuck (pardon the language but that is the only way I can describe it) comes in.  If I delete "Note" and its comment, same problem.  If I delete "Note1" and its comment, the problem goes away.  What is going on?  But maybe this will help someone nail down the issue.

**Comment by ArnoldSmith86** [comment]
Can anyone reproduce this on any other Windows machine?

**Comment by ArnoldSmith86** [comment]
> But maybe this will help someone nail down the issue.

Can you check by highlighting the text if those lines get wrapped differently in the two texts?

**Comment by ArnoldSmith86** [comment]
> If I am still a trustworthy enough source

Of course you are. Doesn't really matter anyway because it works without that commit.

Next step would be to isolate which change in that commit causes the problem. Can you try to change a few things back to their previous state and check if it's still broken?

Prime suspects would be the commented block in `jeDisplayTree` or the added borders in the CSS.

**Comment by 96LawDawg** [comment]
> Can you check by highlighting the text if those lines get wrapped differently in the two texts?

Do you mean do the Note and Note1 lines get wrapped differently in the wide view/narrow view or do they get wrapped differently before or after the breaking behavior?  Either way, the answer is no (except that in narrow view, they wrap differently as expected because of the editor being narrow).

I did learn one other new thing just now.  If, after creating the break, I highlight somewhere else several lines of code away from the problem, then the problem fixes itself and I can go back to the area and highlight correctly.  But then any other changes cause it to break again.

**Comment by ArnoldSmith86** [comment]
> Do you mean do the Note and Note1 lines get wrapped differently in the wide view/narrow view or do they get wrapped differently before or after the breaking behavior? Either way, the answer is no (except that in narrow view, they wrap differently as expected because of the editor being narrow).

I meant the colored vs the invisible text.

**Comment by 96LawDawg** [comment]
> I meant the colored vs the invisible text.

I can't see the invisible text, so again I'm guessing that you wanted me to use the code snippets in the console?  If so, then the answer is that the numbers are the same because of what I just discovered.  Move the cursor away from the breaking area and everything fixes itself.

**Comment by ArnoldSmith86** [comment]
You can see the invisible text when you highlight it. That's why highlighting looks broken when the texts are not in sync.

But I see what you mean. When it breaks, those `Note` lines are not in view and when you scroll up to them, everything seems fine again?

**Comment by 96LawDawg** [comment]
> But I see what you mean. When it breaks, those `Note` lines are not in view and when you scroll up to them, everything seems fine again?

Yes.  Put the cursor anyplace other than the area where I pressed Enter to start the breaking behavior and it is fine.

**Comment by 96LawDawg** [comment]
One other new piece of information based on the video below.  I did a right-click inspect and change the color of the transparent text to red.  You can see the shift when I press Enter.  What's new is that as soon as I use the scroll bar or mouse wheel to move the JSON up or down, it goes back to normal.

https://user-images.githubusercontent.com/76912527/182895049-4f6f962b-79ac-4db5-88b8-a49248f31cb7.mp4

**Comment by 96LawDawg** [comment]
> Next step would be to isolate which change in that commit causes the problem. Can you try to change a few things back to their previous state and check if it's still broken?
> 
> Prime suspects would be the commented block in `jeDisplayTree` or the added borders in the CSS.

Line 46 in that commit is the breaking change: `border: 1px solid white;`

**Comment by 96LawDawg** [comment]
Thanks to @ArnoldSmith86, I think the fix has been found.  Changing line 15 in jsonedit.css from `--editorPaneWidth: 600px;` to `--editorPaneWidth: 602px;` resolves the problem.

**Comment by rogerl50** [comment]
> Thanks to @ArnoldSmith86, I think the fix has been found. Changing line 15 in jsonedit.css from `--editorPaneWidth: 600px;` to `--editorPaneWidth: 602px;` resolves the problem.

Seriously? That's kind of amazing.
