### ISSUE TITLE
Holder attribute to fully hide widgets underneath

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#13]
If one places a holder on top of (say) a holder for a deck, cards can still be dropped onto that deck and, from the user's perspective, they simply disappear. I'd like to have an option to a holder that prevents that from happening. LawDawg and I ran into this when building our poker room where we wanted to implement a player leaving the table by placing a "cover" over his/her spot. But cards could still be dropped there by mistake. (We eventually chose another solution). Another use case is that I wanted to keep my bank of available chips on the table so as to make editing easier during development (and later), so I hid them under a holder. Again, chips could be dropped there if they were dropped in the right spot and appear to vanish.

**Comment by robartsd** [comment]
Sounds like you actually want a widget property that would prevent widgets being dragged from finding drop targets that are covered by the widget. The drop target code currently looks at center to center distance (or an approximation thereof, I don't think diagonals are accurate) to determine which holder catches an item. Might be quite a challenge to refactor the code to account for visible overlap.

**Comment by robartsd** [comment]
I think the solution for the situation described is for the game designer to provide a button that changes the dropTarget property of the holders that should not be receiving widgets. I vote we choose not to try to implement this.

**Comment by larkob** [comment]
It sounds like the OP is asking for a holder that doesn't allow for any manual interaction, i.e. no in/out movement but probably also no actions within the holder, such as pile flip or pile shuffle. The holder content still should be visible and there should be a way to toggle the (un)frozen status of the holder. I'm not sure if this could already be done by changing multiple properties of the holder and it's content?

A simple alternative might be to place a transparent widget above the holder that would effectively block any interaction with the underlying holder and its content. Again, I'm not sure if that's already possible.

**Comment by rogerl50** [comment]
My use case was that I needed to make a holder inaccessible in normal usage but be able to make it available for maintenance. Moving it offscreen used to be pretty painful since it involved going through ghetto. So I tried placing it underneath a holder, but of course that didn't work. But with the new feature of ghetto allowing you to write changes back into the room, just moving it offscreen is fine.

I will close this issue, and if anyone has another use case, they can open a new issue.

**Comment by robartsd** [comment]
> A simple alternative might be to place a transparent widget above the holder that would effectively block any interaction with the underlying holder and its content. Again, I'm not sure if that's already possible.

Simple idea, but not simple to implement due to how drag and drop targets are searched for. A combination of a transparent cover and use of the holder's dropTarget property should do the trick.
