### ISSUE TITLE
Incrementing letters in duplicate command runs out of letters

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#1322]
[cinnamon-2022-09-09T094617+0200.webm](https://user-images.githubusercontent.com/73538315/189299222-1bf2e9fb-c637-448d-bfcb-a5fcc6a1cbcf.webm)

We should change it to "Excel style" where after `Z` comes `AA` etc. But this issue is not severe enough to further delay #837.

I started to write this but it doesn't quite work yet:

```Javascript
function increment(letters, amount=1) {
  const a = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split('');
  let number = letters.split('').map(l=>a.indexOf(l)).reverse().map((l,i)=>l*26**i).reduce((a,b)=>a+b) + amount;
  const result = [];
  while(number > 0) {
    result.push(a[number%26]);
    number = Math.floor(number/26);
  }
  return result.reverse().join('');
}

console.log(increment("A"));
console.log(increment("J"));
console.log(increment("Z"));
console.log(increment("AT"));
console.log(increment("VZ"));
console.log(increment("ZZ"));
console.log(increment("ZZZ"));
```

It might also be easier and shorter to through each letter and if it is `Z`, increment the previous one or add another `A` in front of it.

---

Second attempt. Even more broken. This is when I realized (again) that it just doesn't work like normal counting because going from `Z` to `AA` is like going from `9` to `11` (or `00`)...

```Javascript
function increment(letters, amount=1) {
  let number = parseInt(letters.split('').map(l=>l.charCodeAt(0)).map(c=>c<75?c-17:c+22).map(c=>String.fromCharCode(c)).join(''), 36);
  number += amount;
  return (""+number).split('').map(l=>l.charCodeAt(0)).map(c=>c<75?c+17:c-22).map(c=>String.fromCharCode(c)).join('');
}
```

---

Third attempt. Seems to be working.

```Javascript
function increment(letters, amount=1) {
  let result = [];
  for(const letter of letters.split('').reverse()) {
    const next = letter.charCodeAt(0)-64+amount;
    amount = Math.floor(next/26);
    result.push(next%26);
  }
  if(amount)
    result.push(amount);
  return result.reverse().map(i=>String.fromCharCode(64+i)).join('');
}
```

Nope. `console.log(increment("Y"));` is broken.

---

Fourth attempt. Seems to be working.

```Javascript
function increment(l) {
  const m = l.match(/Z+$/);
  const zs = m ? m[0].length : 0;
  if(m && zs == l.length)
    return 'A'+[...Array(zs)].map(l=>'A').join('');
  else
    return l.substr(0, l.length-zs-1) + String.fromCharCode(l.charCodeAt(l.length-zs-1)+1) + [...Array(zs)].map(l=>'A').join('');
}
```

**Comment by rogerl50** [comment]
It would also be cleaner and more efficient to have each iteration of `clone` work on the previous copy. I'll create a PR.

**Comment by rogerl50** [comment]
I tested this with a single copy where there were no capital letters. I failed to realize that multiple copies worked differently :(
