### ISSUE TITLE
Property for hands that display the back of card for other users

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#1329]
player can see the back of other players cards but cannot interact with them.

basically would be used in situations where number of cards is important and the room has space for individual hands

**Comment by robartsd** [comment]
Most online games I've seen (including PCIO) use a label associated with the seat to indicate the number of cards in the hand which is sufficient if the game only requires that players know the size of other players hands.

However there are games where this feature could be meaningful:
- games that allow players to take a card from another player's hand
- games that have different types of cards that may be held in a hand (of course the game designer could add a count for each card type to the seat)

**Comment by 96LawDawg** [comment]
Closed by #1654
