### ISSUE TITLE
Adding w and h as optional substitutes to every width and height property

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#135]
I really just want to lazy and type "w":100,"h":200

In case of conflict width and height would be the ones used

**Comment by robartsd** [comment]
Might as well add "r" as an alias for rotation as well if we do this.

**Comment by RaphaelAlvez** [comment]
In the meeting it was decided not to include aliases but it was accepted to include improvements and shortcuts in the json editor.

@larkob you said you could work on this. If you feel like including everything is to much for you, please include the following properties:

- "width":
- "height":
- "rotation":
- "cardsDefaults":[

]
- "movable":
- "movableInEdit":

The last 3 suggestions should be a good example for anyone who wants to expand this later. cardsDefaults has [ ] with it and movable needs two options.
