### ISSUE TITLE
deleting many widgets at once is slow

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#1351]
when you use the multiselect and then delete the selected widgets, it is waaay slower than deleting them one by one.

**Comment by ArnoldSmith86** [comment]
Can you provide an example? I tried to reproduce this by just adding a normal deck of cards and then deleting the cards by multi-selecting them using a regex but it was still very fast.

**Comment by Ingegneus** [comment]
try it in https://virtualtabletop.io/SmashUp
I think it might be the tree view again. it could be that the tree is rebuilt after every widget is deleted, even though it would be sufficient to generate the tree only after the last widget is deleted
