### ISSUE TITLE
Dragging widgets over overlapping drop targets often drops to target underneath

### ISSUE THREAD

**Issue by flackr** [ArnoldSmith86/virtualtabletop#1353]
I'm trying to setup a game where the player mat is a floating overlapping widget that can have tokens dropped onto it, but so can the board underneath. The problem is that often when dragging tokens onto the player mat they get dropped onto a target behind it (visually hidden by the player mat which has a higher layer / z value).

I think the problem might be that the move function in widget.js looks for the target with the nearest center without considering the z order:
https://github.com/ArnoldSmith86/virtualtabletop/blob/b4d57d21e924d3b73db20a4bb2b2f518d0c67e0a/client/js/widgets/widget.js#L1712

**Comment by flackr** [comment]
Confirmed that switching the shortest distance to center for highest effective zIndex (i.e. `parseInt(getComputedStyle(t.domElement).zIndex) || 0`) fixes my issue locally.

**Comment by 96LawDawg** [comment]
@robartsd is the expert on this kind of thing.  We had a few issues and PRs a while back that changed (and then reverted some of the changes) concerning which widgets would accept a drop.  We have never been able to drop on a target that is underneath another valid target.  The problem, I think (I am not smart enough on this to really know), with your proposal is that we don't really use z.  Z is just something that has to exist.  We use layer.

Is the layer of your player mat higher than the target behind it?  If so, I don't know that there is a good solution for that (other than creative use of dropTarget... Now that you can know which player is dragging which widget, you might be able to dynamically set dropTarget on the fly if that would work in your situation).

**Comment by flackr** [comment]
> @robartsd is the expert on this kind of thing. We had a few issues and PRs a while back that changed (and then reverted some of the changes) concerning which widgets would accept a drop. We have never been able to drop on a target that is underneath another valid target.

So it sounds like this should be working right? I.e. the player mat being above should always be the preferred drop target? I can try to put together a minimal repro.

> The problem, I think (I am not smart enough on this to really know), with your proposal is that we don't really use z. Z is just something that has to exist. We use layer.
> 
> Is the layer of your player mat higher than the target behind it?

Yep the board below is on a lower layer than the player mat.

> If so, I don't know that there is a good solution for that (other than creative use of dropTarget... Now that you can know which player is dragging which widget, you might be able to dynamically set dropTarget on the fly if that would work in your situation).

The problem is that I do want items to be movable from the player mat to the board or vice versa (i.e. you can move tokens both ways) so I can't just restrict which widgets accept the drop.

**Comment by 96LawDawg** [comment]
> So it sounds like this should be working right? I.e. the player mat being above should always be the preferred drop target? I can try to put together a minimal repro.

Yes.  But there are some calculations involved.  I don't remember the details, but if the target underneath is not the exact same size and shape, then the math the code uses to look for the "best/closest" target might make the lower target accept the drop sometimes.

A demo is always good.

**Comment by flackr** [comment]
I wasn't sure how to make an empty game so I modified one of the tutorials:
https://virtualtabletop.io/yefl

The white translucent box is the equivalent of a player mat that you can move items to/from the green "board". If you drop the object close to the center of the green (even when completely occluded by the white mat) it will fall through to the board underneath.

I put up a PR to fix this linked above.

**Comment by flackr** [comment]
> Yes. But there are some calculations involved. I don't remember the details, but if the target underneath is not the exact same size and shape, then the math the code uses to look for the "best/closest" target might make the lower target accept the drop sometimes.

Yeah those are the calculations I was referring to in the OP. When there are multiple possible drop targets it only selects for the one that the dragged item is closest to the center point of. This breaks the case of a floating player mat where you want the player to be able to put components on all parts of the player mat without having to worry about targets behind it.

**Comment by 96LawDawg** [comment]
> I wasn't sure how to make an empty game so I modified one of the tutorials: https://virtualtabletop.io/yefl
> 
> The white translucent box is the equivalent of a player mat that you can move items to/from the green "board". If you drop the object close to the center of the green (even when completely occluded by the white mat) it will fall through to the board underneath.
> 
> I put up a PR to fix this #1354

To make an empty game, the easiest way is just go to https://virtualtabletop.io and let it create a new room for you.  Then, just click the top left blue and white buttons (game library folder icon).  That will drop you into a blank room.  We are still working on user interface stuff.  Not many of us and it is slow going.

I tried fixing your issue just by using layer.  In your demo room, I added ` "cardDefaults": { "layer": 10},` to the deck.  I think that seems to work.

**Comment by 96LawDawg** [comment]
> > I wasn't sure how to make an empty game so I modified one of the tutorials: https://virtualtabletop.io/yefl
> > The white translucent box is the equivalent of a player mat that you can move items to/from the green "board". If you drop the object close to the center of the green (even when completely occluded by the white mat) it will fall through to the board underneath.
> > I put up a PR to fix this #1354
> 
> To make an empty game, the easiest way is just go to https://virtualtabletop.io and let it create a new room for you. Then, just click the top left blue and white buttons (game library folder icon). That will drop you into a blank room. We are still working on user interface stuff. Not many of us and it is slow going.
> 
> I tried fixing your issue just by using layer. In your demo room, I added ` "cardDefaults": { "layer": 10},` to the deck. I think that seems to work.

Nevermind.  It does not.  It just looks like it did, but when you drag the player mat around you can see they fell through to the main surface.
