### ISSUE TITLE
Hide dragged items while over hidden container.

### ISSUE THREAD

**Issue by flackr** [ArnoldSmith86/virtualtabletop#1356]
Consider https://virtualtabletop.io/vga5 where while seated player1 can move tokens around on their mat. They may want to arrange things that only they should have visibility of (i.e. `onlyVisibleForSeat` prevents other players from seeing them). I think it would make sense if by default as long as the tokens are over their hidden board, they are not be revealed to players not in that seat as once they are dropped they would also not be visible.

To reproduce, open the above game in two different browser instances (e.g. one incognito window). In one window, sit down in the player slot. Then, drag the token to move it around on that player's secret mat. The other player can see the item while dragged. Given that specific seated player only containers may be used to organize tiles I think they should not be revealed until they are dragged over a non-hidden container.

Here's a video of the current behavior:

https://user-images.githubusercontent.com/366761/195745687-2b9ba7b8-ec55-4690-838d-23fc0688c7d7.mp4

**Comment by flackr** [comment]
Arguably other players should also not know the cursor position while it is over a private widget, however this is less distracting / revealing than dragged items popping in and out.

**Comment by 96LawDawg** [comment]
> Consider https://virtualtabletop.io/vga5 where while seated player1 can move tokens around on their mat. They may want to arrange things that only they should have visibility of (i.e. `onlyVisibleForSeat` prevents other players from seeing them). I think it would make sense if by default as long as the tokens are over their hidden board, they are not be revealed to players not in that seat as once they are dropped they would also not be visible.
> 
> To reproduce, open the above game in two different browser instances (e.g. one incognito window). In one window, sit down in the player slot. Then, drag the token to move it around on that player's secret mat. The other player can see the item while dragged. Given that specific seated player only containers may be used to organize tiles I think they should not be revealed until they are dragged over a non-hidden container.

I don't think this is an "issue" that requires any change.  Just make the mat a "hand."  You do that by adding ` "childrenPerOwner": true`.  Then only the player that owns that mat can see the widgets until they are dragged outside of its borders.

**Comment by 96LawDawg** [comment]
> Arguably other players should also not know the cursor position while it is over a private widget, however this is less distracting / revealing than dragged items popping in and out.

We recently made some changes that modified the appearance of the cursor.  But we haven't undertaken the task to do that while it is over a hand.  That would be a fair amount of coding.  Of course it can be done and PCIO allows that.  Eventually we should make it an option, but it hasn't risen up the priority list yet.  See issue #249.

With my observation above and noting that your second comment is a duplicate issue, can we close this?

**Comment by flackr** [comment]
Ah nice! Yeah that works in the single ownership case but I'm guessing doesn't work if you have a holder that is `onlyVisibleForSeat: ['player1', 'player2']`

**Comment by 96LawDawg** [comment]
> Ah nice! Yeah that works in the single ownership case but I'm guessing doesn't work if you have a holder that is `onlyVisibleForSeat: ['player1', 'player2']`

Yes, that is true.  You *could* make it work by setting properties to the widgets so that if they come from the mat, they are only visible to players that own that mat until the widgets are dropped somewhere else.  I'll set a demo that shows that.  But I can see why you might want to make that an option in the code.  If you can make that happen, have at it.

**Comment by robartsd** [comment]
The only issue I see is that the idea might not work for every game design. Probably better to create a new property that triggers this behavior rather than assuming it should be applied as a side effect of hiding something from other players.

**Comment by 96LawDawg** [comment]
> The only issue I see is that the idea might not work for every game design. Probably better to create a new property that triggers this behavior rather than assuming it should be applied as a side effect of hiding something from other players.

I agree with that.  That is what I mean.  It would have to be a new property, or some modification or adjustment to "childrenPerOwner."

I do have a working demo in https://virtualtabletop.io/jg3f of how to get around this without a code change.  You need 3 browser views.  Changes are enter and leave routines to the 2 holders (they are NOT hands) and a draggingChangeRoutine in the deck's cardDefaults.  Could easily be tweaked for many situations.  I believe this solves @flackr's problem (at least through the JSON without rewriting the code).

**Comment by flackr** [comment]
I put together a PR and modified https://virtualtabletop.io/fnll to show the idea. I think this isn't quite right because it should probably inherit from ancestor holders as well if they have the property specified.
