### ISSUE TITLE
inheritChildZ doesn't detect children z changes

### ISSUE THREAD

**Issue by flackr** [ArnoldSmith86/virtualtabletop#1359]
While refactoring the way `z` is calculated I noticed what I think is a bug in the behavior of `inheritChildZ`. In particular, in widget.js applyZ() we look at this widget's `inheritChildZ` to decide whether the parent should update it's `z` value. See https://github.com/ArnoldSmith86/virtualtabletop/blob/b4d57d21e924d3b73db20a4bb2b2f518d0c67e0a/client/js/widgets/widget.js#L244

I put together a simple demo to show this. If you inspect the parent in dev tools you can see that when the children Z values change the parent does not:
https://virtualtabletop.io/inherit-child-z-bug

**Comment by ArnoldSmith86** [comment]
I'm pretty sure that `inheritChildZ` never actually sets `z` on the parent but just uses the highest `z` of its children.

**Comment by flackr** [comment]
The bug is this:
- If `inheritChildZ` is true, `calculateZ` will set a parent's `z` to the max of itself and any children. So anytime a child changes `z` the parent would need to know to match it.
- `applyZ` notifies the parent widget about Z changes if `inheritChildZ` *is set on the child* even though it it the parent's `inheritChildZ` that matters.

This patch fixes that but also adds a generic z change notiifcation which I use in the other PR to keep the correct set of pile cards visible.
