### ISSUE TITLE
Labels should not be selectable when “editable”: false

### ISSUE THREAD

**Issue by Casbuild** [ArnoldSmith86/virtualtabletop#137]
Labels that are not editable, should be part of the background and should not highlight when clicked and should not block dragging cards even if they are on a layer above the cards. Below shows an example of a highlighted Label after being clicked:

![image](https://user-images.githubusercontent.com/77217120/105170764-45772400-5ad2-11eb-901c-883380f23088.jpeg)

**Comment by ArnoldSmith86** [comment]
Duplicate of #20.
