### ISSUE TITLE
New properties for x,y coordinates of cursor

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1377]
There have been a couple of recent requests to be able to obtain the x,y coordinates of the cursor using routines.  The JSON Editor has some code for displaying the x,y coords.  Could that be recycled to make new properties like `_cursorX` and `_cursorY`?  I think these would be virtual or at least not `SET`table properties.

**Comment by robartsd** [comment]
Cursor coordinates should be made available as variables rather than properties if they are added.

I assume these would be room area coordinates of the cursor when the routine was triggered.
