### ISSUE TITLE
PROPERTY of $widgetID doesn't seem to work - returns null

### ISSUE THREAD

**Issue by flackr** [ArnoldSmith86/virtualtabletop#1378]
As described [here](https://github.com/ArnoldSmith86/virtualtabletop/wiki/Functions#code-for-the-color-selection-button-in-the-composed-widget) in the wiki, you should be able to get a property of a named widget by doing the following:

```
"var value = ${PROPERTY of $widgetID}"
```

However, when trying to use this in a `FOREACH`, value gets the value `null` even though the named `widgetID` has a non-null value for that property, see https://virtualtabletop.io/ug9t for a demo.

Code from demo:
```
    {
      "func": "SELECT",
      "property": "cloneAmount",
      "relation": "!=",
      "value": null,
      "collection": "DEFAULT"
    },
    {
      "func": "FOREACH",
      "collection": "DEFAULT",
      "loopRoutine": [
        "var amount = ${PROPERTY cloneAmount of $widgetID}",
        {
          "func": "CLONE",
          "count": "${amount}"
        }
      ]
    }
```

**Comment by 96LawDawg** [comment]
You used a lowercase "of" in the "var amount" line.  Must be "OF".  I fixed it in the room.

**Comment by flackr** [comment]
Oops, thanks so much for catching my rookie mistake there. The examples do indeed have OF capitalized as well.
