### ISSUE TITLE
editor beta server issue

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#1385]
I've tried the editor beta server out of curiosity and every time I open the json editor and move the mouse, the page reloads. It happens only when moving the mouse in the play area, not in the editor area

**Comment by ArnoldSmith86** [comment]
The beta server should be fixed in about an hour because I removed the "JSON editor" label from the PR that breaks it.

**Comment by ArnoldSmith86** [comment]
> The beta server should be fixed in about an hour because I removed the "JSON editor" label from the PR that breaks it.

Oops, apparently not because just removing a label doesn't trigger a server update. It'll update whenever any PR gets new commits or is merged.

**Comment by pounamu** [comment]
has this been fixed?

**Comment by 96LawDawg** [comment]
This works.  Must have been a temporary problem.
