### ISSUE TITLE
New predefined variables `seatIndex` and `seatID`

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1397]
Almost every game I make uses seats that uses substantial automation.  In that automation, I almost always need to know which seat the player activating the routine is in.  Right now, I do that through some short/uncomplicated code that checks the `playerName` against the `player` property in the seat and then gets the `index` property of the seat.  But I do that a lot.  I would love a new predefined variable that contains the index of the seat of the player.  If the player is not in a seat, then the value is null.

**Comment by flackr** [comment]
I do this as well! One challenge, the player can be in multiple seats.

**Comment by 96LawDawg** [comment]
I create a custom variable PID and then do exactly that.  I append it to a variable that applies something that only works for a particular player.

Here is an example:
```
"tuckedRoutine": [
    "var thisSeat = 'seat' + ${PROPERTY PID}",
    "var tuckedArray = ${PROPERTY tuckedBirds OF $thisSeat}",
    "var tuckedArray = remove ${PROPERTY position}",
    "var tuckedArray = insert ${COUNT} ${PROPERTY position}",
    {
      "func": "SET",
      "collection": [
        "seat${PROPERTY PID}"
      ],
      "property": "tuckedBirds",
      "value": "${tuckedArray}"
    }
  ]
```
In this case, I have pre-set PID on the widget because I know this one can only apply to this seat.  But in many cases it might apply to anybody and then I would have to determine the index using the process above.

**Comment by flackr** [comment]
In that example, the seat name, i.e. `thisSeat`, seems strictly better. You wouldn't need to append the index to a string and could just use the property directly. The seat name also isn't always seat[index]

**Comment by ArnoldSmith86** [comment]
Maybe add `seatIndex` and `seatID` as variables and `playerSeats` or something like that as a collection? The collection would contain all seats the player is sitting in.

**Comment by 96LawDawg** [comment]
> For my purposes, I would love to know the seat name, unless there's an easy way to get that from the index. In fact, given the name you can get the index easily. I often set the `onlyVisibleForSeat` to show some UI for just the activating player, but also allow other players to activate that UI on their screens as well if they want.

There is an easyish way to get both the seat name or the index.  But I just want to make it easier (at least for the index). 

> In that example, the seat name, i.e. your `thisSeat` variable, seems strictly better since you never use PID directly. You wouldn't need to append the index to a string and could just use the property directly. The seat name also isn't always seat[index].

True.  But I still need the index sometimes for other properties.  In the same room, I have some automation that uses names like birdTotal1, birdTotal2, etc.  I need the index for that.  I guess we need 2 new variables.

**Comment by ArnoldSmith86** [comment]
At some point the debug output might have to dim (or otherwise separate) pre-defined variables...

**Comment by 96LawDawg** [comment]
> At some point the debug output might have to dim (or otherwise separate) pre-defined variables...

And maybe not just the debug output, but the JSON editor itself could use a different color.

**Comment by flackr** [comment]
> Maybe add `seatIndex` and `seatID` as variables and `playerSeats` or something like that as a collection? The collection would contain all seats the player is sitting in.

What do `seatIndex` and `seatID` contain if the player is sitting in multiple seats? Would they be as if the player was sitting in no seats or choose one or an array?

**Comment by ArnoldSmith86** [comment]
> What do `seatIndex` and `seatID` contain if the player is sitting in multiple seats? Would they be as if the player was sitting in no seats or choose one or an array?

I would say just the first. Not very clean but most game devs probably assume that players are only in one seat.

**Comment by flackr** [comment]
Sounds reasonable. I could see a slight argument for the first one they sat in (assuming that they only jumped in the other seat to look at or help another player), but that's probably overthinking it.

**Comment by ArnoldSmith86** [comment]
The alternative would be to always make them arrays but at that point they're probably harder to use then retrieving the info manually.

**Comment by ArnoldSmith86** [comment]
> Sounds reasonable. I could see a slight argument for the first one they sat in (assuming that they only jumped in the other seat to look at or help another player), but that's probably overthinking it.

And we would have to keep track of that somewhere in the widget state.

**Comment by ArnoldSmith86** [comment]
The change would need to be made in `client/js/widgets/widget.js`. This block:

```Javascript
    if(!byReference) {
      variables = Object.assign({}, initialVariables, {
        playerName,
        playerColor,
        activePlayers,
        thisID : this.get('id')
      });
      collections = Object.assign({}, initialCollections, {
        thisButton : [this]
      });
    }
```

should be something like:

```Javascript
    if(!byReference) {
      const playerSeats = widgetFilter(w=>w.get('type')=='seat'&&w.get('player')==playerName));
      variables = Object.assign({}, initialVariables, {
        playerName,
        playerColor,
        activePlayers,
        seatIndex: playerSeats.length ? playerSeats[0].get('index') : null,
        seatID: playerSeats.length ? playerSeats[0].get('id') : null,
        thisID : this.get('id')
      });
      collections = Object.assign({}, initialCollections, {
        thisButton : [this],
        playerSeats
      });
    }
```
