### ISSUE TITLE
Set multiple properties from SET

### ISSUE THREAD

**Issue by flackr** [ArnoldSmith86/virtualtabletop#1404]
When you need to set multiple properties it can be quite verbose writing multiple calls to [SET](https://github.com/ArnoldSmith86/virtualtabletop/wiki/Functions#set). It would be nice to have a convenient way to set multiple properties in a single [SET](https://github.com/ArnoldSmith86/virtualtabletop/wiki/Functions#set) call.

If we don't want to diverge from the existing syntax we could use index-paired lists, e.g.
```
{
  "func": "SET",
  "property": ["x", "y", "parent", "owner"],
  "value": [100, 200, "container", "player"]
  }
}
```

One convention when one list is shorter than another in CSS is to auto-extend the last value. This could be useful for different relations, e.g.
```
{
  "func": "SET",
  "property": ["x", "y", "parent", "owner"],
  "relation": ["+", "+", "="],
  "value": [100, 200, "container", "player"]
  }
}
```

Where the "=" would auto-extend for everything after the first two indices.

**Comment by 96LawDawg** [comment]
Duplicate of #1168

**Comment by flackr** [comment]
We should close this right?

**Comment by 96LawDawg** [comment]
Yes, I just wanted to make sure your observations got added to the other one.  You did that, I see.  Thanks.
