### ISSUE TITLE
JSON editor fails to delete properties

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#1408]
I have this widget:

```JSON
{
  "type": "holder",
  "id": "B1",

  "x": 500,
  "y": 800,
  "width": 100,
  "height": 100,

  "movable": false,
  "movableInEdit": true,

  "classes": "transparent",
  "css": "background:#ccc",
  "dropOffsetX": 0,
  "dropOffsetY": 0,
  "inheritFrom": {
    "A1": [
      "width",
      "height",
      "borderRadius",
      "classes",
      "css",
      "dropOffsetX",
      "dropOffsetY",
      "dropTarget",
      "enterRoutine"
    ]
  }
}
```

I want to delete for example `"dropOffsetY": 0,` but opening the widget again shows that it's not deleted.

**Comment by rogerl50** [comment]
I just tried this and didn't see this behavior. See https://virtualtabletop.io/uumy.

**Comment by ArnoldSmith86** [comment]
Which property did you delete? At first glance they're all still there.

**Comment by rogerl50** [comment]
I put the `dropOffsetY` property back in after deleting it. But I just tried deleting it, and it went away. I restored it; give it a try. (Firefox, MacOS).

**Comment by ArnoldSmith86** [comment]
Can confirm. I also added the `A1` widget. Now it fails again for me.

**Comment by rogerl50** [comment]
It seems to fail only if A1 has `dropOffsetY` set.

**Comment by ArnoldSmith86** [comment]
The problem is that it inherits the same value as it has itself. And the recent change about minimizing the delta checks if the value changed (but it didn't).

**Comment by rogerl50** [comment]
Which PR was that?

**Comment by ArnoldSmith86** [comment]
Should have been part of #1314.
