### ISSUE TITLE
Button click causes room to misbehave, even after reload

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#141]
In the attached vtt file, there is a button labeled "Recall all chips" (lower left). If that button is clicked, the room stops working - nothing can be dragged any more. (To see this, click one of the Buy buttons first; you can move the chips around. But once you click that button, you can no longer move the chips out of their holders). What is more, if you "Remove" and reload from the vtt, the room still does not behave properly (again, try to click the same Buy button after this).

The last two entries in the `clickRoutine` for that button are a `SELECT` and a `CLICK`; if those two are removed, everything works fine.

So my assumption is that I did something wrong in the `SELECT`/`CLICK`, but I can't figure out what. I'd like to know that, but more importantly, the fact that it seems to take the room down seems to me to indicate some kind of leak. Oh, and setting `DEBUG` in the Recall button is useless, because something bad happens before the debug code is displayed, and I never see it.

I've left a room at https://virtualtabletop.io/3qkv that was loaded from that vtt file.

[poker_7_player(1).zip](https://github.com/ArnoldSmith86/virtualtabletop/files/5853478/poker_7_player.1.zip)

**Comment by robartsd** [comment]
Are you aware that the click is clicking each player's buy button as well as the potValueButton? You've used `mode` on all your other `SELECT`s but you didn't use it on the last one. `mode` currently defaults to `add` (planned to change to default to `set` soon).

**Comment by robartsd** [comment]
After adding `"mode":"add"` it seems to be working. It does take a long time to update after the button is clicked. There may be an actual issue with the virtualtabletop project related to clicking the labels in a click routine.

**Comment by rogerl50** [comment]
Thanks. I can't count the number of times I've made that mistake. (you meant add "mode": "set", BTW).

Also, the reason it takes a long time to update, even without that last click, is that the `RECALL`, which is recalling 900 cards, must be issuing a recall for each one even if it is already where it needs to be.
