### ISSUE TITLE
Collection named 'all' will not work in TURN

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#1416]
Note that the `TURN` code first tests for `"source": "all"`, and if true, it uses all the seats, even if there is a collection with that name. I guess that just needs to be documented in the wiki, since it's clearly too late to change it.

**Comment by 96LawDawg** [comment]
Tested and I agree that is an issue.  I updated the wiki and fixed an error.  It originally said that all seats at the table would be considered when setting turn, but it is actually only all occupied seats.
