### ISSUE TITLE
Using default value for `LABEL` inc/dec does not work

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#1418]
The default value is always zero, so
```JSON
    {
      "func": "LABEL",
      "mode": "inc",
      "collection": ["fllx"]
    }
```
will increment `fllx` by zero. The documentation claims that the default is 1 for inc/dec. (I'm not even sure how to make this happen, though.)

**Comment by 96LawDawg** [comment]
I changed the wiki to reflect the reality that default is.  But then this isn't really an issue any more unless you are suggesting that we change the default?  I don't think that is necessary.  I mean 1 makes sense, but not worth the trouble of changing.

**Comment by rogerl50** [comment]
> I changed the wiki to reflect the reality that default is. But then this isn't really an issue any more unless you are suggesting that we change the default? I don't think that is necessary. I mean 1 makes sense, but not worth the trouble of changing.

I mentioned it mostly because I'm proposing a similar thing for `SCORE`. Not sure how to implement it.
