### ISSUE TITLE
Changes to MOVE all

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#1454]
This may even be impossible to make a file updater but I would like to add the following values to MOVE and some other functions

- 0: actual 0 cards
- "all": all cards
- "half": half the cards in original holder
- "spilt": total/number of destination holders.

**Comment by ArnoldSmith86** [comment]
I don't see a big issue with a file updater.

**Comment by RaphaelAlvez** [comment]
> I don't see a big issue with a file updater.

I'm mostly afraid to break complex automations as usual

**Comment by ArnoldSmith86** [comment]
Yes but we can see what the MOVE uses for `count` and replace it by the result of an `IF` that behaves the same as current MOVE behavior.

If it's not a variable, we can just replace the value.

Shouldn't be an issue.

**Comment by RaphaelAlvez** [comment]
> Yes but we can see what the MOVE uses for `count` and replace it by the result of an `IF` that behaves the same as current MOVE behavior.
> 
> If it's not a variable, we can just replace the value.
> 
> Shouldn't be an issue.
> 
> Most MOVEs probably use a fixed positive number that doesn't need any updating.

Hum alright that seems like a good solution. This change should make using variables more consistent.

Also let's agree that negative numbers should be equivalent to 0?
