### ISSUE TITLE
It would be nice it buttons has access to a 'this' object

### ISSUE THREAD

**Issue by shaunhillier** [ArnoldSmith86/virtualtabletop#146]
I find I am repeating code across buttons with the only difference being that each code needs a Select id statement, where I have to change the ID of each script to match the button.
It would be great if the 'click' operation had a thisID variable by default. (like PlayerName)
Or if the button object was the default container onload.

**Comment by shaunhillier** [comment]
Looking at the code I'm wondering if exposing every property of the widget to the variables object would be the easiest way to achieve this, then you could use id and I know a lot of my code starts by getting properties off the widget to use. Is it possible to give me minimal write access to create a branch for this?

**Comment by ArnoldSmith86** [comment]
You don't need write access for that. Just create a fork and then a pull request.

**Comment by shaunhillier** [comment]
Cool, will have a play.

**Comment by larkob** [comment]
@shaunhillier I just added a proposal for allowing access to properties in issue #158. One example would be 
```
{
"func": "COMPUTE",
"operation": "-",
"applyProperties" [
{
  "property": "myWidgetID.height",
  "parameter": "operand1"
},{
  "property": "myOtherWidgetID.height",
  "parameter": "operand2"
}
]
}
```
I'm not quite sure what you had in mind, but would the following approach with `this` instead of a specific widget ID work for your use cases?
```
{
"func": "COMPUTE",
"operation": "+",
"applyProperties" [
{
  "property": "this.height",
  "parameter": "operand1"
}
],
"operand1": 1
}
```
I'm using COMPUTE here for the examples, but `applyProperties` would be useable in any operation. I was going to try coding this today, so let me know if we're talking about the same or different features.

**Comment by RaphaelAlvez** [comment]
Yeah that's a good suggestion. Would be an intuitive way to avoid some select + get soutines

**Comment by shaunhillier** [comment]
applyProperty is a great idea. My main 'ask' was that a widget know its own id (other properties were a bonus) Then you can duplicate a widget change some properties and not have to touch code. But if you could get the above to work with 'this' that would be great.

**Comment by shaunhillier** [comment]
So if you get your code to work and it automatically replaces "this" with this.p('id') (or whatever) then we are in business

My simple solution was just going to be to add  "widgetID" to the default variables object. Then each button would still need a load of gets to get the properties, but at least they would all have same code.

const variables = {
      playerName,
      playerColor,
      "widgetID" : this.p('id')
    };

**Comment by larkob** [comment]
Ok, let me try and see what I can do. You might not need that many GETs once the applyProperties works, as it would allow to map properties to parameters within any operation. So, the main use case for GET would be to store a property as a variable, otherwise you'd just apply properties as needed.

**Comment by robartsd** [comment]
I think @larkob proposal would be very useful in many circumstances, but I'd still be in favor of adding a variable containing the button's ID to the default variables list and/or a default collection that contains just the button.

**Comment by shaunhillier** [comment]
Shall we make that this enchantment then, change the default collection to be the button itself and add the widgetID variable to Variables. I've done the second bit in a fork already but couldn't quite work out the collections.
And leave @larkob to do his clever bit in #158

**Comment by rogerl50** [comment]
I'm in favor of doing both of these as well. But if you change the default collection to be the button itself, you might want to wait to submit this until after #83 is merged, since right now any `SELECT`s that are the first select in a given `clickRoutine` will change their behavior unless they currently explicitly specify `"mode": "set"`.

**Comment by robartsd** [comment]
> Shall we make that this enchantment then, change the default collection to be the button itself and add the widgetID variable to Variables. I've done the second bit in a fork already but couldn't quite work out the collections.
> And leave @larkob to do his clever bit in #158

Don't set `DEFAULT` to the button (leave it empty), but providing `thisButton` as a collection and/or `thisButtonID` as a variable would be nice.

**Comment by shaunhillier** [comment]
Ok I have created a pull request for this, #175
