### ISSUE TITLE
grid should have option to limit widget to the grid

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#1460]
at the moment grid allows widgets to be taken of the grid area manually

for tokens, board components and other situations we might want to just allow the widget to be in an area

I propose we add a "locked" property that will force the widget to be in the grid if moved manually

**Comment by 96LawDawg** [comment]
Or maybe another way of thinking about this is something that applies to all widgets.

xMinLimit
yMinLimit
xMaxLimit
yMaxLimit

Those define the boundaries outside which the widget is not allowed to go, grid or not.  They all default to null of course.  There have been a number of instances of changeRoutines being used to do the same thing.  This would greatly simplify that and would allow it to work on the room level or the parent level.
