### ISSUE TITLE
deck editor turns white on card upload

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#1463]
sometimes after I upload an image in a deck the overlay turns white and I can't press "update widget", but only exit via esc key. reopening the deck in the editor doesnt change the overlay. after I reload the site the deck widget displays a number >0 of cards in it, even though opening the overlay or the json editor reveals that there are none. 
![image](https://user-images.githubusercontent.com/78076361/209479011-e69a5023-459f-457c-ad27-884b879e610c.png)
I tried uploading 1 card and ~20 cards, but the result is the same. idk what exactly triggers this, but for me I can do it repeatedly in this room: https://virtualtabletop.io/4xmm its in the white holder 

edit: I think this is related to inheritFrom. the deck inherits 2 properties from another deck:
```
"inheritFrom": {
    "districtCardsDeckHolder": [
      "faceTemplates",
      "cardDefaults"
    ]
  }
```
but the fact that it should inherit only 2 properties doesn't seem to ensure that the other properties are applied correctly

**Comment by 96LawDawg** [comment]
No longer relevant in new UI.
