### ISSUE TITLE
assets not correctly saved in PL folder

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#1479]
I just tried to update shape sorter using the "update from active game" button.

since the assets were loaded in my server the game did not put the assets in the PL folder

![image](https://user-images.githubusercontent.com/73476656/210136556-be998de4-81a5-447f-8e49-b2ef31471e78.png)

**Comment by ArnoldSmith86** [comment]
File, please..

**Comment by RaphaelAlvez** [comment]
> File, please..

this is closed for a reason 🤦‍♂️

it was assets that I did remove but some but 2 ID's were started the same and I got confused
