### ISSUE TITLE
Add widget and edit mode is not available on mobile

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#1507]
New UI removed it.

Today I couldn't review 2 PRs because of it. Not a major problem IMO.

**Comment by 96LawDawg** [comment]
I just noticed that as well.  On my iPad, in portrait mode, I can't see edit mode.  In landscape mode, I can.

**Comment by RaphaelAlvez** [comment]
> I just noticed that as well.  On my iPad, in portrait mode, I can't see edit mode.  In landscape mode, I can.

On my phone I can't even in landscape mode.

**Comment by RaphaelAlvez** [comment]
I figured out that you can see edit mode if you change you browser to desktop mode

**Comment by 96LawDawg** [comment]
No longer an issue after #1482/
