### ISSUE TITLE
new UI: sort by similar to change

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#1509]
I think, if a game has no similar to entry, then the name should be used for the sort.

**Comment by ArnoldSmith86** [comment]
That's what it did. Doesn't work?

**Comment by Ingegneus** [comment]
no unfortunately

**Comment by ArnoldSmith86** [comment]
Seems to work when I look at Chess in the public library. Have an example where it doesn't?

**Comment by Ingegneus** [comment]
oh I should have been clearer. what I mean ist that non PL games should be sorted as I described

**Comment by Ingegneus** [comment]
oh I should have been clearer. what I mean ist that non PL games should be sorted as I described

**Comment by 96LawDawg** [comment]
Closing.  Non PL games are sorted as requested (by similar name if there is one and by the game name otherwise).
