### ISSUE TITLE
Proper dice

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#151]
We don't have a real solution yet for simple dice with images. The BasicWidget can do it in theory but it has the same problem that spinners had in the beginning: if you roll the same die face twice in a row, you don't know if you missed your click.

My proposal would be to amend `faceCycle: random` so that it doesn't switch to a random face immediately but instead first "rolls" through a few other ones so that it's clear that something happened.

Another solution would be to add a proper widget type for dice but since `faceCycle: random` was meant for exactly that, I think we should update it. As it is now it's not really that useful.

A third solution would be to add image support to spinners but I feel like the images would be too small.

**Comment by robartsd** [comment]
I think your change to `faceCycle: random` sounds like the best immediate solution, but I would also like to see image support added to spinners eventually. I don't think we need a new widget type for dice.

**Comment by larkob** [comment]
I'm not a fan of BasicWidgets and would favor the use of Cards for dice. I agree that they can actually do everything we need for dice rolling, except for some nice animation for when there's a random flip. 

Once we've got the Deck Editor, we could offer a "standard deck of dice" like we do for playing cards, which would make it quite simple for game designers to pick which dice to use and to modify them as needed. You may wonder why dice would need a deck, but when you think of games that use lots of different dice, such decks make absolute sense.

**Comment by ArnoldSmith86** [comment]
Well, I would want `faceCycle: random` to be consistent between BasicWidget and Card. So that would make both of them work.

I would have just added one or two examples to the "add widget" overlay but I don't really care.

**Comment by RaphaelAlvez** [comment]
It should be faceCycle: dice. Random can still have some uses with automation.

**Comment by robartsd** [comment]
> It should be faceCycle: dice. Random can still have some uses with automation.

I do like the idea of a new faceCycle value being used for this. Not sure the value should be "dice".

**Comment by robartsd** [comment]
I recently visited tabletopia.com (and was reminded that 3d tabletop simulators demand more graphics horsepower than many in my group usually have available which is why I found PICO in the first place), they animate decks when shuffling (non-uniform scaling in 3 dimensions). I could see using a non-uniforn 2D scaling animation on virtualtabletop to indicate something chnaging to a random state.

Something like:
```
@keyframes shuffle {
  0% {scale: 1 1}
  25% {scale: 1.2 .8}
  50% {scale: .8 1.2}
  75% {scale: 1.2 .8}
  100% {scale: 1 1}
}

.shuffling {
  animation-name: shuffle;
  animation-duration: .5s
}
```
Note: css scale property only works in Firefox currently, all other browsers can only scale in the transform property. Potential for css animations is a big reason I wish positioning was set with top and left instead of translate(x,y).

**Comment by robartsd** [comment]
Good solution came together on Discord today. Interitus suggested rotation to indicate that the click happened. He used dice with shading applied so 90 degree rotation would be noticeable. I put the dice into a widget with a transparent button over them, then I realized there's no reason the angle needs to be 90 degrees and added random rotation (not too close to 90 degrees). Interitus, LawDawg, and I each made original dice images that will be added as assets in the public library.

**Comment by larkob** [comment]
I've created a detailed requirements analysis for dice in the wiki (see https://github.com/ArnoldSmith86/virtualtabletop/wiki/Dice,-Dice-Cups-and-Bags), which should help us with further discussion of "proper dice". I'm not so familiar with the specific functional details of BasicWidgets, which is why I haven't populated that column. Feel free to add missing information.

Note that requirements are written from a "button-less" perspective. My sincere hope is that "proper dice" can eventually meet most (if not all) of the listed requirements. This does not imply that I have anything against using buttons for rolling dice. I simply want to see how far we can get "proper dice" to work on their own.

Also, as you can see, there are quite a lot of requirements. One of the reasons I've created the list is so that we could focus our discussion on specific aspects (e.g. each issue dedicated to one requirement), while still seeing the "bigger picture". For instance, the discussion here seems to be focused on requirement 10, i.e. making sure that players can recognize when dice are being flipped/rolled, for which an animation would be a suitable solution.

**Comment by RaphaelAlvez** [comment]
Really like your analysis as it goes beyond our initials discussions. I added information for basic widgets.

I do think that the other widgets you proposed should not be their own type but constructed widgets like the counter

**Comment by larkob** [comment]
I didn't mean to suggest any specific implementation for Cups and Bags, just wanted to list their requirements. I actually don't think they are specific to dice, because there's plenty of games with token bags that contain no dice. Never seen a "cup" for anything but dice, but who knows... Nevertheless, I felt it'd helpful to complete the "big picture" view for dice with cups and bags.

**Comment by robartsd** [comment]
Not sure how to interpret requirement 10 & 11. Do you simply mean the game designer should be able to specify if the die participates in piles or not? The pile rework will enable this for all widgets, so I've changed noes to upcoming.

**Comment by robartsd** [comment]
Basic Widget faces can set the widget's value property on face change. Updated requirement 3 to yes.

**Comment by larkob** [comment]
> 
> 
> Not sure how to interpret requirement 10 & 11. Do you simply mean the game designer should be able to specify if the die participates in piles or not? The pile rework will enable this for all widgets, so I've changed noes to upcoming.

Yes, in some games, dice are meant to allow stacking dice on top of each other, forming a pile (e.g. https://boardgamegeek.com/boardgame/39088/hoppladi-hopplada). In other games, this is undesirable.

**Comment by robartsd** [comment]
Cups and Bags would be varieties of holders. A new holder property `hideContents` property and implementing `onLeave` routines would allow them to be created.

**Comment by RaphaelAlvez** [comment]
Before implementing this can someone try to add a "faceCycle":"dice" that rotates through some faces quickly and then stop at a random one?

**Comment by larkob** [comment]
You're suggesting a face-flip animation, right? We would not actually flip through faces as that would cause irrelevant game state updates and lead to issues with concurrent user interaction. While a face-flip animation is doable, it's quite a bit of effort, in particular when there could be any amount of faces and each face having their own properties.

**Comment by RaphaelAlvez** [comment]
Yeah sure not really a flip. I was expecting and animation. I'm still not happy with awesome solutions that people created. I still fell that I lacks something more visual

**Comment by robartsd** [comment]
Animations would be a great UI enhancement. I'd like animations for both face change and pile shuffle. I still think that if we implement a new faceCycle value for this I'd prefer "roll" over "dice"; I'd also be OK with just animating "random".

**Comment by bjalder26** [comment]
It occurred to me today that an animated gif that doesn't repeat and becomes clear could look like a dice roll, then leave the actual/random roll visible underneath it when it becomes transparent.

**Comment by robartsd** [comment]
> It occurred to me today that an animated gif that doesn't repeat and becomes clear could look like a dice roll, then leave the actual/random roll visible underneath it when it becomes transparent.

Yes, but you'd still have to have a way to trigger the animation. I personally think that our solutions that add movement or rotation to make it obvious that there has been a change is a good enough solution to mark this as solved now that clickRoutine is available for every widget.

**Comment by larkob** [comment]
I still want to have proper dice. I just want to wait for the pile rewrite, so I can decide when the dice should stack and when they shouldn't.

**Comment by bjalder26** [comment]
> Yes, but you'd still have to have a way to trigger the animation. 
Yes, I see that now.  Even if cloned, it would not "restart".

**Comment by bjalder26** [comment]
Maybe at some point we could implement something like this (I know it doesn't have any images right now), but set a higher min/max rotation, and give it translational motion based on the width of the sizes and how much it spins in each direction.
https://jsfiddle.net/bjalder26/1dyembvw/11/

**Comment by 96LawDawg** [comment]
That looks cool and I like the effect.  Don't know about you, but all I see is a white cube.  No pips.

**Comment by bjalder26** [comment]
> That looks cool and I like the effect. Don't know about you, but all I see is a white cube. No pips.

Okay, you shamed me into putting in a tiny extra work.

**Comment by RaphaelAlvez** [comment]
I would also like to see more turns per roll

**Comment by RaphaelAlvez** [comment]
also, the faces should be customizable.
I don't mind only having d6 but IF the code is expandable have all classic dices would be nice

**Comment by robartsd** [comment]
This is using 3D css transformations in an animation. Not sure if our 2d use of z-index messes with that, but our use of transform for positioning could be problematic.

I think keyframes could be added to the animation to force it through more turns per roll. As it is I'm not sure it solves the problem of visually indicating a roll that happens to end up on the same face that it started on.

It would be quite a bit of work to expand this to a shape other than a cube.

**Comment by bjalder26** [comment]
> This is using 3D css transformations in an animation. Not sure if our 2d use of z-index messes with that, but our use of transform for positioning could be problematic.
> 
> I think keyframes could be added to the animation to force it through more turns per roll. As it is I'm not sure it solves the problem of visually indicating a roll that happens to end up on the same face that it started on.
> 
> It would be quite a bit of work to expand this to a shape other than a cube.

I suspect the z-index won't be a problem.  To me it seems like our use of transform is pretty much the same, however, I could be wrong.  Now that I think about it rotating much past 360 degrees might be a problem.  I think the CSS snaps back after about 390, but maybe 360 could be reset to zero several times in the JS.  I think it already has a 360 spin when the same number comes up.

I am not sure about other shapes.  I suspect making the shape would be easy enough, but I don't know if they would rotate correctly.
