### ISSUE TITLE
Proper game pieces (colored SVGs)

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#152]
I don't think it's possible right now to make an SVG (for example a city for Catan) that can inherit the widget's `color` attribute.

My best idea so far is to add a property to BasicWidget that makes it download its `image` asset, replace a pre-defined color (pink?) in its XML (SVG) code and then set the result as a data-URL asset to the widget.

**Comment by robartsd** [comment]
The simplest solution would be to embed the SVG directly into the room's DOM where the SVG could make use of "currentColor". Not sure if we want accept security risks of adding user provided markup directly to the room's DOM though, so keeping the SVG as a separate document using a data-URI might be more appropriate. The color to replace in the SVG should be "currentColor".

[https://stackoverflow.com/questions/13000682/how-do-i-have-an-svg-image-inherit-colors-from-the-html-document](url)

I'd want similar SVG colorization support for card image layers. I'd also be in favor of supporting data-URI images in general (as you may recall I made use of data-URI svg images to make rotated text on PCIO, before PCIO stopped supporting data-URI).

**Comment by RaphaelAlvez** [comment]
this would be also useful for recoloring default spinners

**Comment by robartsd** [comment]
How do we feel about providing a solution for library assets only (not user submitted content)? If we control what content the feature works with, we can safely inject the SVG elements into the DOM. If we use a new property to load these assets to a widget, we can even take advantage of SVG defs for cases where the same resource is used in multiple places on the page. Data URI has the disadvantage that each instance becomes its own thing.

**Comment by RaphaelAlvez** [comment]
Can you explain why this wouldn't be possible with a generic svg?

**Comment by robartsd** [comment]
> Can you explain why this wouldn't be possible with a generic svg?

I'm talking about making the SVG part of the DOM of the room itself. That is the only way CSS can set the color property that it inherits. I can see security reasons to be cautious with that. We can easily mitigate security concerns if we only use pre-screened content here.

**Comment by ArnoldSmith86** [comment]
> How do we feel about providing a solution for library assets only (not user submitted content)?

I don't like that. Sooo many games have custom game pieces and this would be the best solution for them IMO.

I would just replace a color in the SVG source and add it as a data URL.

And I'm pretty sure that data URLs work. If they don't, please open an issue for that.

**Comment by robartsd** [comment]
Here's a demo room for this: https://virtualtabletop.io/ColorizeSVG
