### ISSUE TITLE
Properties are not replaced in css selectors.

### ISSUE THREAD

**Issue by flackr** [ArnoldSmith86/virtualtabletop#1545]
Based on a discussion on discord, there was an attempt to style a widget based on a parent class. In theory the following should work:

```
  "css": {
    "_,body.edit #w_${PROPERTY id}": {
      "background": "red"
    }
  }
```

However, it doesn't, because the `${PROPERTY id}` isn't substituted with its value. This is simply a missing call to `cssReplaceProperties` here:
https://github.com/ArnoldSmith86/virtualtabletop/blob/main/client/js/widgets/widget.js#L483

**Comment by robartsd** [comment]
Not quite that simple if the widget id uses any characters that use escape sequence. I can't see a good reason to use any property other than the ID. I've thought about adding direct support for targeting the widget which would handle properly escaping the id.

**Comment by flackr** [comment]
Yeah that's fair. I could try to imagine other things but realistically you just want to select the widget itself. In this case it's mostly just a question of what the reserved magic string should be to generate the id selector for the widget itself. Maybe it should still be `${PROPERTY id}` but just have special conversion in this context to the element id rather than the literal id?

**Comment by ArnoldSmith86** [comment]
Maybe `, body.edit ${THIS}` or something? But I agree that an escaped ID would be more useful than being able to use everything. If we only provide one variable with the entire selector, it'll probably be easier to change later on in case we want to.

**Comment by robartsd** [comment]
When I change the DOM structure (see PR #984 ) we will want to be able to address both the container div (the DOM ancestor of any child widgets) and the presentation element (DOM sibling to any child widget container div).

**Comment by flackr** [comment]
@robartsd any suggestions? I'm happy to implement replacements for one or both. I feel like if we were to implement something now we'd probably want it to apply to the presentation element later right?

Also note that I want to add a separate hit testing element but I don't know that there should be any reason to directly style that - it would just be a clip-path element for the puposes of receiving events.

**Comment by robartsd** [comment]
I think `${THIS}` referring to the widget by ID makes sense. We can add something for the widget's outer div later.

A separate hit testing element is an interesting idea (though I can't think of a use case that requires it).

**Comment by flackr** [comment]
> I think `${THIS}` referring to the widget by ID makes sense. We can add something for the widget's outer div later.

Done

> A separate hit testing element is an interesting idea (though I can't think of a use case that requires it).

I have several games where I want to make irregularly shaped holders which can contain pieces but still allow them to hang over the edges.

The other use case would be if you have a graphic which is larger than the hit area (e.g. maybe has a glow or shadow as part of the graphic).

The way this works technically is you make the widget element itself `pointer-events: none` and a descendant `pointer-events: auto` and treat hits on the descendant as hitting the holder in the widget targeting code. This will of course be a separate issue / PR.

**Comment by robartsd** [comment]
> I have several games where I want to make irregularly shaped holders which can contain pieces but still allow them to hang over the edges.

PR #984 solves this use case (and is otherwise required by this use case) without an additional DOM element. The holder can have a clip-path and accept pointer events while the child widgets are outside the clip path.

For other use cases, I think a css pseudo element should be sufficient. I believe the engine already handles the bubbling up of mouse events through the DOM tree to identify the widget rather than the DOM child that received the pointer event.

**Comment by flackr** [comment]
> PR #984 solves this use case (and is otherwise required by this use case) without an additional DOM element. The holder can have a clip-path and accept pointer events while the child widgets are outside the clip path.

I filed #1572 since this is really unrelated to the current issue.
