### ISSUE TITLE
Inconsistent blurring of widget using "enlarge" and "scale"

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#156]
Recently, casbuild reported the tile distribution chart (.png)  in Wordy was blurry when hovering over it to enlarge using "enlarge."  I did not have the same problem and today, casbuild reported there was no problem for both .png and .svg versions of the widget.  We both used Chrome.

I also tried to make the file fullsize permanently on the screen.  I used the scale feature with an .svg file.  This time I got blurry results and casbuild did not.  But when I went back into the room just now, the file was not blurry.  Blurry samples attached.

<img width="595" alt="casbuild" src="https://user-images.githubusercontent.com/76912527/105784055-9907c880-5f3d-11eb-87b6-847e4292704a.png">
![LawDawg](https://user-images.githubusercontent.com/76912527/105784057-9ad18c00-5f3d-11eb-965a-a6722b85a25f.jpg)

**Comment by robartsd** [comment]
This sounds likely to be differences in browser rendering that may depend on hardware and software being used.

**Comment by 96LawDawg** [comment]
I haven't noticed this as a problem and as the likely cause is browser differences, this is no big deal.  Closed.
