### ISSUE TITLE
Rooms removing variations of games

### ISSUE THREAD

**Issue by Casbuild** [ArnoldSmith86/virtualtabletop#157]
Today myself and @96LawDawg LawDawg have been losing work with rooms resetting. For @96LawDawg LawDawg, they have just ben going to older save states of games. 

I have had bigger problems and have lost all the games in one of my rooms and have variations continuously deleting from others.

Before:
![Before](https://user-images.githubusercontent.com/77217120/105792954-20a10780-5f3d-11eb-85bc-2173ae7f55d1.png)

After:
![After](https://user-images.githubusercontent.com/77217120/105792993-331b4100-5f3d-11eb-8805-7fa6b4114bad.png)

**Comment by robartsd** [comment]
I have lost work due to disconnections without being aware of them for some time. I haven't noticed any problems where it wasn't just that the room went back to a previous state. Certainly could have a better system for checking that the current state is in sync with the server.

**Comment by ArnoldSmith86** [comment]
Please note that disconnections can only affect the current room - not anything in the games list. If you see your change in the games list, it went to the server and back.

**Comment by robartsd** [comment]
> Please note that disconnections can only affect the current room - not anything in the games list. If you see your change in the games list, it went to the server and back.

Come to think of it, I have noticed this - the inability to update the games list because I was disconnected.

**Comment by robartsd** [comment]
Just experienced this in one of my rooms.

I had an old version of Rummy Tiles loaded from the library in the room. I edited the room's Rummy Tiles game and tried adding a variant from the public library, selecting Rummy Tiles. All games were removed from the room.

**Comment by rogerl50** [comment]
I was just doing some coding in a room, and while I was just thinking, the room contents disappeared, replaced by the initial empty room screen.

**Comment by 96LawDawg** [comment]
This issue would no longer be possible based on the new UI.  Closed.
