### ISSUE TITLE
Broken card dragging

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#1582]
[cinnamon-2023-02-06T134412+0100.webm](https://user-images.githubusercontent.com/73538315/216974901-1b446910-c153-4d8d-bbd9-c5beaef68444.webm)

**Comment by robartsd** [comment]
Possibly related to #1550

**Comment by flackr** [comment]
Debugging pointed me to the specific issue. The top-left point being compared to (0, 0) was being rotated by the 180 degree rotation. Instead we should be comparing to the transform origin point and then offsetting by the transform origin.
