### ISSUE TITLE
Duplicating a widget should copy its children

### ISSUE THREAD

**Issue by UltimateGeek** [ArnoldSmith86/virtualtabletop#16]
```gherkin
Feature: Widget parenting / Copy widget
  As a game designer
  I want widgets' children to be duplicated along with the widget
  So that I don't have to manually do it myself

Scenario: Duplicate widget with children by default
  Given a widget that has children
  When I click to duplicate the widget
  Then the widget gets a unique ID
  And all of the original widget's children are duplicated
  And the new children get unique IDs
  And the new childrens' parent is set to the new widget's ID

Scenario: Duplicate widget without children when selected
  Given a widget that has children
  And I click to duplicate the widget
  And it prompts to confirm duplicating children
  When I select to not duplicate children
  Then only the single widget is duplicated
```

**Comment by RaphaelAlvez** [comment]
Duplicating cards mess up with decks.

Case 1: 
If you duplicate a holder with cards but deck is not in the holder.
Result: cards would be added in the deck

Case 2:
If you duplicate a holder that has a deck and cards.
It would duplicate the deck but the cards would still keep the old card type and would be included in the original deck

Now let's say we add the cards to the initial deck:

Case 3:
If you duplicate a holder that has a deck but not all cards are in the holder.
It create a deck with the incorrect amount of cards and possibly be a total mess. 

I think the simpler and more consistent solution would be to not include cards and piles

**Comment by rogerl50** [comment]
Should it be optional whether to duplicate all the owned widgets (except cards)? I don't know the answer, but it's worth thinking about before hand. I think that in most situations, a parent widget is a parent because it has some relation with its children, so it makes sense to duplicate them all.
