### ISSUE TITLE
Transition location error when widget changes properties

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1603]
In the PL game Spin 5, dragging one of the cards onto a holder when the holder has been rotated sometimes causes the card to appear to relocate from a strange location.

**Comment by robartsd** [comment]
I think this is related to the holder setting the rotation of the card during the transition.

**Comment by robartsd** [comment]
[Solution for Spin 5]( ttps://virtualtabletop.io/f3ly) applies the counter rotation to the holders on the board instead of the cards in the holder.

**Comment by 96LawDawg** [comment]
This isn't really about Spin 5.  It's a placeholder for @flackr to fix something that broke as a result of something else.

**Comment by 96LawDawg** [comment]
We were talking about it in our meeting.  I'll fix Spin 5, but thanks.
