### ISSUE TITLE
${PROPERTY something} doesn't work in handleCSS

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#1621]
what the title says. it would be nice for consistency and ease of use, to be able to do the same stuff you can do in the normal css

**Comment by 96LawDawg** [comment]
It would be a property of the pile, right?  Not of the cards that make up the pile?

**Comment by Ingegneus** [comment]
yes

**Comment by ArnoldSmith86** [comment]
You can use `css` to style `.handle` and there you can use properties. But yeah, some day...

**Comment by robartsd** [comment]
Duplicate of #1304 

Use the property in `css`.
```json
"css": {
  " .handle": {
    "styleName": "${PROPERTY something}"
  }
}
```
OR
```json
"css": "--something: ${PROPERTY something}",
"handleCSS": "styleName: var(--something)"
```

> But yeah, some day...
Maybe ... probabaly not.
