### ISSUE TITLE
dropShadow doesn't get correct position for rotated containers

### ISSUE THREAD

**Issue by flackr** [ArnoldSmith86/virtualtabletop#1640]
The calculation of the position for the drop shadow isn't the same as the one used when dropping the widget. This results in the drop shadow showing in a different location than it drops to. For example try the demo at:

https://virtualtabletop.io/clip-path-holder

You can see that in the rotated holders the position of the shadow is not the place it drops to as the `moveEnd` code does some extra repositioning to align the anchor point in the transformed container. This incorrect location could result in inconsistent orders in rotated aligned containers where while dragging it looks like you'll drop in one place and end up dropping in another.

**Comment by 96LawDawg** [comment]
All that time we spent playing with the drop shadow PR and none of us . . . NOT. ONE. OF. US. . . thought to try transformations!!  We should all be fired.  And then rehired back at our old pay rate because I don't see anybody else volunteering to take over.

**Comment by flackr** [comment]
😆 I only discovered it because I was trying to make another useful feature #1639 and added a drop shadow to make debugging easier (realtime feedback of drop location rather than only when dropped) only to find the drop shadow was wrong already.
