### ISSUE TITLE
Timers with CSS Broken on Edge

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1663]
I don't understand how this is possible (@flackr, I'm looking at you).  Timers with complicated CSS transitions are broken (on production).  Look at the Timer: Appearance tutorial (and the attached video).  The basic timer at the top of the screen works.  The bar, hourglass, and stopwatch do not.  Well, they sort of work, but get bogged down after a few seconds.  After a minute or so, they actually get going again and appear to work.  This is newish behavior.  They didn't use to be this way.  In fact, I'm 99.9% certain it was working correctly as recently as Feb 3 when I added Alphabet Soup to the dice PR.

Help?

https://user-images.githubusercontent.com/76912527/222326318-f7d84931-11b7-418f-aff7-182b58e1448d.mp4

**Comment by 96LawDawg** [comment]
Update:  this is only happening on Edge.  Usually Chrome and Edge do the same thing, but here is a difference.

**Comment by robartsd** [comment]
> Update: this is only happening on Edge. Usually Chrome and Edge do the same thing, but here is a difference.

That is interesting. I would see if you could determine the base Chromium version of each.

**Comment by 96LawDawg** [comment]
Now even Edge isn't a problem.  I haven't done anything different.  I haven't rebooted my computer since yesterday and many of the same tabs are open.  But it works again.  Issued closed.
