### ISSUE TITLE
Seat counter does not work with stackOffset 0

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#1670]
https://virtualtabletop.io/issue1670

after there is a pile it stops counting

**Comment by ArnoldSmith86** [comment]
Looks like `COUNT` doesn't work:

```JSON
    {
      "func": "COUNT",
      "holder": "${PROPERTY hand OF $parent}",
      "owner": "${PROPERTY player OF $parent}"
    }
```

https://virtualtabletop.io/xqou

**Comment by RaphaelAlvez** [comment]
> Looks like `COUNT` doesn't work:
> 
> ```json
>     {
>       "func": "COUNT",
>       "holder": "${PROPERTY hand OF $parent}",
>       "owner": "${PROPERTY player OF $parent}"
>     }
> ```
> 
> https://virtualtabletop.io/xqou

it does work if you drop a pile it does not work if you add cards one by one. probably a problem with the trigger

**Comment by ArnoldSmith86** [comment]
Hmm, that same code works if it is in a clickable button.

It _is_ called when the `owner` changes but something must be different.

**Comment by RaphaelAlvez** [comment]
https://user-images.githubusercontent.com/73476656/222852740-ab18109a-f0b7-4aca-89fd-d96692a3a6f7.mp4

super weird behavior....

**Comment by ArnoldSmith86** [comment]
My guess is that at the time of evaluation the new card is in the holder but not yet in the pile. And then `children` returns the pile and the new card (so two widgets).
