### ISSUE TITLE
Lost everything in my main room

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#169]
I wanted to get an empty board so I got the Unicode assets as a starting point. I then went into the metadata and erased everything. I guess the file was then totally empty and when I pressed play everything was erased. Even other games. 

I guess that not such a big problem in my case but that a big bug

![image](https://user-images.githubusercontent.com/73476656/106087191-4297b700-6102-11eb-87c7-fceb4594470f.png)

**Comment by 96LawDawg** [comment]
I was able to duplicate this same error following the steps that RaphaelAlvez did (although it took about 10-15 seconds for it to kick in).  Console shows the same basic results as what he got.

**Comment by ArnoldSmith86** [comment]
I will fix this but just so you know: If a variant has an "update link" set, it doesn't store its state in a file like normal states do. When removing the link, such a file is also not created but when you click play on that variant, it tries to read from that file.

The error is not caught in an appropriate place and leads to a complete room reset.

**Comment by robartsd** [comment]
> I will fix this but just so you know: If a variant has an "update link" set, it doesn't store its state in a file like normal states do. When removing the link, such a file is also not created but when you click play on that variant, it tries to read from that file.

So if you add a game from the public library, it includes an update link that pulls the public library version every time you choose to play a variant from your games list?

If you want to disconnect from public library updates, what is the recommended practice? Would loading the variant into the room then updating the variant from the current room state do the trick?

**Comment by ArnoldSmith86** [comment]
Probably not as long as there is an update link set. After #172 is merged just removing the update link would be the recommended way.

You can also download and re-upload the game.

**Comment by 96LawDawg** [comment]
Will PR #168 (rooms cleanup unused files on the server) cause a problem with this.  Scenario:  I have a private game not in the public library.  I put it in my room.  I share the update link with people.  Then I decide to remove it from my room.  Will the people still be able to access the game with the update link?

**Comment by ArnoldSmith86** [comment]
I don't know. Somebody test that... :D

**Comment by 96LawDawg** [comment]
> Will PR #168 (rooms cleanup unused files on the server) cause a problem with this. Scenario: I have a private game not in the public library. I put it in my room. I share the update link with people. Then I decide to remove it from my room. Will the people still be able to access the game with the update link?

Turns out that was a stupid question (yes, there are stupid questions).  You don't get update links with games that are not in the public library.  So if you want to share a non-library game with someone, you have to give them a room code with the game in it or a .vtt file.  Nevermind.

**Comment by ArnoldSmith86** [comment]
> You don't get update links with games that are not in the public library.

You should if you add the shared link of someone else to your room. And I'm not quite sure what happens when a shared game is deleted.

**Comment by 96LawDawg** [comment]
Okay, I'm an idiot.  Nothing new there.  When I looked at non-public library games, I forgot you have to click on the Share link button.  In a public library game, there is already a URL displayed.

To address the issue, when a shared game is deleted from the room, trying to use that hyperlink gives "502 Bad Gateway" and the .vtt file is no longer available for download.  That is the behavior right now.  I don't think that should change.
