### ISSUE TITLE
`SCORE` with property null deletes seat

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1697]
I have no idea how this could happen, but if you use the `SCORE` function and set the "property" parameter to null, it deletes the seats specified in the "seats" parameter.

**Comment by rogerl50** [comment]
The problem is that the `null` property is being passed through to `set`, which then tries to set the null property of the state to some value. I don't know what happens after that, but it sure seems like the answer is to make sure the property parameter is non-null.
