### ISSUE TITLE
Auto-generated IDs for new widgets can be based off the original

### ISSUE THREAD

**Issue by UltimateGeek** [ArnoldSmith86/virtualtabletop#17]
```gherkin
Feature: Copy widget / ID generation
  As a game designer
  I want new widgets created by duplicating existing ones to have IDs based off of the original when possible
  So that I don't have to hand-modify each new duplicated widgets' IDs

Scenario Outline: Auto-increment number at end of ID
  Given a widget with ID <orig_id>
  And there is an existing widget with <other_id>
  When I duplicate the widget
  Then the new widget's ID is <new_id>
Examples:
  | orig_id | other_id | new_id  |
  | label_1 | label_0  | label_2 |
  | label-1 | label-2  | label-3 |
  | a3f45   | n/a      | <random>|
  | b_p9    | n/a      | b_p10   |
  ```

**Comment by robartsd** [comment]
Not clear on why duplicating a3f45 results in a random new id but duplicating b_p9 results in b_p10. 

I'd suggest that if we implement this feature, anything with a custom id (anything that is not 4 lowercase letters) create a incremental id by:
- adding a number (starting with 1 if available) if the id does not already end in digits
- incrementing the number if the id ends in digits (if the string of digits at the end of the id starts with zeros, format the incremented id leading zeros to match the number of digits)

**Comment by UltimateGeek** [comment]
The presence of a non-digit, not-Letter in the ID is what I was suggesting be the trigger. That way, true random IDs continue to work the same when duplicating.

**Comment by robartsd** [comment]
> The presence of a non-digit, not-Letter in the ID is what I was suggesting be the trigger. That way, true random IDs continue to work the same when duplicating.

To implement this we could check the id of the widget being duplicated to see if it matches `/^(.*\W\D*)(\d+)$/`. If it does, the first capture group becomes the base ID and the second capture group is incremented to the next available id. I still want support for padding with zeros.
