### ISSUE TITLE
ESC key when in fullscreen

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#173]
This is a little QOL issue: when editing a widget in fullscreen mode, pressing esc exits fullscreen instead of the editor. Same thing when using the debug function.

**Comment by ArnoldSmith86** [comment]
I don't think we can change that. I'm pretty sure the browser uses the ESC without ever telling the page about it.

**Comment by robartsd** [comment]
I think it depends partially on how one enters fullscreen. On Chrome, if I use the fullscreen button that VTT provides, ESC exits fullscreen, but I can enter fullscreen using the browser's menus and only F11 exits fullscreen (F11 toggles fullscreen regardless of how it was entered). I don't think we can change this browser behavior. If user's want to stay in fullscreen more easily, they can use their browser controls to enter fullscreen. I think we should provide a clear direct way to exit each overlay with a mouse/touch (close box or cancel button on every overlay).

**Comment by bjalder26** [comment]
I believe PR #519 addresses this.
