### ISSUE TITLE
Five of a Kind

### ISSUE THREAD

**Issue by robartsd** [ArnoldSmith86/virtualtabletop#1734]
Clicking an individual die rolls it independently.

**Comment by rogerl50** [comment]
Each die should be set to `clickable: false`. I'd do it myself, but I don't know how to submit games for approval these days. Another issue I noticed is that the game title is now displayed improperly in its text box; this is likely a side effect of some other PR.

**Comment by robartsd** [comment]
> Each die should be set to `clickable: false`. I'd do it myself, but I don't know how to submit games for approval these days. Another issue I noticed is that the game title is now displayed improperly in its text box; this is likely a side effect of some other PR.

Yeah, I think it was set in cardDefaults when the dice were created as cards.
