### ISSUE TITLE
Filter out cards subject to `RECALL`

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1749]
I have created several games now where I have had to come up with solutions to the problem of keeping certain cards out of play. For example, say you have a deck of 40 cards.  With 4 players you use all 40. With 3 players, you remove 5 specific cards from play. There are work arounds for making this work, but to me it seems like the simplest solution in the JSON would be to have a filter for those cards.  You still have to remove them initially by `SET`ting the parent somewhere else like on off-screen holder. But my solution would mean those cards are not recalled after that and then have the parent set somewhere else again.

It could look something like this:

```JSON
{
  "func": "RECALL",
  "holder": "${PROPERTY parent}",
  "filter": {
    "cardType": [
      "T 1J",
      "T 2J"   
    ],
    "suit": "C"
  }
}
```

Maybe my spacing and my brackets aren't exactly right. But the idea is that you specify any property on a card and an array or scalar value to say what cards will NOT be affected. So in the example above using the nomenclature of our standard deck, the jokers and the clubs would not be recalled.

Could also name the parameter `exclude`, or `limit` or whatever.

**Comment by robartsd** [comment]
In practice I would probably move cards to be excluded from play into an off screen holder and filter based on that parent (or _ancestor). Without changing RECALL, this is several steps: SELECT deck, SELECT not excluded, SET parent (possibly MOVE to another holder since SET parent does not trigger everything that MOVE triggers).
