### ISSUE TITLE
activeSeats  - requested predefined collection for routines

### ISSUE THREAD

**Issue by pounamu** [ArnoldSmith86/virtualtabletop#1773]
activeSeats - a collection consisting of all the seat id`s that any player is in

I would find this useful as a predefined collection

**Comment by 96LawDawg** [comment]
This already exists as `playerSeats`.  See https://github.com/ArnoldSmith86/virtualtabletop/wiki/Functions#predefined-variables

**Comment by ArnoldSmith86** [comment]
That's all seats the active player sits in. Not all seats _any_ player sits in.

Basically:

```JSON
{
  "func": "SELECT",
  "property": "player",
  "relation": "!=",
  "value": "",
  "type": "seat"
}
```

**Comment by 96LawDawg** [comment]
Good catch.  Question is, do we do this?  I'm not necessarily against it, but we already have a lot of predefined variables/collections with "seat" in their name.  So what would this be named?  `allActiveSeats`?  Also, this collection is easy to create using the routine above.  Most of the other variables/collections either take several steps to create or are not exposed at all to the designer without the variable.  Just some things to think about.

**Comment by ArnoldSmith86** [comment]
@pounamu, were you aware that it's "that easy" to retrieve the seats? Because I kind of agree that it's too short to add a shortcut for it.

**Comment by pounamu** [comment]
Ok.
