### ISSUE TITLE
Allow widgets to be configured to have a fixed parent

### ISSUE THREAD

**Issue by UltimateGeek** [ArnoldSmith86/virtualtabletop#18]
```gherkin
Feature: Fixed Widget parenting
  As a game designer
  I need to be in full control of parent-child relationships of widgets
  So that when the parent is moved in the editor GUI, all the children move with it
  And so that I can prevent accidental orphaning and new parent adoption.

Scenario: Fixed parent
  Given a widget has properties:
    | parent      | holder1 |
    | fixedParent | true    |
  When I move the child under a different holder
  Then the child stays parented to its fixed parent
```

**Comment by rogerl50** [comment]
This is a potential solution to issue #11, which I opened earlier today; the two should probably be merged. This describes a possible solution, while my post describes only the problem.

**Comment by RaphaelAlvez** [comment]
We added movableInEdit to solve that issue. Are you aware of that property?

in the wiki, it is described as: "If set to false, the widget will not be movable in edit mode.
This is sometimes useful for child widgets of more complex widget groups. For example buttons of counters."

As a game designer, I recommend locking all widgets that's shouldn't be moved by accident before publishing your game.
lock them using movableInEdit and movable

**Comment by UltimateGeek** [comment]
> We added movableInEdit to solve that issue. Are you aware of that property?
> 
> in the wiki, it is described as: "If set to false, the widget will not be movable in edit mode.
> This is sometimes useful for child widgets of more complex widget groups. For example buttons of counters."
> 
> As a game designer, I recommend locking all widgets that's shouldn't be moved by accident before publishing your game.
> lock them using movableInEdit and movable

I think this reply is related to #11 as this feature request is about preventing the parent of a widget from changing when moving it onto things that by default change its parent (a holder).
