### ISSUE TITLE
games should be able to specify and use any font from Google Fonts

### ISSUE THREAD

**Issue by robartsd** [ArnoldSmith86/virtualtabletop#181]
Provide a way for a game designer to list font names to load from [Google Fonts](https://fonts.google.com/).

In meeting today we decided that we want to support game designers specifying fonts they would like to use from Google Fonts. This issue is to discuss how this should be implemented.

**Comment by RaphaelAlvez** [comment]
This issue was approved in the meeting today

**Comment by robartsd** [comment]
We've added a variety of fonts and chosen to self-host fonts. Do we still want to allow game designers to add external font resources to games?

**Comment by robartsd** [comment]
@font-face rules can be added using the `}` hack in widget style sheets (and official support for css @rules is being considered).
