### ISSUE TITLE
There should be one font available for unicode and emoji so they look the same across platform.

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#182]
The suggested fonts were Noto Emoji and Not Color Emoji.
They should be ideally be used in addition to Roboto.

It was proposed to merge the 3 fonts in a font editor.

This issue was a proved in today's meeting

**Comment by robartsd** [comment]
Why not just use Noto Sans for regular text instead of Roboto?

Can't use Noto Color Emoji - only works on Linux and Android.
> This font format is supported on Android and Linux, but doesn’t work on macOS or Windows.
[https://www.google.com/get/noto/help/emoji/](url)

I don't see a reason not to use Noto Sans (or Roboto) and Noto Emoji as our standard font.

**Comment by robartsd** [comment]
I misunderstood the font fallback QA I found on stackoverflow during the meeting. Fallback does work at the glyph level. So there should be no need to make a custom font containing all glyphs we want. We can even limit the glyphs available in a google font if we want to use it for some of its glyphs but not others:
[https://css-tricks.com/css-basics-fallback-font-stacks-robust-web-typography/#h-individual-characters](url)

**Comment by mousewax** [comment]
Does the combination of Material Icons and VTT-Symbols satisfy this issue?

**Comment by RaphaelAlvez** [comment]
It does but it doesn't deal with this problem directly but it solves the problem this issue was trying to solve.
I wanted emojis for the PL.
