### ISSUE TITLE
allow more control over which cards can form a pile

### ISSUE THREAD

**Issue by larkob** [ArnoldSmith86/virtualtabletop#189]
Currently, all cards form a pile when placed in close proximity. Not all cards are equal, though, and as a game designer I'd sometimes like to prevent cards of different kinds to pile. A typical use case is when a games has small cards and large cards that should not stack together. Another use case is when I use cards to represent dice and don't want them to pile. And most importantly, when the game has cards with very different amount of faces (e.g. single-sided cards, two-sided cards and six-sided cards), they are rarely meant to form a pile with cards of different face-type.

My suggestion is to allow to define some kind of custom criteria to determine which cards can stack with other cards. A simple approach would be a boolean deck property which simply defines whether cards of this deck stack with any cards from other decks. A better approach would be to be use a property that defines which cards can pile, preferably per card rather than per deck (which would allow to change the property on entering/leaving a holder).

For implementation, we could support a "pilesWith" property for cards, which allows for an array of string values. When cards are moved in proximity, we compare the pilesWith values and if there's a match, the cards pile, otherwise they don't. The default value would be null and cards with null values would also be considered matches, to make this functionality fully compatible with the current logic.

**Comment by ArnoldSmith86** [comment]
That should already work in #147.

**Comment by 96LawDawg** [comment]
Closed by #646 and #905.
