### ISSUE TITLE
Data URL SVG that is not base64 encoded should work

### ISSUE THREAD

**Issue by robartsd** [ArnoldSmith86/virtualtabletop#191]
Since SVG is mostly a text based format the most efficient way to encode them in a data URI is to keep them as text and URL encode only the few characters that need it; see [Optimizing SVGs in data URIs](https://codepen.io/tigt/post/optimizing-svgs-in-data-uris) (note there is a link to a Node.js module at the end of the article).

I originally used these types of URLs on PICO in July 2020 to create rotated text. Here's an actual example from a deck imported in a PICO file that does not work:
`"svg": "data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 216'%3e%3ctext fill='%23fff' style='font: 900 16px sans-serif' text-anchor='end' transform='matrix(0 -1 1 0 18 5)'%3eClear%3c/text%3e%3c/svg%3e"`

But I also found that using data URI for rounded rectangle card layers made smaller PICO files (example from same deck):
`"value": "data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 142 216'%3e%3crect width='132' height='206' x='5' y='5' ry='9' fill='%23080'/%3e%3c/svg%3e"`

These data URL SVGs do not get loaded to the background-image property of the DOM elements by VTT (they do work if I set the background-image in a custom css property). These types of data URLs may be useful for #152 .

**Comment by robartsd** [comment]
Demo of using these types of data URL SVG to colorize an image: https://virtualtabletop.io/ColorizeSVG

**Comment by ArnoldSmith86** [comment]
That demo is really cool.

**Comment by ArnoldSmith86** [comment]
Putting the same SVG as `image` works fine for me in your demo room (see bottom right). Am I misunderstanding the problem?

**Comment by robartsd** [comment]
Perhaps it is only an issue on card layers then. I know I had a problem with this type of SVG on cards in Apples to Apples.

**Comment by ArnoldSmith86** [comment]
Ah, that's possible. Please check if it's fixed in #199 because I saw that it was missing quotes.

**Comment by robartsd** [comment]
> Ah, that's possible. Please check if it's fixed in #199 because I saw that it was missing quotes.

Yes, #199 fixes this.
