### ISSUE TITLE
Routines to create and delete widgets

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#193]
Create would be using the json just like adding a custom widget.
Delete would be all widgets in a collection

Use cases:

- Creating temporary widgets in general.
- Providing additional tokens.
- Creating UI pop ups (instead of having them hidden somewhere).
- In particular allows creating widgets and UIs only one user can see without the need of providing countless copies in the outside board.

**Comment by RaphaelAlvez** [comment]
putting some for some more time into this issue I came up with some format

```
{
"func": "CREATE";
"base": {
  "faces": [
    {
      "classes": "checkersPiece"
    },
    {
      "classes": "checkersPiece crowned"
    }
  ],
  "width": 73.5,
  "height": 73.5,
  "x": 50,
  "y": 50,
  "z": 2,
  "classes": "checkersPiece",
  "createdChecker": true (custom property for tracking back later)
},
"properties":{
  "color": playerColor (that's a preset variable)
  }
}
```

```
{
  "func": "SELECT",
  "property": "createdChecker",
  "relation": "==",
  "value": true,
  "collection": "myCollectionName",
},
{
"func": "DELETE";
"widgets": "myCollectionName"
}
```

```
{
  "func": "SELECT",
  "property": "createdChecker",
  "relation": "==",
  "value": true,
  "collection": "myCollectionName",
},
{
"func": "DUPLICATE";
"widgets": "myCollectionName",
"properties":{
  "duplicated": true
  },
xOffset: 50,
yOffset: 50
}
```

**Comment by larkob** [comment]
How about we start simple and just implement a basic CLONE and DELETE? The CLONE should "return" the newly created widget(s) as a collection so it can be used in consecutive operations (e.g. to change some properties). The DELETE simply needs a collection as input. Not sure if we should call that property "widgets" or rather "collection".
```
{
  "func": "SELECT",
  "property":"id",
  "value": "<widgetID>",
  "collection": "myCollection"
},
{
  "func": "CLONE",
  "collection": "myCollection", (or "widgets": "myCollection")
  "result": "myCloneCollection"
},
{
  "func": "DELETE",
  "collection": "myCloneCollection" (or "widgets": "myCloneCollection")
}
```

**Comment by rogerl50** [comment]
@larkob's approach seems adequate, and certainly fills my need. I assume that in either approach, the duplicated widgets will have the same properties (except for id) as the original; they should also have a predefined "is_duplicate" property as Raphael suggested so they can easily be removed all at once. 

In @larkob's approach, where would the generated widgets be placed?

**Comment by robartsd** [comment]
> they should also have a predefined "is_duplicate" property as Raphael suggested so they can easily be removed all at once.

Perhaps the property should be "clonedFrom" and contain the ID of the widget that got cloned.

**Comment by RaphaelAlvez** [comment]
Well it would definitely make things more dificult for my needs. Especially the since I want to generate temporary widgets.

The idea to add the original widgets I'd is definitely better then mine.

At the end of the day I'll be happy with whatever the coder who takes this issue is willing to make.

**Comment by rogerl50** [comment]
What do you mean by "temporary"? What would their lifetime be, and how would you remove them?

**Comment by RaphaelAlvez** [comment]
> What do you mean by "temporary"? What would their lifetime be, and how would you remove them that is different from what @larkob proposed?

I'm imagining less than a couple of minutes. Something pop-ups up, you interact and dismiss.
My initial proposal has space for flexible properties so you can easily set owner, color and other stuff.
Setting the owner would be the most important part as the idea came from making pop-up holders and making zoomed hands

**Comment by rogerl50** [comment]
How about something like
```
{
  "func": "CLONE",
  "source": "myCollection", (or "widgets": "myCollection"),
  "count": <number>,
  "applyVariables": [
     {
         "parameter": "<existing widget property>", 
         "variable": "<new value>"
     },
    {
        "parameter": "<new, custom property of this set of clones>",
        "variable": "<value>"
    }
  ]
  "collection": "myCloneCollection"
}
```
In addition to changing the `CLONE` syntax a little bit to be more compatible with the property names used in `SELECT`, this allows you to create more than one at once, to alter existing properties (like color for instance), and to add a new property to all cloned objects, which could be used for example to distinguish different sets of clones so they could be independently deleted. I also like Lars' idea of adding a `clonedFrom` property for all clones containing the `id` of the source widget.

**Comment by RaphaelAlvez** [comment]
I understand why you did what you did but that's not how applyVariables is used elsewhere. Count is really a needed feature that we forgot about. I think that it would make sense to keep xOffset and yOffset as we would want an easy way to change the final position

```
{
  "func": "CLONE",
  "source": "myCollection", (or "widgets": "myCollection"),
  "count": <number>,
  "properties": {"applyVariables": [
     {
         "parameter": "<existing widget property>", 
         "variable": "<new value>"
     },
    {
        "parameter": "<new, custom property of this set of clones>",
        "variable": "<value>"
    }
  ],
  "customProperty":"anotherValue"}
  "collection": "myCloneCollection"
}
```

**Comment by rogerl50** [comment]
That looks good. So would xOffset and yOffset be the offset of the new (stack?) of widgets from the source widget, or would it work like stackOffset{X,Y} does now? I think I'd prefer the former, that all the clones be stacked together at xOffset, yOffset from the original, but maybe it should be an option. At the risk of making things more complicated, you could reuse dropOffset and stackOffset here as well.

**Comment by robartsd** [comment]
>  I also like Lars' idea of adding a `clonedFrom` property for all clones containing the `id` of the source widget.

I'm not Lars.

> ```
> {
>   "func": "CLONE",
>   "source": "myCollection", (or "widgets": "myCollection"),
>   "count": <number>,
>   "properties": {"applyVariables": [
>      {
>          "parameter": "<existing widget property>", 
>          "variable": "<new value>"
>      },
>     {
>         "parameter": "<new, custom property of this set of clones>",
>         "variable": "<value>"
>     }
>   ],
>   "customProperty":"anotherValue"}
>   "collection": "myCloneCollection"
> }
> ```

This looks like good syntax to me. Of course we'd use the expanded "applyVariables" and be able to pull in properties from existing widgets or use string templates if desired as well as directly using variables.

**Comment by rogerl50** [comment]
> > I also like Lars' idea of adding a `clonedFrom` property for all clones containing the `id` of the source widget.
> 
> I'm not Lars.
> 
I knew that :)

**Comment by rogerl50** [comment]
Should the `CLONE` operation also clone children of the selected widgets? I'll note that right now, if you duplicate a widget in the editor, the children are not duplicated. So consistency might indicate that `CLONE` should not do so either. (And my guess is that this will primarily be used just to replicate simple widgets.)

If we end up that it does, however, should a `DELETE` remove all the children?

**Comment by RaphaelAlvez** [comment]
> Should the `CLONE` operation also clone children of the selected widgets? I'll note that right now, if you duplicate a widget in the editor, the children are not duplicated. So consistency might indicate that `CLONE` should not do so either. (And my guess is that this will primarily be used just to replicate simple widgets.)
> 
> If we end up that it does, however, should a `DELETE` remove all the children?

Well there is another e issue that suggest it should duplicate children to using the UI

**Comment by rogerl50** [comment]
There's still something wrong here. Go to http://212.47.248.129:3286/foo, move two cards from the deck to the holder just above, and press the clone button next to that holder. In edit mode, the original deck now shows 68 cards, as it should. Now delete clones. The handle on the deck now reads 52, but in edit mode the deck claims to have 68 cards. There are in fact only 52 there. 

Further, if I then delete the holder containing the deck, the screen flashes and some but not all cards are removed. The holder remains.
