### ISSUE TITLE
receiving a 404 error on any pcio file i try to upload

### ISSUE THREAD

**Issue by vcampo99** [ArnoldSmith86/virtualtabletop#1949]
when uploading any pcio file, even a simple one with just a card deck I get a 404 error. Tried in 2 different browsers, edge and brave.

**Comment by 96LawDawg** [comment]
That must have happened when we recently updated the pcio importer logic.  Until fixed, you can get a file to update by going back to a recent-ish PR test room that was not affected.  This one works: https://test.virtualtabletop.io/PR-1908/yourroomnamehere

**Comment by 96LawDawg** [comment]
Probably broken by #1915 but haven't tested with git bisect.

**Comment by ArnoldSmith86** [comment]
Do the games you tested on https://test.virtualtabletop.io/PR-1950/pr-test ?
