### ISSUE TITLE
renaming a widget in the JSON makes the editor lose connection to the widget

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#1974]
This causes a client crash when using the dragToolbar unless you click on the widget again first.

**Comment by 96LawDawg** [comment]
My bad.  I forgot to open an issue on this a long time ago.  I just got used to it.

![Screenshot 2023-11-23 092938](https://github.com/ArnoldSmith86/virtualtabletop/assets/76912527/472aa8e9-1e5a-4011-a0a4-72e19b4550a1)
