### ISSUE TITLE
Using DELETE on cards that are in pile

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1978]
If you use DELETE on cards that are in a pile, you can end up with a pile that the handle says had negative numbers, but actually has cards in it.

**Comment by ArnoldSmith86** [comment]
I can't reproduce it: https://virtualtabletop.io/8ff3

Do you have an example?

**Comment by 96LawDawg** [comment]
Cannot reproduce.  No idea what was going on that long ago.  Closing.
