### ISSUE TITLE
Adding a pawn in edit mode, after cancelling an INPUT overlay, crashes the client

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#2002]
Probably the same issue as #2000 but in case it's not...

Doesn't seem to happen when clicking the Cancel button; only when using ESC.

**Comment by 96LawDawg** [comment]
Git bisect shows this is the problem commit 230bb76547fd498e6024fd0a5e5b92f2aefb2b00.  Ironically named "fixed crash when pressing ESC on an INPUT overlay.  Part of #1873.
