### ISSUE TITLE
"Flip pile" button on the stack handle flipping to defined face

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#202]
I think it would be better if the "Flip pile" button on the stack handle would flip all cards to a defined card face instead of just switching the current face.

**Comment by larkob** [comment]
I agree. I believe what's missing here is a means to provide names for each card face in JSON, so the user can make a meaningful decision rather than having to guess what card face 0 represents. Not all cards have two faces, so we cannot simply offer to choose between "backside" and "frontside".

**Comment by 96LawDawg** [comment]
Closed by #646 and #905 as this can now be customized by the game designer.
