### ISSUE TITLE
Enable applyVariables to be used for a parameter in a field in the function INPUT.

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#204]
INPUT seems to be a powerful tool for changing settings on a widget because it could enable someone to change multiple settings at once.  It also seems to me that if applyVariables was able to be used for a parameter in a field in the input function, then people could use GET to get the current settings and pre-populate the INPUT form with the current settings, which would make editing using INPUT easier.  Also an image type under INPUT might be nice as well.

Here is an example where I tried to pre-populate an INPUT form with the current text from a label.
https://virtualtabletop.io/8jsu

I realize this might all be made obsolete by the pending UI changes.

**Comment by ArnoldSmith86** [comment]
I feel like this was implemented a long time ago and improved by #307. The image part isn't done but you opened an issue for that (#203) so I will close this issue.
