### ISSUE TITLE
Create onLoadRoutine to allow immediate shuffle, etc. when loading game from saved library state

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#205]
Juddly brought up a concern that when a game is loaded from its saved state in the library, the cards will always be in the same order they were in when the game was created.  This makes it is possible for every game to start out the same way.  Although his question was about Duel 52, the problem applies to every game that relies on shuffled cards and maybe other random order widgets.

Several solutions were discussed in the #help channel which also identified the need to support saved games.  So an onLoad command would need to be optional and not mandatory so that players can come back to saved games.

The best, I think, solution came from BicycleIndividual:  Perhaps we provide onLoadRoutine as a property that can be set for widgets, and an option for if onLoadRoutine should be run or not when saving state. In the game list the option could be labeled "Reset game on load?"

This certainly warrants further discussion and comment about how to best implement this.

**Comment by bjalder26** [comment]
PR #540 should make this possible.

**Comment by ArnoldSmith86** [comment]
> PR #540 should make this possible.

Only if you're the only player in the room while loading the game though.

This should really get its own proper feature.

**Comment by robartsd** [comment]
> PR #540 should make this possible.

Yes, you could have a non-paused timmer saved in a room then have that timer trigger a routine after it starts. This would probably require manually editing the JSON to set up the timer state though. I don't think having other players in the room would be a problem. The player who started the timer would be the one running the reset routine. Only issue would be if other players get a delta in first that causes the timer player's delta to be rejected.

**Comment by ArnoldSmith86** [comment]
> I don't think having other players in the room would be a problem.

```Javascript
if(delta.paused === false && activePlayers.length == 1)
  this.startTimer();
```

I guess it could be changed to "if I'm `activePlayers[0]`" though. Hmm. Maybe it should always be run by `activePlayers[0]` and when they leave, the new `activePlayers[0]` takes over.
