### ISSUE TITLE
Weird behaviour with rotation when using onEnter

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#207]
![image](https://user-images.githubusercontent.com/78076361/107244643-88bc1700-6a2e-11eb-8089-cdbab6af3cad.png)
the holder is not rotated, but rather the height and width dimensions are reversed compared to default holders. the holder has a onEnter property to rotate the cards by 90°. for some reason the card appears to have a certain offset in respect to the holder even though dropOffsetX/Y is set to 0.

**Comment by robartsd** [comment]
The card is located aligned based on the top left corner of the holder and the top left corner of the card. It is then rotated around the center of the card. This is the expected behavior. Not sure what you're trying to do, but I'd recommend rotating the holder instead of the card if possible.

**Comment by RaphaelAlvez** [comment]
Even though in this case is looks like a bug as @robartsd said, upon more though we realised that this is the intended behavior.

Cards are rotated from the center
