### ISSUE TITLE
inheritFrom does not immediately update some properties

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#2117]
To see this issue, make a couple of widgets.  Inherit something on the second widget that is not already specified (like activeFace 1 on the main widget and activeFace 0--default gray--on the second widget).  The change is instant; it happens as soon as you finish typing.  But try to change x (or another property that already is not gray on the second widget) and the change does not take place immediately.  Of course, you have to delete the x or whatever on the inheriting widget. But when you do the deletion, the change still does not take place.  You have to change the inheritFrom property again (change anything about it like delete the x and put it back, or add a space and then delete it).

**Comment by ArnoldSmith86** [comment]
Probably related to #1969. Can't remember what happened there exactly.

**Comment by 96LawDawg** [comment]
> Probably related to #1969. Can't remember what happened there exactly.

Yes.  Probably the same.  And probably caused by #1718 or #1862 because I first started noticing it around that time.
