### ISSUE TITLE
MOVE to a seat does not correctly assign the owner if the card is already located in the hand

### ISSUE THREAD

**Issue by andypymont** [ArnoldSmith86/virtualtabletop#2141]
When executing the [MOVE function](https://github.com/ArnoldSmith86/virtualtabletop/wiki/Functions#move) to move cards directly to a seat, these cards should end up in the assigned hand for the seat, with the owner matching the seated player if the hand has `childrenPerOwner` set to true.

However, if the cards being moved are already in the hand holder (for example, in the hand of another player), then this assignment does not happen correctly, and instead the cards end up with no owner assigned at all, meaning that all players can see them and the `childrenPerOwner` setting ends up having been ignored.

[Example game definition illustrating the bug](https://gist.github.com/andypymont/0f18e86767b4a1e24274b19cd5d895eb)

**Comment by andypymont** [comment]
Steps to reproduce in the provided example room:
1. Take both seats (using separate browser sessions/player names);
2. Recall, shuffle, and deal the cards using the provided buttons. Each player will have 5 cards in hand.
3. Press one of the provided buttons to give all of one player's cards to the other player. The moved cards will end up visible in both players' hands instead of having the correct owner assigned.

**Comment by 96LawDawg** [comment]
May be related to #1973 and #1116.  Maybe not.

**Comment by 96LawDawg** [comment]
Also check how this ties in to the work done on #933.
