### ISSUE TITLE
Feature request: "display" property for widgets and objects

### ISSUE THREAD

**Issue by Tobl4** [ArnoldSmith86/virtualtabletop#2166]
It might be useful to have a property "display" that can be set to false to hide a an object. Two examples where this might be used:

**1) Objects on faceTemplates for card decks**
In Egyption Epochs, the scarab for permanent tiles must be shown on some cards and hidden on others. Currently, this is implemented like this:

```
  "cardDefaults": {
    "scarabcolor": "#e30022"
  },

  …

    "tile-nile": {
      "color": "#6495ed",
      "image": "/i/game-icons.net/delapouite/palm-tree.svg"
    },
    "tile-flood": {
      "color": "#6495ed",
      "image": "/i/game-icons.net/delapouite/oasis.svg",
      "scarabcolor": "transparent"
    },

  …

  "faceTemplates": [
    {
      "objects": [
        {
          "type": "image",
          …
          "value": "/i/game-icons.net/lorc/gold-scarab.svg",
          "svgReplaces": {
            "#000": "scarabcolor"
          }
        }
      ]
    }
```
This works, however, it is not semantic and presents a barrier to new mod developers. In addition, it is important to to set up this workaround the right way around. In the same cardDeck, the crosses for disaster tiles also need to be shown on some cards and not on others. However, for those, the cardDefault is defined as "transparent", with the cards that show the cross overriding the value to red. As a result, if someone wants to alter the color of the cross, they have to do so for each cardType that features it.

With the display Property, this could be rewritten like this:
```
    "tile-nile": {
      "color": "#6495ed",
      "image": "/i/game-icons.net/delapouite/palm-tree.svg",
      "showScarab": true
    },
    "tile-flood": {
      "color": "#6495ed",
      "image": "/i/game-icons.net/delapouite/oasis.svg"
    },

  …

  "faceTemplates": [
    {
      "objects": [
        {
          "type": "image",
          …
          "value": "/i/game-icons.net/lorc/gold-scarab.svg",
          "dynamicProperties": {
            "display":"showScarab"
          }
        }
      ]
    }
```

**2) Widgets that need to be hidden with the option to later reappear in the same spot**
In this fork of the Great Greece mod parts of the map need to be hidden: https://virtualtabletop.io/game/lr20tzaf/great-greece-smaller-maps-rivers They cannot be deleted, as there is the possibility that they will need to be re-shown when setting up the game for a second match.
This is currently achieved by setting their layer to -50, which is hidden behind a large image
```
            {
              "func": "SELECT",
              "property": "remove_left",
              "relation": "==",
              "value": true
            },
            {
              "func": "SET",
              "property": "layer",
              "relation": "=",
              "value": -50
            },
```
To re-show them, the layer must be set to the original value of 1
```
        {
          "func": "SELECT",
          "property": "map_hex",
          "relation": "==",
          "value": true
        },
        {
          "func": "SET",
          "property": "layer",
          "relation": "=",
          "value": 1
        },
```
This is, again, not semantic. In addition, if the "correct" layer to show them at later changes from 1 to a different value, the modder would need to remember to also change the value in this routine.

With a display property, this could be rewritten more semantically as
```
            {
              "func": "SELECT",
              "property": "remove_left",
              "relation": "==",
              "value": true
            },
            {
              "func": "SET",
              "property": "display",
              "relation": "=",
              "value": false
            },
``` 
```
        {
          "func": "SELECT",
          "property": "map_hex",
          "relation": "==",
          "value": true
        },
        {
          "func": "SET",
          "property": "display",
          "relation": "=",
          "value": true
        },
```
This makes no assumption about the overall layer composition of the mod.

**Comment by ArnoldSmith86** [comment]
> This is currently achieved by setting their layer to -50, which is hidden behind a large image

FYI: I usually set `owner: []` to hide and `owner: null` to unhide.

But I like the idea of a dedicated `display` property.

**Comment by 96LawDawg** [comment]
> > This is currently achieved by setting their layer to -50, which is hidden behind a large image
> 
> FYI: I usually set `owner: []` to hide and `owner: null` to unhide.
> 

And I usually set "scale":0 to hide things rather than change their layer.  Not against this, just suggesting another alternative that probably works better than layers..

**Comment by Tobl4** [comment]
> > This is currently achieved by setting their layer to -50, which is hidden behind a large image
> 
> FYI: I usually set `owner: []` to hide and `owner: null` to unhide.
> 
> But I like the idea of a dedicated `display` property.


> > > This is currently achieved by setting their layer to -50, which is hidden behind a large image
> > 
> > 
> > FYI: I usually set `owner: []` to hide and `owner: null` to unhide.
> 
> And I usually set "scale":0 to hide things rather than change their layer. Not against this, just suggesting another alternative that probably works better than layers..

Good to know that there's other options, but both of these aren't semantic, and both require re-setting it to the right value. (It's not guaranteed that the "correct" value for owner and scale are null and 1 respectively)
