### ISSUE TITLE
TURN function freezes game interaction if all occupied seats are "skipTurn" : true

### ISSUE THREAD

**Issue by Tobl4** [ArnoldSmith86/virtualtabletop#2172]
https://virtualtabletop.io/bedv

Observed behavior: Calling the TURN function if at least one seat is occupied but all occupied seats have "skipTurn" set to true freezes the game for the client calling the function. Initially, the poker chip can be dragged around, but as soon as the TURN button is pressed, that client can no longer interact with the game until they reload the page.

Expected behavior: Keep the current turn unchanged and return to the calling routine, same as when no seat is occupied.

**Comment by 96LawDawg** [comment]
Well, that's about the 1,000 problem we've had with TURN and it has been refactored 3-4 times.  Ugh.

Console reports:

![Screenshot 2024-07-03 221423](https://github.com/ArnoldSmith86/virtualtabletop/assets/76912527/f50dc15d-b675-45a9-a526-9e11683c4bf8)
