### ISSUE TITLE
Basic Styles Should Be Widget Properties

### ISSUE THREAD

**Issue by robartsd** [ArnoldSmith86/virtualtabletop#218]
In developer meeting on 12 Feb 2021, we talked about supporting a set of basic styles that should be available as widget properties and implemented in basic or intermediate editor UI. This issue is to discuss which properties should be included.

Properties already in widgets:
- width (px)
- height (px)
- layer
- rotation (deg)

Properties that should be added
- color
- font-family (pre-selected Google Fonts)
- font-size (px)
- font-weight (normal, bold)
- font-style (normal, italic)
- text-decoration (none, underline, line-through)
- text-align (center, left, right, justify)
- padding (px)
- background-color
- border-color
- border-radius (%)
- border-width (px)

**Comment by 96LawDawg** [comment]
Probably will be resolved by #951
