### ISSUE TITLE
INPUT.choose does not show child widgets

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#2188]
Is this a bug or a feature? :grin:

**Comment by 96LawDawg** [comment]
I would say that is the way it is supposed to work. If we want to show child widgets, we should add another parameter.  And then no idea what that display would look like.

**Comment by ArnoldSmith86** [comment]
No, I mean, not list the child widgets separately. But they should be rendered on the widget representation on the INPUT. Here is my current example where the complex widget is visible on the left but when rendered in an INPUT, it only shows the wrapper:

![image](https://github.com/user-attachments/assets/cdacf528-8aef-4223-8355-0250d8fdcd76)

**Comment by 96LawDawg** [comment]
Oh.  That seems like a bug in your use case. But I can also imagine situations where we don't want that.  For example, take the solitaire games where cards have holders that have cards that have holders in a nested parent/child relationship. If I wanted to INPUT one of those cards, I wouldn't want them all. So I think we still need a parameter.
