### ISSUE TITLE
PCIO import bug: move count "all" should be 0

### ISSUE THREAD

**Issue by pipejakob** [ArnoldSmith86/virtualtabletop#2193]
Attached a simple example of this issue: [move-demo.pcio](https://github.com/user-attachments/files/16576851/move-demo.pcio.zip)

Original PCIO automation for a button to move all cards from one holder to another:

```json
  {
    "type": "automationButton",
    "label": "Move cards",
    "clickRoutine": {
      "steps": [
        {
          "id": "c378c4d8-774d-453f-a400-373644111dab",
          "func": "MOVE_CARDS_BETWEEN_HOLDERS",
          "args": {
            "objects": {
              "type": "query",
              "queryWidgetTypes": [
                "card",
                "piece"
              ],
              "holders": [
                "d45ea740-910f-47fe-bf8c-042e3ebc4a24"
              ]
            },
            "to": {
              "type": "literal",
              "value": [
                "d1be7dcc-50e4-442e-ad21-775d79b5270f"
              ]
            },
            "quantity": {
              "type": "literal",
              "value": "all"
            }
          }
        }
      ]
    },
```

When imported to VTTio, this becomes the widget:

```json
  "clickRoutine": [
    {
      "func": "MOVE",
      "count": "all",
      "to": "d1be7dcc-50e4-442e-ad21-775d79b5270f",
      "from": "d45ea740-910f-47fe-bf8c-042e3ebc4a24"
    }
  ]
```

The MOVE invocation doesn't report any errors, but also does nothing. Changing `"count": "all"` to `"count": 0` fixes it.

**Comment by 96LawDawg** [comment]
See if 2194 fixes it: https://test.virtualtabletop.io/PR-2194/pr-test.

**Comment by pipejakob** [comment]
Haha whoops, raced you https://github.com/ArnoldSmith86/virtualtabletop/issues/2193 :-).

> See if 2194 fixes it: https://test.virtualtabletop.io/PR-2194/pr-test.

Tested and verified; ship it!

**Comment by 96LawDawg** [comment]
I had no idea you were going to try and do it yourself.  Thanks.  Your code is actually more compact.  I'll approve that one and @ArnoldSmith86 can review and approve or not.
