### ISSUE TITLE
name overlays in library are inconsistent

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#2198]
We have several games in the library that don't have a "Similar to" entry and show their game name on the image.

Some of them overlay their name over the image anyway. Examples: A Simple Life, Cards Against Humanity

Others don't. Examples: An Infamous Traffic, Steam Power

IMO, we should do this consistently in the public library.

I personally prefer not overlaying the name but either way is fine with me.

**Comment by 96LawDawg** [comment]
I also like not overlaying the name as long as the name is visible on the library image and there is no "similar to."  Union Station is another example of that

**Comment by ArnoldSmith86** [comment]
> But QQ Step is a borderline case. The name is there, but it is not as readable as the others.

Yeah, I guess it's up to the author then?
