### ISSUE TITLE
Scrappet Kaiser Princess has missing library image on my local server

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#2205]
![image](https://github.com/user-attachments/assets/042ce526-7341-4933-aac8-14de5172cc23)

So does Stardust Butterfly:

![image](https://github.com/user-attachments/assets/f1753da9-704b-448f-8833-2d663dfec9ec)

**Comment by 96LawDawg** [comment]
I have no idea how that is possible.  The assets in the .vtt files have the library image files in them.  And the metadata properly references the asset name.
