### ISSUE TITLE
Cards do not accept children

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#225]
When trying to attach widgets to a card, the widget simply disappears from the board.  See demo room at [https://virtualtabletop.io/09of](https://virtualtabletop.io/09of).  The single card at the top, King of Spades, has the ID of "cardtest."  Try setting the parent of a holder, card, or another widget type to that card and the widget simply disappears.

**Comment by ArnoldSmith86** [comment]
I don't have time to fix it right now but I know what's wrong and will fix it soon (unless someone else is faster):

The CSS rules that hide the inactive card faces are too broad and actually hide any child widgets. Cards also have an `overflow: hidden` that break it; that should be on the faces instead.
