### ISSUE TITLE
Implement clickRoutine using onEnter and onLeave

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#23]
Feature: Automatic functions
  As a game player
  I want certain things to happen automatically
  So that the game keeps up with what I am doing without having to click a button.

Scenario Outline: Update count
  There is a holder for captured game pieces
  When I move a game piece there, the onEnter property triggers an update to a label showing the count of captured game pieces.

**Comment by rogerl50** [comment]
Note that as per discussions in the discord, this could be implemented by allowing the full range of `clickRoutine` functions in the `onEnter` and `onleave` which to me would be preferable, or alternatively by allowing `onEnter` and `onLeave` to cause a button click.

**Comment by UltimateGeek** [comment]
@rogerl50 Did someone take the time to create an example of what the json would look like?

**Comment by 96LawDawg** [comment]
I am not a programmer.  But all I envisioned was a change to the onEnter (and onLeave) property that would allow me to insert JSON exactly like in the high-and-low level buttons.  I think Raphael wants a new property (like clickTrigger) or something.  I don't know how to code it.  I just want access to the button functions by moving an object into or out of a holder.

**Comment by rogerl50** [comment]
No we didn't. But the default initial position would be that what is allowed is identical to what is allowed in the clickRoutine.

**Comment by ArnoldSmith86** [comment]
I would prefer if it called a button instead. It's more work for the game creator but I'd prefer if this stuff stays in one place.

I do think this is a nice feature though.

**Comment by rogerl50** [comment]
Is there a way to create an invisible, non-clickable button on the table surface? If we have to put it offscreen, then it becomes painful to change its `clickRoutine`.

**Comment by RaphaelAlvez** [comment]
If we choose to go with the trigger being on the automation button, I suggest having the routines separated from the click routines. In this case, I would recommend using three types of automation:
- clickRoutines
- triggerRourines
- continuousRoutines

**Comment by pwinckles** [comment]
After browsing click routine code, it seems reasonable that the evaluation logic could be abstracted out of the button widget so that routines could be executed by other widget types without needing to duplicate any internal logic.

The only one that is a little questionable is `INPUT`, but I'm not sure that it makes sense for a widget apart from a button to use it.

**Comment by RaphaelAlvez** [comment]
> After browsing click routine code, it seems reasonable that the evaluation logic could be abstracted out of the button widget so that routines could be executed by other widget types without needing to duplicate any internal logic.
> 
> The only one that is a little questionable is `INPUT`, but I'm not sure that it makes sense for a widget apart from a button to use it.

What I believe people are suggesting is that those trigger work lin the CLICK clickRoutine. You would still need buttons to be activated.

**Comment by pwinckles** [comment]
Yes, I was just agreeing with @rogerl50 that it seems a little complicated to make a button that you do not actually want people to click in order to code a routine that is executed everytime a card leaves a holder, and suggesting that it is perhaps not to difficult to the internal routine evaluation logic so that it can be reused on different widget types so that invisible buttons do not need to be added.

**Comment by larkob** [comment]
If we take the clickRoutines out of their widgets, it's hard for anyone other than the game designer to figure out which routine is used where. They would pretty much have to search the json. Also, we already have CLICK as an action if a game designer has good reasons to re-use clickRoutines. So, I'd prefer clickRoutines to be placed in context of where they are triggered.

**Comment by ArnoldSmith86** [comment]
Raphael, can you describe what your proposal was? Something with triggers?

**Comment by RaphaelAlvez** [comment]
> If we take the clickRoutines out of their widgets, it's hard for anyone other than the game designer to figure out which routine is used where. They would pretty much have to search the json. Also, we already have CLICK as an action if a game designer has good reasons to re-use clickRoutines. So, I'd prefer clickRoutines to be placed in context of where they are triggered.

This would mean more work if you need multiple triggers to the same automation.
Example: clicking one spinner makes every other spinner to spin.

**Comment by RaphaelAlvez** [comment]
> Raphael, can you describe what your proposal was? Something with triggers?

My proposal would have 3 types of routines with different objectives:

- clickRoutines: What we already have

- triggerRoutines: Would check an array of possible actions executed in widgets and execute the routine. Same routines available on clickRoutines.

- continuousRoutines: This one would be checking more complex conditions. for example, if a sum of counters values is bigger than a values. Same routines available on clickRoutines but would be more powerful with simple conditional testing.

**Comment by pwinckles** [comment]
> 
> 
> > If we take the clickRoutines out of their widgets, it's hard for anyone other than the game designer to figure out which routine is used where. They would pretty much have to search the json. Also, we already have CLICK as an action if a game designer has good reasons to re-use clickRoutines. So, I'd prefer clickRoutines to be placed in context of where they are triggered.
> 
> This would mean more work if you need multiple triggers to the same automation.
> Example: clicking one spinner makes every other spinner to spin.

You could still get the same behavior if you have the routine call `CLICK` on the button you have your common logic in. The advantage with allowing the routine definition to be on the widget that initiates the routine is that it is simple and easy to understand by default, as @larkob was saying, while still allowing you to centralize logic in a button if you wanted to by using `CLICK`.

**Comment by robartsd** [comment]
> > Raphael, can you describe what your proposal was? Something with triggers?
> 
> * continuousRoutines: This one would be checking more complex conditions. for example, if a sum of counters values is bigger than a values. Same routines available on clickRoutines but would be more powerful with simple conditional testing.

I don't think continuousRoutines makes makes sense. Instead counters could have onChange routines to deal with the described scenario (each of the counters would a have an onChange routine to trigger the check - probably with the check logic centralized in a button).
