### ISSUE TITLE
re-enable details for anonymous widgets in the tree

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#2314]

**Comment by ArnoldSmith86** [comment]
There's actually still the `Toggle wide editor` button above the JSON editor commands. It no longer changes the width of the editor, but it still toggles those details in the tree.

**Comment by 96LawDawg** [comment]
Aha!  Maybe the PR for this would just get rid of the button and make that effect permanent?  Alternatively, move the button to display when the tree is shown and change the button icon to something else because that is not intuitive.

**Comment by ArnoldSmith86** [comment]
Yeah, I would either just always display the details or display them if the tree is wider than X.
