### ISSUE TITLE
Changing playerName broken?

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#2351]
I came across this while looking at #1631.

https://virtualtabletop.io/wrrq

I think changing playerName might have gotten broken when there was an update to player cursors.
![image](https://github.com/user-attachments/assets/8ad116e9-13c4-4191-9d10-b39da2ea0684)
It looks like this was this update:
![image](https://github.com/user-attachments/assets/3a5d434f-4892-4d88-9981-ac182f864f09)
https://github.com/ArnoldSmith86/virtualtabletop/pull/1829/files

Maybe this can be fixed with an `if(playerCursors[e.player])` but @ArnoldSmith86 should probably look at it.

**Comment by ArnoldSmith86** [comment]
How did you trigger the error? Pressing the button in your room doesn't seem to cause issues for me in Firefox or Chrome.

**Comment by bjalder26** [comment]
> How did you trigger the error? Pressing the button in your room doesn't seem to cause issues for me in Firefox or Chrome.

I think the new name has to include a non-letter character (e.g. numbers, !, etc.).

I have no idea why that would be the case.

**Comment by bjalder26** [comment]
On second thought, I think it just has to not be the same as the current name.  Also, it won't crash if it had already crashed and you don't refresh the browser.

It looks like it is looking for the previous name, and I'm guessing that it has already been removed from playerCursors.

I updated the room, and it should trigger it every time (or after 2 clicks) because it now cycles through names.
