### ISSUE TITLE
conflict detection doesn't trigger when removing a widget and setting parent to it

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#2360]
If one client sends a delta that removes a widget and another client sends a delta that adds another widget to the _not yet_ removed widget, the conflict detection doesn't trigger.

This (and probably some other cases like deck) need to be checked and simply trigger conflict resolution (re-sending game state to the second client).

**Comment by rogerl50** [comment]
Note that in my case, when this happened, indeed a card had vanished in addition to the client crashes.
