### ISSUE TITLE
Position of stars in starred games on Create Room overlay

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#2365]
So we just fixed the position of the number of starred games on the main VTT screens.  But it is still out of place when you invite use the shared link feature.  For example, linking someone to Uncheckered through https://virtualtabletop.io/game/uncheckered gives this:

![Screenshot 2024-11-20 180824](https://github.com/user-attachments/assets/2a3b21d1-56c3-41c2-a883-d5ab65a96b1b)

The problem is the 8 (I think it is an 8) is over the first C in Uncheckered.  Probably the same fix as #2359 is needed, but in a slightly different location in the css.

**Comment by bjalder26** [comment]
It looks like `.mainStateImage span {...}` in `/client/css/overlays/welcome.css` needs the top to be changed from 51px to 17 px.

```
.mainStateImage span {
    position: absolute;
    font-size: 16px;
    top: 51px;
    width: 62px;
    text-align: center;
    color: #fff;
    font-weight: 700;
}
```
