### ISSUE TITLE
Copy room from invalid URL

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#2366]
If you paste an invalid URL into the JSON Editor to try and copy from another room, you get the error message that the room crashed and to submit the problem and reload it.

**Comment by bjalder26** [comment]
Are you sure this is about pasting in an invalid url, and not about selecting a url (valid or not) from the drop down menu?  Because that is what is causing a crash for me.
![image](https://github.com/user-attachments/assets/67ad3f93-97ea-41ee-a592-7f5ad12a601d)

**Comment by 96LawDawg** [comment]
Top left button in the attached.  Paste an invalid URL and it crashes.

![Screenshot 2024-11-24 234159](https://github.com/user-attachments/assets/9bec64b6-d907-4178-8939-ba71dc65eb68)

**Comment by bjalder26** [comment]
I figured out a url invalid enough to trigger it.  It looks like this fetch in jsonedit.js needs error handling.

![image](https://github.com/user-attachments/assets/effb7157-75a9-49af-8b1e-9a7270fb22e7)

```js
const jeCommands = [
  /* Just for editing convenience, the top (command) buttons are listed first */
  {
    id: 'je_copyState',
    name: 'Copy state from another room/server',
    icon: '[import_room]',
    forceKey: 'C',
    options: [ { type: 'string', label: 'URL' } ],
    call: async function(options) {
      const sourceURL = options.URL.replace(/\/[^\/]+$/, a=>`/state${a}`);
      const targetURL = location.href.replace(/\/[^\/]+$/, a=>`/state${a}`);
      fetch(sourceURL).then(r=>r.text()).then(t=>{
        fetch(targetURL,{
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: t
        })
      });
    }
  },
```
I suppose it either needs `.catch()` or a try/catch block.
