### ISSUE TITLE
Add player count to menu

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#2373]
A version of this idea was originally suggested by @bjalder26 in #1859.

The main sidebar/bottombar menu has Game Shelf, Active Game, Players, About, and Edit Mode.  It might be a nice addition to add the current active player count near the Players text/icon.  It appears in multiple different configurations depending on the size of the window, but I think a number that reflected the active players in the room would be useful.  And the number could flash or change color briefly as an alert to let people know someone has entered or left.

**Comment by 96LawDawg** [comment]
Awesome.  I was literally just about to start work on this.  You are correct that `activePlayers.length` is what is needed for the basic part.  I tossed that into a console.log and it worked great.  I'll work on getting it properly css'd here next.

**Comment by ArnoldSmith86** [comment]
Maybe we just change "Players" in the menu to "3 Players"? Not sure..

**Comment by 96LawDawg** [comment]
I have it like "Players: 3" right now.  Just tweaking some more.

**Comment by RaphaelAlvez** [comment]
Players: n sounds perfect to me
