### ISSUE TITLE
Add default property to full size board backgrounds

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#24]
Feature: Add "movableInEdit":true
  As a game designer
  I usually do not want the board background to move
  But I end up clicking it when editing other pieces

Scenario Outline: Game editing
  After clicking "upload board"
  Add the default words in the JSON, but make it set to true, which is the current setting
  Then it is easier to change the behavior without additional typing

**Comment by UltimateGeek** [comment]
The last sentence in the scenario should be part of the user narrative.

The test scenario I think can be written like this:

```gherkin
Scenario: Add board
  Given a room
  When I add a new board
  Then it is configured to not be moveable in edit mode
```

**Comment by 96LawDawg** [comment]
The new JSON Editor essentially takes care of this.  Closed.
