### ISSUE TITLE
Unexpected behavior in drawing corners on cards

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#240]
Tonight in my poker game, I noticed square corners on cards that I don't think had ever been there before.  I brought it up to the other players, and we identified that different people were seeing different things.  The first screen shot is from my computer.  Notice the square corners on cards 2,4,5 (counting from the left) and rounded corners on the other cards.  The second screenshot is from another player of the SAME cards.  Notice the square corners on cards 2,3,4 and rounded corners and 1 and 5.

As I said, as best I can remember, this is new since the last time I played last week (February 23).

![Version 1](https://user-images.githubusercontent.com/76912527/109750175-93874900-7ba1-11eb-94e2-dac22050e738.jpg)

![Version 2](https://user-images.githubusercontent.com/76912527/109750179-95e9a300-7ba1-11eb-90d0-ee59c354659c.jpg)

**Comment by 96LawDawg** [comment]
Looking in other rooms at other games, I notice the same thing.  Lots of cards have squared rather than rounded corners.  And the effect seems to be random.  I looked to that PRs that closed in the last week or so and can't find anything that might be causing this but hopefully somebody can figure out what's going on.

**Comment by robartsd** [comment]
It could be #226. `overflow:hidden` was removed from cards.

**Comment by 96LawDawg** [comment]
Adding overflow:hidden back in fixed the problem.  I tested it on my local machine.  I don't have time today to do a PR, but if anybody does, then please do.  It's a minor annoyance, but it will impact most games with cards so should be fixed soon.

**Comment by robartsd** [comment]
What I can't figure out is why the change of this css property on the card is having any affect at all. All of the visual aspects of the card are within the faces which still have `overflow:hidden``. What is even more confusing is that moving one card can affect the appearance of another. I'd like to understand the root cause better before we just hide it under a css property that seems to fix it.

**Comment by 96LawDawg** [comment]
I can't disagree with your logic that we should find out the root cause.  But in the meantime ```overflow:hidden``` does at least cosmetically solve the problem.  I'm all for finding the solution, but unless that is fast in coming, in the meantime, I would propose we go back to what we had before (but adding that back in will still allow widgets to be children of cards, so actually we'll still be better off than we were a week ago).

**Comment by 96LawDawg** [comment]
Closed by accident because I don't know what I'm doing.

**Comment by 96LawDawg** [comment]
Through testing today, we learned that this effect is not visible on all browsers.  For example, Firefox does not show the square corners.

**Comment by 96LawDawg** [comment]
Fixed by #308.

**Comment by robartsd** [comment]
I just stumbled across a css issue where background can bleed through the corner a bit. I'm not sure if it is related.

https://tumble.sneak.co.nz/post/928998513/fixing-the-background-bleed
