### ISSUE TITLE
Solo (or simultaneous multiplayer) roll/flip and write?

### ISSUE THREAD

**Issue by scruffynerf** [ArnoldSmith86/virtualtabletop#2422]
I landed on this project while trying to see what the SOTA was, starting from people using tablets/pads with a drawing program or pdf viewer which allows 'overlay sketching' to fill out the playsheet of a roll/write game.  The rules/enforcement being nonexistent, any dice/cards being external, etc.  Essentially it's an erasable digital overlay only.  Useful, and easy.  Load a PDF, and go, no printing requirement.

But I realized that adding dice would make things better.  Add digitalcdice, and suddenly some games become self-contained.
So Yatzhee, as an trivial example.  But let's add in D8, D10, D20, etc... ok, what about non-numeric faces? (So let's say replace the 1 with a smilely face).    So Dice.

Then adding 'cards' makes sense, to allow flip and write games.

And still this is just sitting on a PDF-ed image, allowing a digital pencil/pen to fill out the page.

I was looking for a base for this... (or did it exist), and came across this project (and PC.io) and saw that all of the card stuff, and most of the dice stuff (are non-numeric faces possible?)
And the entire multi-player aspect is handled.

And I see a canvas widget, allowing pictionary type games.

So... the question:

What's missing at this point?  Load a PDF image onto the canvas, under the draw layer?  Private canvas drawing (so that each player can have a playsheet?) Which can be shared or even saved?

Again, solo plays as well.. essentially load the game, and no dice/cards to manage, you see the playsheet, click to roll/flip etc, and draw on the playsheet, and at the end of the game, a screenshot or saved png keeps your playsheet scribbling intact.

How close is this? Or am I just missing it's all here already?

Example games:
Railroad Ink (custom dice faces and individual playsheets)
Ganz Clever series (shared normal dice, but individual playsheets)
30 Rails
Imperial Settlers Roll and Write
Cartographers
Hadrians Wall

**Comment by ArnoldSmith86** [comment]
Shouldn't be a problem. Dice faces can have any image on them and dice can have any number of faces.

For writing numbers, you can use labels instead of canvas. Canvas should work but it's one of the weaker parts of VTT (very low red or pretty resource expensive).

You'll love VTT. Join our Discord if you want more hands on help..

**Comment by 96LawDawg** [comment]
>  Private canvas drawing (so that each player can have a playsheet?) Which can be shared or even saved?

Can't save canvas drawings yet (other than a screenshot as you mention).  There is an issue for that #1057.

**Comment by 96LawDawg** [comment]
@scruffynerf, okay to close this?  We took most of the discussion to Discord and answered the questions here, I think.

**Comment by scruffynerf** [comment]
yup, the answer is "it's doable, not perfect, but certainly the best answer out there at this time"
