### ISSUE TITLE
Turn the enlarge property into an object to include more info for customization

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#244]
The proposal is to include properties like coordinates, enlarge factor,coordinates offset in relation to widgets position and which face is enlarged.

This last one could be used to create pop ups with rules or extra details for cards. This would be useful for games where cards normally have a lot of information. It also has the advantage of being personal and not bothering other players.

**Comment by robartsd** [comment]
Some of this will be enabled with #1180
