### ISSUE TITLE
onHover property

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#245]
This was suggested during this week's meeting.

Would temporarily change any property on a widget when mouse hovers it or long click on mobile.

About the discussion on the meeting:

- This would be only on client side
- Shouldn't be applied while staging or clicking
- Could be used for changing css of buttons when hovering it.
- Could be used to change the of object when hovering and therefore showing more information about a card. (See #244)

**Comment by robartsd** [comment]
Would be much more flexible to game authors if we simply implement #154

**Comment by RaphaelAlvez** [comment]
> Would be much more flexible to game authors if we simply implement #154 

This wouldn't exclude the need of #154 but it would allow simple on hover features and would stay consistent with coding style.

Besides that his would allow changes on any property. Obviously this would open doors to new ways to break games but that's always on the game autor to avoid when making a new implementation.

**Comment by bjalder26** [comment]
With changeRoutines, there could be onHoverChangeRoutines if there was an onHover property that updated when someone hovers over a widget.  It seems like it would require updating event listeners.  The default could be false so that it would only show up in the JSON when someone is hovering over the widget.

**Comment by robartsd** [comment]
> With changeRoutines, there could be onHoverChangeRoutines if there was an onHover property that updated when someone hovers over a widget. It seems like it would require updating event listeners. The default could be false so that it would only show up in the JSON when someone is hovering over the widget.

One problem with this idea is that routine code makes changes to the state that all players see, but hover effects are supposed to just be in the user interface.

**Comment by bjalder26** [comment]
> One problem with this idea is that routine code makes changes to the state that all players see, but hover effects are supposed to just be in the user interface.

That's a good point.  However, I think it might also be nice to allow an onHover property.  For example, a cooperative Fruit Ninja game might be fun, and I don't think that would be possible without an onHover property.
