### ISSUE TITLE
Add more game pieces types to "add widget" overlay

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#246]
Current suggested list is:

- [x] Checker
- [x] Pawn
- [x] Pin
- [ ] House/Building
- [ ] Person/Meeple
- [ ] Flag
- [ ] Poker Chips
- [ ] Cube token
- [ ] Marble

**Comment by 96LawDawg** [comment]
Closed by #1506
