### ISSUE TITLE
Add property to change options color in spinners

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#251]
The options displayed in spinners are actually an svg.
There is already a feature in the platform to recolor SVGs and this should be extended to spinners.
Ideally the line and the font would be both customizable individually. 

On top of that, if possible, changing the font and font size would be a nice extra.

**Comment by RaphaelAlvez** [comment]
@robartsd I know we already discussed this but I created the issue

**Comment by robartsd** [comment]
Since the spinner is an inline SVG generated by the javascript, it can be styled with style sheets applied to the page. The SVG replaces code doesn't fit well with spinners. We should probably come up with a list of properties that we want the spinners to have that get applied when drawing the SVG.
