### ISSUE TITLE
Add timer

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#255]
I was pretty sure there was already an issue with that but I couldn't find it

![Novo Projeto (18)](https://user-images.githubusercontent.com/73476656/110351345-7fb16c00-8013-11eb-9700-7cde70a5d11a.png)
I did some mockups for a possible timer.

automation related to time would be added using propertyChangeRoutine from PR #197.

Time would be in seconds and conversion could be added in COMPUTE covering different formats and units. (I forgot to add this to the mockups).
 
startTime and ednTime would determine if the timer is counting down or up and when time=endTime the counter would be turned off. (active=false)

At this point, the game designer could also use propertyChangeRoutine to trigger a pop-up when the timer reaches its end.

A digital timer could be created with propertyChangeroutines changing the value in a label. One digital timer could be provided in the "add assets" overlay

**Comment by pf-lkobbe** [comment]
I suggest not to have any time conversion. Just use seconds as the unit. 

I believe the timer widget should have a click function so it can be triggered with the CLICK button operation. The question is how a second click should be interpreted? Pause or Reset?

Also, to what degree will property changes using button operations affect the timer on server side? Are active, time, startTime and endTime read-only once the timer is running?

There's a challenge in implementing a clickRoutine for the timer. We need to avoid that the server triggers the same clickRoutine for several players at once. Perhaps we should add another property `owner` which is linked to the player starting/resuming the timer, so the clickRoutine is only triggered for this person and the state change is then shared with everyone else.

**Comment by larkob** [comment]
I suggest not to have any time conversion. Just use seconds as the unit.

I believe the timer widget should have a click function so it can be triggered with the CLICK button operation. The question is how a second click should be interpreted? Pause or Reset?

Also, to what degree will property changes using button operations affect the timer on server side? Are active, time, startTime and endTime read-only once the timer is running?

There's a challenge in implementing a clickRoutine for the timer. We need to avoid that the server triggers the same clickRoutine for several players at once. Perhaps we should add another property owner which is linked to the player starting/resuming the timer, so the clickRoutine is only triggered for this person and the state change is then shared with everyone else.

**Comment by ArnoldSmith86** [comment]
Do timers even need to be server-side? All clients could just check once per second and the one that's the first in the player list could execute a tick handler for each timer.

**Comment by larkob** [comment]
Right, if we need some kind of "owner" anyhow, then this could probably be done client-side only. It needs to be an active player to ensure there's still a client running and checking the timer, so whoever is the top-most active player could be the owner in case the end time has been reached. If that player drops out while the timer is running, the next top-most active player would resume. The timer doesn't need to perfectly timed, so I guess this wouldn't be a problem. And if all players dropped out, the timer would simply pause.

**Comment by ArnoldSmith86** [comment]
When all players leave, the room is unloaded anyway.

**Comment by RaphaelAlvez** [comment]
> I suggest not to have any time conversion. Just use seconds as the unit.

As I suggested I agree that the time should be in seconds. I just suggested to include a conversion function in COMPUTE. That would be used to SET labels or get the minutes value

> I believe the timer widget should have a click function so it can be triggered with the CLICK button operation. The question is how a second click should be interpreted? Pause or Reset?

I included a workflow for that in the image. Basically clicking do play and pause unless the timer has run out. In this case it resets.

> Also, to what degree will property changes using button operations affect the timer on server side? Are active, time, startTime and endTime read-only once the timer is running?

I think we need testing for this but I imagine it would be between 1 and 0.1 second. To frequent could cause lag and too spaced could also **feel** as lag.

**Comment by ArnoldSmith86** [comment]
I think it should just be 1s. If you see the time somewhere, it feels natural to have a "tick" every time the seconds tick.

**Comment by 96LawDawg** [comment]
> Basically clicking do play and pause unless the timer has run out. In this case it resets.

What about if the timer is just counting up and not down?  Click is natural to pause it, but would probably need a separate button to reset?  Or maybe a double-click (not sure that is even possible).

**Comment by RaphaelAlvez** [comment]
> > Basically clicking do play and pause unless the timer has run out. In this case it resets.
> 
> What about if the timer is just counting up and not down?  Click is natural to pause it, but would probably need a separate button to reset?  Or maybe a double-click (not sure that is even possible).

In my proposal the timer has an end. So if you want an infinite timer then just put a very big number as the end time. In this case you would need to use a button to reset the timer
