### ISSUE TITLE
Sorting collections in button operations

### ISSUE THREAD

**Issue by larkob** [ArnoldSmith86/virtualtabletop#257]
Currently, the order in which collections are processed is unclear (possibly based on the widget's creation order). However, when using the _count/limit_ or _aggregation_ parameter in operations, it is important to have a specific order in the collection.

My idea is to use a similar format to applyVariables, by which we could provide an array of keys to sort by, as well as a flag to determine whether sorting is ascending (default) or not.
```
{
  "func": "GET",
  "property": "id",
  "aggregation": "first",
  "collection": "myCollectionName",
  "applySorting": [
    {
      "sortBy": "z",
      "asc": true
    }
  ],
  "variable": "myVariable"
}
```

**Comment by larkob** [comment]
Alternatively, the sorting could be applied on the level of the routine itself, so you don't have to apply sorting time and time again for each operation:
```
{
  "type": "button",
  "text": "Small Board Offscreen",
  "clickRoutine": [{
     "func": "GET",
     "property": "id",
     "aggregation": "first",
     "collection": "myCollectionName",
     "variable": "myVariable"
   }],
  "sortOrder": [{
     "sortBy": "z",
     "asc": true
  }],
  "x": 758,
  "y": 721,
  "z": 11,
  "id": "2zye",
  "layer": 1
}
```

**Comment by robartsd** [comment]
I would sort the collection itself (probably in the SELECT func, possibly in a new func specifically for sorting collections). Sort the collection in the order you need it prior to using the collection in the func that requires the sort.

**Comment by RaphaelAlvez** [comment]
I agree that a function seems to fit better in this context

**Comment by larkob** [comment]
In SELECT it would be something like this:

```
{
  "func": "SELECT",
  "source": "all",
  "property": "width",
  "relation": ">=",
  "value": 50,
  "max": 5,
  "mode": "set",
  "collection": "myCollectionName",
  "sortOrder": [{
     "sortBy": "z",
     "asc": true
  }]
}
```

We could also use "-" as a prefix to indicate descending order, so it could be simplified to:
```
{
  "func": "SELECT",
  "source": "all",
  "property": "width",
  "relation": ">=",
  "value": 50,
  "max": 5,
  "mode": "set",
  "collection": "myCollectionName",
  "sortOrder": [ "-z"]
}
```

**Comment by larkob** [comment]
When used with mode "add", should the sorting be applied to the resulting collection or to selected widgets prior to adding them? I think it should be applied to the resulting collection. In the odd case that you wouldn't want it this way, you could just use two SELECTs, with the first applying the sorting on a new collection and the second adding it to the existing collection.

**Comment by larkob** [comment]
As there is no other function than SELECT that could change a collection, I don't the see the need to make the sorting a standalone operation. It would also be confusing as we already have a SORT operation.

Alternatively, we could add a "collection" parameter to SORT, so you can either sort widgets in a holder or widgets in a collection. However, for holders, the Sorting affects the "z"-parameter, so it's a bit different.

**Comment by larkob** [comment]
I no longer see the need for sort options in every button operation. Sorting should be taken care of with a SELECT operation.
