### ISSUE TITLE
COMPUTE is missing random

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#270]
There is no way to set a random value to a variable. (or at least I couldn't find it)

**Comment by rogerl50** [comment]
There is a separate `RANDOM` function.

**Comment by RaphaelAlvez** [comment]
> There is a separate `RANDOM` function.

I did in fact forget about that.

Maybe this issue is still relevant since RANDOM only returns intergers

**Comment by rogerl50** [comment]
Why not remove the existing `RANDOM` function and put in a `COMPUTE` function instead? It would require a fileupdater change, but would be more consistent.
