### ISSUE TITLE
Give INPUT Go button on mobile devices functionality

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#271]
On the INPUT screen the Go button on mobile devices does nothing, which might be confusing for some users.  The Go button on the screen works fine though. When a mobile user clicks in a text box, or a number box to enter text or a number, a Go button will appear on their device by the keypad or keyboard.  I assume this works like an enter key because hitting enter while in the number or text box also does nothing.  It might be a nice feature if that would work the same as clicking on Go, or since INPUT sometimes accepts multiple types of input, it might be better if it worked like a tab so they could tab through the screen.

![Mobile](https://user-images.githubusercontent.com/78324099/111058301-4f266380-8453-11eb-8855-6b664cbc193c.jpg)

**Comment by larkob** [comment]
@bjalder26 I don't have an Android device, so I cannot test this. Could you please test if this is fixed on http://212.47.248.129:3273/pr-test

**Comment by robartsd** [comment]
On my Android (7.1.1) device, there was no Go button on the keyboard. The next field button worked to advance the fields, then dismissed the overlay after the last field. I'm not certain what the overlay returned. The overlay messed up the room boundaries.
