### ISSUE TITLE
CLONE and DELETE need to tell holders what they are doing

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#278]
CLONE and DELETE have a problem in that when cloning or deleting widgets, they are created or deleted without letting the holder know, so that the actual count of widgets in the holder differs from what the holder reports. Thus for example suppose there is one widget in the holder (say, a poker chip that you want 8 of because someone bought). You clone 8 of them, but when you try to move the 8 clones out of the holder, the holder says "wait, I only have one widget here", and only allows a move of one. (Note that selecting the clones is not the issue; that can be done using the `clonedFrom` property.)

So I think what needs to be done is that if cards are being created or removed, one must call moveToHolder for each one; also, moveToHolder needs to be able to deal with the possibility that the holder being moved to is null in the case of deletion. Is this correct, and does it apply only to cards? If so, what is the correct check to perform in the clone and delete code to make this happen?

**Comment by robartsd** [comment]
Looks like all widgets (not just holders) have a children property that needs to be updated. `DELETE` should cause each widget's `applyRemove()` method to run which should handle removing the widgets from the parent by calling the parent's `applyChildRemove()` method. It looks like `CLONE` needs to cause the parent's `applyChildAdd()` method to run.

**Comment by robartsd** [comment]
`CLONE` and `DELETE` appear to be using `addWidgetLocal()` and `removeWidgetLocal()` from editmode.js. `removeWidgetLocal()` appears to take care of setting the `parent` and `deck` of the widget to `null` before removing the widget. Looks like the only issue might be that `addWidgetLocal()` might not handle creating a widget that has a parent property at time of creation properly.

**Comment by rogerl50** [comment]
I think I'm out of my depth here, but I don't think that simply clearing the `parent` and `deck` will do the trick. The `pile` code has routines (`applyChildAdd` and `applyChildRemove`) that increment and decrement the handle on the pile. So I do think those need to be called directly. But I'm not sure how, as the pile gets (magically, apparently, since I can't figure out how) created when the second card is added to the holder.

**Comment by rogerl50** [comment]
Looks like Arnold has taken this one, which is good. After some investigation, it seems to me that `CLONE` might need to call `moveToHolder` if the owner of the cloned widget is either a pile or a holder.
