### ISSUE TITLE
Cards do not refresh when new text is SET through a button push

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#287]
Pushing a button can set new text on a card, however, the text is not visible until the web browser is refreshed.  In the example below text from a label is SET on the upward face of the card at the top of the pile in the holder.  However, you cannot see the new text until refreshing your browser.

https://virtualtabletop.io/qi7g

**Comment by robartsd** [comment]
The button is setting a property of the card, but the code that creates the card faces does not redraw the card due to changes in a dynamic property. Each browser with the room open needs to be refreshed to see the changes.
