### ISSUE TITLE
Easier link to Ghetto

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#29]
Currently, to get to Ghetto from a table you must enter edit mode, click on some widget, click again to edit the JSON, then click on the "Advanced Editor" link. I don't think Ghetto should be accessible at the top level, but it would be nice if, whenever you entered edit mode, a new icon appeared on the left-hand icon bar giving you direct access.

Also, it may be too late, but perhaps a different name should be chosen for that editor.

**Comment by ArnoldSmith86** [comment]
Yeah, I agree. I just don't know if it's bug-free already to make it more prominent.

And yes, we should probably change the name and make it a proper part of the project.

**Comment by robartsd** [comment]
I'd like a context menu on the edit room button providing the option to go directly to the advanced editor. And if we feel it is ready to be that prominent just start referring to it as the "advanced editor".

**Comment by robartsd** [comment]
With #176 I'm not sure I care about this one anymore.

**Comment by ArnoldSmith86** [comment]
I'll close this one as well. While I still agree that it's not ideal right now, I believe the proper solution is to deprecate Ghetto and add all its features to the JSON editor.
