### ISSUE TITLE
Access to tutorials and Wiki should be easier

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#30]
There should be icons in the main icon bar to get to the tutorials and to the wiki, which should both be hosted outside of GitHub.

**Comment by larkob** [comment]
@rogerl50 Any reason why they shouldn't be hosted in github?

**Comment by rogerl50** [comment]
All I meant was that github shouldn't be the *only* place you can find them. "Normal" people just going to virtualtabletop.io have essentially zero chance of finding them unless there is at least a link there.

**Comment by ArnoldSmith86** [comment]
Did you not see the link above the JSON box or are you saying it should be easier?

**Comment by robartsd** [comment]
If we add a context menu to the edit button to make the advanced editor easier to open, perhaps links to reference material would also belong in the edit button context menu.

**Comment by bjalder26** [comment]
> There should be icons in the main icon bar to get to the tutorials and to the wiki, which should both be hosted outside of GitHub.

Is this resolved?  Does it need clarification?

**Comment by 96LawDawg** [comment]
From my perspective, the tutorial thing is solved at least for now as they have been moved to the public library.  The wiki part of it was not done in the way Roger asked, but there is a substantially revised About page (i in a circle icon) that has a link to the wiki (and discord).  I don't see a reason to host the wiki outside of GitHub as it acts like a wiki should.

I would close this.

**Comment by bjalder26** [comment]
I think an overlay that provided an iframe showing the wiki could be really helpful.  However, on phones we already have all the icons that can fit on the left side of the screen.  So perhaps the about page could be supplemented to have an iframe to the wiki, or perhaps the about info could be moved to the wiki and contained in the iframe.

**Comment by rogerl50** [comment]
Largely overtaken by events, closing.
