### ISSUE TITLE
SOUNDS

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#301]
I don't know if this is unrealistic or not, but being able to insert sounds would be really cool.

**Comment by ArnoldSmith86** [comment]
Shouldn't be too hard. We can provide a clickRoutine operation that plays a sound and in the near future those routines can be triggered by anything.

I'm not sure how I feel about it as a user though. Maybe sounds should then be disabled by default and can be enabled in the toolbar?

**Comment by Ingegneus** [comment]
I am working on a public library version of Halli Galli and a ringing sound for the bell would be very cool. A mute button should definitely be an option.

**Comment by bjalder26** [comment]
> Shouldn't be too hard. We can provide a clickRoutine operation that plays a sound and in the near future those routines can be triggered by anything.
> 
> I'm not sure how I feel about it as a user though. Maybe sounds should then be disabled by default and can be enabled in the toolbar?

After thinking about this for a bit. It seems to me that we tend to give control to the game maker.  So perhaps there should be a volume setting for the game maker to set, then the game-maker could provide a slider widget (which we could have readily available) to control volume through a variable that is gotten from a property of the widget.  Ultimately the player has control of volume regardless using their own volume controls.
