### ISSUE TITLE
Hotkeys for room state copy and paste

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#302]
While developing I have to copy test cases from PR test servers to local dev servers all the time. It would be really nice if there were JSON editor commands (or global ones) that use the `/state` API to copy a room state without having to save it as a game and manually downloading it.

**Comment by robartsd** [comment]
So you're proposing to add shortcuts that would copy/paste the state as JSON using the system clipboard?

**Comment by ArnoldSmith86** [comment]
Well, no, I would copy the `/state` URL for the room to the system clipboard and the the paste would fetch the state from there.
