### ISSUE TITLE
Enlarged card view flickers while dragging

### ISSUE THREAD

**Issue by larkob** [ArnoldSmith86/virtualtabletop#31]
There's a minor issue with the enlarged view of the card. When you drag and hold a card for a while (to give time for the enlarged view to appear), the enlarged view "blinks" until the card movement is stopped. It'd be better if the enlarged view is disabled while dragging a card.

**Comment by ArnoldSmith86** [comment]
I still can't reproduce this. What are you using (OS, Browser, Room)?

**Comment by larkob** [comment]
Windows, Chrome and FF in https://virtualtabletop.io/stlj (Reward). To reproduce: Drag a card and hold onto it. Then drag it around fast enough that the mouse cursor temporarily leaves the card itself - this produces the flickering.

**Comment by bjalder26** [comment]
For me, (windows 10, brave browser) the enlarged view disappears when I release the mouse click after moving a card.  Then to make it reappear again I need to move my mouse and mouse-over it again.

**Comment by bjalder26** [comment]
Enlarge could be 'turned on' by mouse enter and then 'turned off' by mouseleave.  However, mousemove or mousedown could deactivate the effect of mouseleave, in which case, the effect could be turned off by mouseup.

That way enlarged would just remain on regardless of whether or not the mouse cursor moved off of the widget.
