### ISSUE TITLE
integrate button debugging into the JSON editor

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#313]
I would like to introduce a command that clicks the button you're currently editing with `debug` temporarily set to `true`. That in itself would be very easy.

It would be very cool though if the debug output was easier to traverse. Some ideas I had (which I don't like enough yet):

- Only display debug output for the operation at your text cursor of the last button run. So you could move the text cursor up and down to see the different steps.
- Display the debug output directly in the JSON as properties of the button operations. They would use a different color or whatever. This doesn't work for the current debug output though that is way too verbose. But it could just show changes to variables and collections.

Any ideas for this?

**Comment by rogerl50** [comment]
Is it possible to open the debug output in a separate browser tab?
