### ISSUE TITLE
JSON editor ray tracing doesn't work if width or height are strings

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#319]
The selection buttons F1-F12 show widgets with strings for `width` or `height` in places where they aren't.

**Comment by robartsd** [comment]
I didn't realize that width and height properties could take anything other than a number in room pixel units.

**Comment by ArnoldSmith86** [comment]
Me neither but a numeric string is no problem and somebody used that in a PR test room.
