### ISSUE TITLE
New public library versions do not get applied into existing rooms

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#326]
If a game room has version 1.3 of a game and the public library updates to version 1.4, players will still only see version 1.3 unless they remove the old version and add a new one from the updated library.

**Comment by robartsd** [comment]
I wouldn't expect the active setup to be upgraded, but I do expect a variant with an update link to be up-to-date when loaded from the game menu. Is this not happening?

**Comment by 96LawDawg** [comment]
No.  Go to [https://virtualtabletop.io/Tutorials](https://virtualtabletop.io/Tutorials).  Click on the Functions - GET tutorial, second variant (aggregation: sum).  There are no spinners in the bottom left corner.  That is the version of the tutorial I loaded a few months ago for that room.  Compare that to [https://virtualtabletop.io/LawDawg](https://virtualtabletop.io/LawDawg) where the version of the tutorial was updated in the last round of updates.  That version was loaded from the most current public library.

**Comment by robartsd** [comment]
Those variants no longer have an update link which is why they are not updating.

**Comment by ArnoldSmith86** [comment]
Also see #389. I'm leaving this open for now because of the discussion.

**Comment by 96LawDawg** [comment]
I can’t speak to the larger issue, but I know why the tutorials room was not updating. I had loaded those files, or some of them anyway, from a vtt and not the library. The reason is I post files in there when they are done and the library gets updated days later. I fixed that for existing tutorials in that room and will try to keep it current. But if there is still a bigger problem in this area then being current won’t matter until that is fixed.

**Comment by ArnoldSmith86** [comment]
It should all work as expected until you _add_ variants or _remove_ variants.

**Comment by 96LawDawg** [comment]
> I can’t speak to the larger issue, but I know why the tutorials room was not updating. I had loaded those files, or some of them anyway, from a vtt and not the library. The reason is I post files in there when they are done and the library gets updated days later. I fixed that for existing tutorials in that room and will try to keep it current. But if there is still a bigger problem in this area then being current won’t matter until that is fixed.

No matter what I seem to do, every time a tutorial is modified, I have to load it again from the public library.  The update link thing seems horribly broken.  Or I'm missing something.  Either is possible.
