### ISSUE TITLE
Zero points for x and y don't appear to be consistent

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#337]
I'm getting some weird results for x and y.  It seems to depend (at least somewhat) on whether or not I start moving the card from the negative or positive direction.  When I move something from the negative direction it seems to reach x=0 or y=0 while still being about 1 or 2 pixels in the negative direction.  I know this is a really tiny issue, but I thought I should bring it up anyway.

![image](https://user-images.githubusercontent.com/78324099/113472420-bae36700-9428-11eb-9efa-d6ba5cc06d65.png)

**Comment by bjalder26** [comment]
I am not trying to promote this tiny issue, but I had an idea to test it out (two cards & buttons to move them).  After a little testing it appears that only the 0,0 (which I now realize is null, null) is inconsistent depending on what side the card approaches from (and this even includes when it is moved via a button push).  

Basically moving from the right (positive) to the left it goes like this 2, 1, 1 (though it will show nothing for the x), -1 .
Moving from left (negative) to the right it goes like this -2, -1, -1 (though it will nothing for the y), 1

![image](https://user-images.githubusercontent.com/78324099/114220464-a96ef300-9931-11eb-89fa-584a1c337947.png)

Also if I put something in y=0 (really null) and try to move it, in the x direction movement it glitches at and it just stops moving (in Ghetto editor it still appears to move).

When I placed it at 0,0 (really null, null) and tried to move it to the left:
![image](https://user-images.githubusercontent.com/78324099/114221752-526a1d80-9933-11eb-9071-2823076a3303.png)

When I placed it at a negative x and y=0 (really y=null) and tried to move it to the right)
![image](https://user-images.githubusercontent.com/78324099/114221908-88a79d00-9933-11eb-986d-0439ea14e0e4.png)

The same thing happens when moved the cards to x=0 (really x=null), meaning they couldn't be moved in the x direction with a button press incrementing the x property.  
![image](https://user-images.githubusercontent.com/78324099/114225899-8562e000-9938-11eb-98c9-1d298282ca63.png)

Even more interesting is when something has a null value as x or y and you refresh the browser, then it goes to the 0,0 of the room, despite its other x or y value (in Ghetto it will still appear to be in the "right" place).

![image](https://user-images.githubusercontent.com/78324099/114226799-af68d200-9939-11eb-85c6-705b15d6e03e.png)

I think 96LawDawg may have been correct in linking this to the Rummy Tiles issue, because when I set onEntry x=0 y=0 to the holder for that game the problem seemed to go away.  So, the Rummy Tiles issue may be an x=null, y=null issue.

**Comment by bjalder26** [comment]
Upon more testing, this does not happen with basic widgets.  It appears to be a card issue alone.

**Comment by ArnoldSmith86** [comment]
That info probably helps a lot for finding the issue.

**Comment by robartsd** [comment]
Not sure if this is part of the problem here, but I notice that `statemanaged.set` checks values against `this.defaults` to see if the value needs to be retained; however, this might not be the value that `getDefaultValue` returns if the deck provides a default value for the card type (or similarly a basic widget getting a property from a face).

**Comment by ArnoldSmith86** [comment]
You have this in your deck:

```
  "cardTypes": {
    "p1a6": {
      "x": "",
      "y": "",
      "z": ""
    }
  }
```

So you told the system that your default x/y/z is an empty string. When a coordinate reaches `0`, it looks at the defaults of widget type `card` and since it's `0`, it removes the property from the card. As soon as it is removed from the card, it uses the value from the `cardTypes`. And an empty string leads to something like `translate(px, 4px)` which breaks.

Technically it maybe shouldn't remove the property when it is `0` because you changed its default but I'm not sure if we need to change this.

In any case, please re-test with those three lines removed.

**Comment by bjalder26** [comment]
> You have this in your deck:
> 
> ```
>   "cardTypes": {
>     "p1a6": {
>       "x": "",
>       "y": "",
>       "z": ""
>     }
>   }
> ```
> 
> So you told the system that your default x/y/z is an empty string. When a coordinate reaches `0`, it looks at the defaults of widget type `card` and since it's `0`, it removes the property from the card. As soon as it is removed from the card, it uses the value from the `cardTypes`. And an empty string leads to something like `translate(px, 4px)` which breaks.
> 
> Technically it maybe shouldn't remove the property when it is `0` because you changed its default but I'm not sure if we need to change this.
> 
> In any case, please re-test with those three lines removed.

Funny, we noticed yesterday that bit wrecks piles as well, so I deleted them.  However, if I create new cards, they will have the same issue because they are created with the same empty strings for x and y.  Changing it in cardDefaults didn't change anything.  However, entering ones in the Edit Widget screen for x and y fixed the issue.  This seems like it is limited to cards with an x or y dynamic property where no number has been entered in the Edit Widget screen.  

Also, we have actually now moved on to using a basic widget for measurements anyway.  I would probably close this issue.

**Comment by ArnoldSmith86** [comment]
It should be fixed with the PR #436 either way.

**Comment by robartsd** [comment]
> However, if I create new cards, they will have the same issue because they are created with the same empty strings for x and y.

What tool is adding these properties to cardTypes by default?

**Comment by robartsd** [comment]
> JSON editor does that. Maybe it should get the default value?

Why is it adding the property at all? Shouldn't those properties default to the widget default instead of being defined in cardTypes?
