### ISSUE TITLE
Moving Walls: game pieces get lost

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#340]
If you slide a tile with a game piece off the board, the game piece does not reappear on the opposite side of the board.

The reason is that holder `tempHiddenPile` does not have a `dropTarget` set that would enable `MOVE` to move the game pieces out of it.

_Edit: Should have added that I'll fix this but there's an update coming for the game anyway._

**Comment by bjalder26** [comment]
This should be closed due to PR #636 right?
