### ISSUE TITLE
Decimals without leading zeros are not treated as numbers

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#345]
The COMPUTE function treats ".2" as a text string and treats "0.2" (or any other number like 17.2) as a number.  So adding ".2" and ".2" gives you a concatenated value of ".2.2" rather than ".4."  I guess it is possible that some people would want a string to start with a decimal, but it seems like this should be treated as a number.

**Comment by RaphaelAlvez** [comment]
I believe that comes directly from JS and it's not really a bug. Maybe adding .2 to 0 will solve you problem

**Comment by 96LawDawg** [comment]
I tried that and tried concatenating "0" and ".2."  Still ended up with a string.  You may be right that this is a JS thing, but in #26 ArnoldSmith86 was able to create a work around for numbers like 17.2 which were a problem originally.  Not saying it is a bug.  And I have a workaround (not an ideal solution) for what I need.  Just putting this out there for consideration.

**Comment by rogerl50** [comment]
I've run into this problem recently as well; see my discussion with Jan on #help, 4/2. Also, the following code:
```
  "clickRoutine": [
    {
      "func": "COMPUTE",
      "operation": "concat",
      "operand1": "2",
      "operand2": "1"
    }
  ],
```
generates `Exception: TypeError: a[e] is not a function`, and of course using `+` instead gives 3, not 21.

```
{
  "func": "COMPUTE",
  "operation": "concat",
  "operand1": "2",
  "operand2": ".00",
}
```
gives the same error, while
```
{
  "func": "COMPUTE",
  "operation": "+",
  "operand1": "2",
  "operand2": ".00",
}
```
gives `2.00`. I think all of this is just passed directly to JS, and it does what it does. I don't understand, though, why `concat` fails in the last example while `+` succeeds.

**Comment by rogerl50** [comment]
> I tried that and tried concatenating "0" and ".2." Still ended up with a string. You may be right that this is a JS thing, but in #26 ArnoldSmith86 was able to create a work around for numbers like 17.2 which were a problem originally. Not saying it is a bug. And I have a workaround (not an ideal solution) for what I need. Just putting this out there for consideration.

At the very least, we need to understand exactly how various numeric strings are treated in both `concat` and `+`, and document it.

**Comment by larkob** [comment]
COMPUTE is implemented in a way where any string that looks like a number (i.e. contains only numbers and dots, and perhaps a +/- at the beginning) is treated as a number. In your example, `concat` throws an error because it expects a string, but the "2" is converted to a number beforehand. This conversion helps beginners who may not understand the difference between strings and numbers. Obviously, you could just use numbers instead of numeric strings:

```
    {
      "func": "COMPUTE",
      "operation": "+",
      "operand1": 2,
      "operand2": 0.01
    }
```

The reason a decimal below 1 requires a leading 0 is that the JSON.parse() function throws an error if it's missing, so I don't think we can something about that.

I'm not sure what you're trying to accomplish, but if you want to work with numbers with a fixed amount of decimal points, we could simply add the appropriate functions to COMPUTE, like [toFixed](https://www.w3schools.com/jsref/jsref_tofixed.asp) and [parseFloat](https://www.w3schools.com/jsref/jsref_parsefloat.asp).

**Comment by rogerl50** [comment]
> I'm not sure what you're trying to accomplish, but if you want to work with numbers with a fixed amount of decimal points, we could simply add the appropriate functions to COMPUTE, like [toFixed](https://www.w3schools.com/jsref/jsref_tofixed.asp) and [parseFloat](https://www.w3schools.com/jsref/jsref_parsefloat.asp).

What I was trying to do was to divide an integer by 100, giving a string with precisely two digits after the decimal point. I eventually accomplished what I wanted, but it was not particularly easy.

**Comment by 96LawDawg** [comment]
> I'm not sure what you're trying to accomplish, but if you want to work with numbers with a fixed amount of decimal points, we could simply add the appropriate functions to COMPUTE, like [toFixed](https://www.w3schools.com/jsref/jsref_tofixed.asp) and [parseFloat](https://www.w3schools.com/jsref/jsref_parsefloat.asp).

As for me, I have an entry form where a user types information.  Sometimes the info might be 0.2.  If they type .2 instead, there is an error.  I was trying to prevent that.  I couldn't find a way, so I just noted the problem on the form and said you have to use a leading zero.

**Comment by larkob** [comment]
Alright, both cases can be fixed by using the functions I mentioned. I will add `toFixed` and `parseFloat` to COMPUTE to address this issue.

**Comment by robartsd** [comment]
While I'm not sure that the automatic conversion is something we _should_ do for literals in the game JSON, I think it is something we need for processing player submitted data. Player submitted data comes from editing the text of a label widget or responding to INPUT functions in routines. We could consider setting the type of the input at the time of input, but I don't have any idea on how we could automatically convert existing games that depend on the automatic conversion.

I think we should use `parseFloat` to do any automatic string to number conversion; certainly if we expect "0.2" to automatically be treated as 0.2, we should also expect ".2" to be automatically treated as 0.2. I also think we should avoid the conversion if the operation requested expects a string (possibly automatically converting numbers to their JSON representation).
