### ISSUE TITLE
Button press font-size changes to objects in faceTemplate do not show without a browser refresh

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#359]
I created a button that will change the font-size in the CSS of objects in the faceTemplate of a deck of cards.  It also changes the font-size in the CSS of a label I use for text entry in order to edit the cards.  The font-size change shows immediately in the label but only shows after a broswer refresh for the cards.

Below is a room with an example.  The buttons that increment the font-size are black and in the lower right corner.

https://virtualtabletop.io/q6tu

**Comment by ArnoldSmith86** [comment]
BTW, you added `"css": "background-color: white"` to your deck which will only affect the little deck widget in edit mode.

You'll want to add an `object` of `type: image` to your `faceTemplate`.
