### ISSUE TITLE
thisButton and thisID are not reset in a CALL

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#360]
When one widget calls a routine in another widget, the `thisButton` collection and the `thisID` variable continue to refer to the (original) caller. This behavior should *probably* be changed.

Additionally, now that any widget can have a `clickRoutine`, the name of `thisButton` should perhaps be changed to `thisWidget`; however, this would require a fileUpdater change.

**Comment by ArnoldSmith86** [comment]
I agree that `thisID` and `thisButton` should point to the callee.

I also agree with renaming but later.
