### ISSUE TITLE
Edit widget for decks resets unupdated text when it uploads an image

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#367]
Edit widget for decks resets the boxes for text entry.  The easy workaround is to upload the image(s) first or update your text before adding images.  However, I thought this might not be operating as intended.

![image](https://user-images.githubusercontent.com/78324099/114139594-dd67fb00-98d4-11eb-9d27-791aedc61605.png)

This can also be tested out in this room: https://virtualtabletop.io/1re4

Note: It also resets changest to the card counts.

**Comment by 96LawDawg** [comment]
Superseded by new UI.
