### ISSUE TITLE
SORT with multiple parameters

### ISSUE THREAD

**Issue by larkob** [ArnoldSmith86/virtualtabletop#37]
SORT currently sorts by a single key and allows to reverse the sort direction. 
```
{
  "func": "SORT",
  "holder": "<holderID>",
  "key": "label",
  "reverse": true
}
```

I suggest to either improve SORT with multiple keys and directions or to create a MULTISORT operation like this:

```
{
  "func": "MULTISORT",
  "holder": "<holderID>",
  "sort": [{
     "key":"rank",
    "reverse": true
    },{
     "key":"suite",
    "reverse": true
    }]
}
```

**Comment by RaphaelAlvez** [comment]
If this goes with the new sorting Arnold added (I don't know where) then this would be a very good tool

**Comment by robartsd** [comment]
Since sort does not change the relative order of items with the same value for the sort key, multi key sort can be accomplished, but is a bit counter intuitive and unnecessarily sorts items multiple times.

**Comment by robartsd** [comment]
I propose that `SORT` be extended rather than make a new function. Allow both `key` and `reverse` to take arrays. The highest priority `key` would be the first element of the array. If the `reverse` array is longer than the `key` array then the extra elements are ignored. If the `reverse` array is shorter than the `key` array, then the last value for `reverse` is used for all remaining keys. Push a warning to `problems` if `reverse` is an array that does not match the length of the `key` array (but not if `reverse` is a single value).

**Comment by 96LawDawg** [comment]
So something like:

```JSON
{
      "func": "SORT",
      "holder": "hand",
      "key": [
        "key1",
        "key2",
        "key3" 
      ],
      "reverse": true
}
```
would first sort on key1, then on key2, then on key3 and all would be reversed.


And something like:

```JSON
{
      "func": "SORT",
      "holder": "hand",
      "key": [
        "key1",
        "key2",
        "key3" 
      ],
      "reverse": [
        true,
        false 
      ]
}
```

would sort by key1 with reverse, then by key2 (no reverse), then by key3 (no reverse).

**Comment by robartsd** [comment]
> would sort by key1 with reverse, then by key2 (no reverse), then by key3 (no reverse). I think that is clear enough. I like it.

Yes, but problems would get a warning about the length of the `reverse` array. To avoid the warning you'd need:
```json
{
      "func": "SORT",
      "holder": "hand",
      "key": [
        "key1",
        "key2",
        "key3" 
      ],
      "reverse": [
        true,
        false,
        false 
      ]
}
```

**Comment by robartsd** [comment]
`SORT` `key` expanded to provide similar functionality as requested here as `MULTISORT` `sort` in PR #1158. The idea for parallel arrays for `key` and `reverse` was dropped.
