### ISSUE TITLE
Different sized cards do not pile

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#370]
Not sure if this is a bug or a feature.  Not sure if it will matter after the pile update.  But when testing a different PR, I noticed that cards don't always stack/pile if they are different shapes.  For example, in [https://virtualtabletop.io/10g8](https://virtualtabletop.io/10g8) the Crafty/Patchwork cards only stack if (on Face 1), they are about the same size outside the holder.  But inside the holder, they pile no matter which face or size.

**Comment by ArnoldSmith86** [comment]
It's just really picky about the position. The top left corners have to align +/- 5px which is hard to do for transparent cards.

**Comment by 96LawDawg** [comment]
Sounds good.  I think that now that you say that, this has come up somewhere before.  Closing the issue.
