### ISSUE TITLE
Edit widgets sorts numerical IDs that do not start with zero

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#374]
In Edit widget for cards, the cards are sorted by ID (cardType) number (left to right) when there are numerical values that do not start with zero.  If they start with zero or contain a letter, then they are not sorted.  They just appear in the order they are entered/updated, or the order in the JSON.  I suspect when it has a leading zero it is not interpreted as a number.  The numbered (sorted) IDs always show up before the ones that are not sorted.

![image](https://user-images.githubusercontent.com/78324099/114250997-249dcc80-9965-11eb-9efe-3136fe54a929.png)

Personally, I do not see a need for sorting them in Edit widgets at all since that can be controlled by editing the JSON, but perhaps there is some use.

This issue can be avoided by starting every number with zero, not using numbers, or by adding a letter to every number.  Even adding a space after the number worked.

**Comment by 96LawDawg** [comment]
Similar to #473

**Comment by 96LawDawg** [comment]
Superseded by new UI
