### ISSUE TITLE
Add `all` aggregation mode to `GET`

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#381]
When given a collection, `GET` should have the ability to return an equal-sized collection that contains the property of each element of the source collection.

**Comment by larkob** [comment]
GET is not meant to return collections, it populates a variable. If you need a collection, SORT is probably the best candidate. What is the use case and the problem?

**Comment by rogerl50** [comment]
I have a set of widgets, call them owner1, owner2, owner3. Each of them has a child, say child1, child2, child3. Each child has  a true/false property foo. I want a collection containing exactly those owner widgets whose children have foo==true. Thus if only child1 has foo==true, the resulting collection should contain only owner1.

There was a discussion of this problem today in the #help channel.

**Comment by robartsd** [comment]
> GET is not meant to return collections, it populates a variable. If you need a collection, SORT is probably the best candidate. What is the use case and the problem?

Correct, it would not return a collection (which is an array of widgets) it would return an array of values from the properties of the widgets.

Roger's process would be something like:
SELECT property:foo relation:== value:true
GET property:parent mode:all
SELECT property:parent relation:in value:{parent}
