### ISSUE TITLE
Issues with DEBUG behavior

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#388]
The debug property on buttons does not behave exactly as one would like. Specifically, there are the following issues:

1. The only way to get debug information in a `CLICK`ed button is to set the debug flag in that button and in *no* others in its parent tree. I believe the reason is that `depth` is not reset to zero after exiting the `clickRoutine` processing for the clicked button, so that the parent processing never realizes that it should print debug information. It would be nice if clicking a button behaved, in terms of debug output, exactly like "CALLing" its `clickRoutine` would.

2. When doing a `CALL`, you get a nice message that the call is happening, and then output from the callee (if debug set set in the callee) is indented. But the debug output for the `CALL` function itself is printed *after* the call is complete. Doesn't look like this is easy to fix, but perhaps the `CALL` debug output could at least be preceded by a message saying something like "Exited the CALL, shown below".

3. If the main button does not have debug set, but the `CALL`ed button does, you will not see any debug output. This is because printing of debug output is governed by `this.debug` at the top level. Seems to me you need a static variable here to track debugging in callees, but I don't know how to do that.

As a side note, the third parameter to `setText` is a debug flag; this flag is not used in the subroutine, so perhaps the parameter should be removed.

**Comment by ArnoldSmith86** [comment]
Yeah, `debug` needs to catch up to all the changes we introduced in the last months. I was waiting for the `CALL` to be merged but one of my next todos is an overhaul of `debug`.

My main focus is to only have one line in the debug output per button operation with basic information about what the operation did and then you can get the details you see now when hovering over the lines. Right now everything is _way_ too long.

At the same time I will look at the problems you describe.

**Comment by rogerl50** [comment]
It would also be really nice if there were a way to copy the debug output to a clipboard so you could load it up into an editor on your machine to look at.

**Comment by ArnoldSmith86** [comment]
That would be nice for the current behavior. But I would prefer if it was functional enough so you wouldn't even want to do that.

**Comment by rogerl50** [comment]
While I'm complaining about DEBUG, one more thing. My old eyes have trouble with the (lack of) contrast due to the partial transparency on the DEBUG overlay.

**Comment by ArnoldSmith86** [comment]
Do you think it's reasonable to assume that `debug` is only used in conjunction with the JSON editor?

And would you still use the property `debug` if there was a shortcut in the editor to click the currently edited widget with `debug` temporarily enabled?

**Comment by robartsd** [comment]
> Do you think it's reasonable to assume that `debug` is only used in conjunction with the JSON editor?
> 
> And would you still use the property `debug` if there was a shortcut in the editor to click the currently edited widget with `debug` temporarily enabled?

This sounds reasonable to me.

It would be even nicer if the JSON editor could just provide access the debug information from the last time the routine was run (during the current client session). Then if you noticed something that didn't go as expected when testing, you could immediately open the JSON editor and start poking around in the debug information to try to figure out what went wrong.

**Comment by rogerl50** [comment]
> Do you think it's reasonable to assume that `debug` is only used in conjunction with the JSON editor?

I don't use the new JSON editor much; I find it easier to just type. So if you meant 'only in conjunction with the new JSON editor', then no, I don't think it's reasonable.

> And would you still use the property `debug` if there was a shortcut in the editor to click the currently edited widget with `debug` temporarily enabled?

Same comment, I think. But if there were a way to do that from the traditional editor, or from the game screen (i.e. not in edit mode), I'd be fine with that.

**Comment by ArnoldSmith86** [comment]
> I don't use the new JSON editor much; I find it easier to just type.

Where do you type then? The "old" JSON editor in edit mode? An external editor? I'm pretty curious why you prefer that.

**Comment by rogerl50** [comment]
Yes, the "old" edit mode editor, just typing raw JSON. I'm a good typist and find it annoying to keep switching contexts to either click on a button or figure out what control sequence I need to type to get the desired property in a widget when using the new editor.

**Comment by ArnoldSmith86** [comment]
But can't you just type in the new editor as well? Even without buttons/commands I would prefer the higher editor and syntax highlighting.

Not that I want to take away your editor, I'm just curious.

**Comment by rogerl50** [comment]
I guess I could. I'll try it. I also have trouble with some of the colors on the dark background.
