### ISSUE TITLE
Holders need parameter to stop widget movement

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#391]
Adding an issue based on suggestion by @ArnoldSmith86 arising from Quad Line.  In some situations, like the one in that game, it would be good to be able to prevent accidental (or intentional) realignment of widgets after being placed in the holder.  They should be able to be moved programmatically, but not by clicking and dragging.  I think it should be called something like "movableInHolder" and it would be either true or false (defaulting to true).  Unlike the other "movable" parameters, this one would be on the contents of (children of) a holder and not on a particular static widget.

It could be added to individual widgets, but that would be a lot more complicated to implement.  For example, in Quad Line, you would want the widgets movable from the main stack, but not once they were placed on the board.  So just adding "movableInHolder":"false" to the widget wouldn't work because it would lock down all movement of the widgets.  The parameter would have to specify which holder or holders it applied to and whether it was true or false.  That is probably still doable, but again, a lot more work and the first solution will solve the example use case.

**Comment by bjalder26** [comment]
How would this operate differently than putting "onEnter": {"movable": false} on the holders?  Is the point that some widgets would be movable in the holders and others would not?  Would this issue also be solved by making onEnter work like a clickRoutine that sets movable to false on specific widgets?  Just trying to wrap my head around this issue.

**Comment by 96LawDawg** [comment]
> How would this operate differently than putting "onEnter": {"movable": false} on the holders?

Ummm, that works.  Shame on me and @ArnoldSmith86.  I thought I had figured out the solution as part of the draft of #406 and I was coming back here to comment on that.  Then I saw your idea and tried it and it works.  There are things onEnter can't do.  But this is not one of those.  Good idea.

**Comment by ArnoldSmith86** [comment]
Well, it's not only about that. You can still drop the pieces at the bottom of the holder, pushing existing ones up. IMO there should be a way for offset holders to say "you can only interact with the top" like in normal holders.

**Comment by robartsd** [comment]
A potential workaround would use a separate holder to accept dropped widgets then move them using a enterRoutine.

**Comment by ArnoldSmith86** [comment]
> A potential workaround would use a separate holder to accept dropped widgets then move them using a enterRoutine.

Hmm, interesting. That should even work with `onEnter`.

**Comment by robartsd** [comment]
> > A potential workaround would use a separate holder to accept dropped widgets then move them using a enterRoutine.
> 
> Hmm, interesting. That should even work with `onEnter`.

Or make the holder dimensions such that the holder is only at the top of the stack and use dropOffset to position the first checker outside the holder with each subsequent checker closer to the holder using stackOffset. Revised QuadLine at https://virtualtabletop.io/1ywc

**Comment by 96LawDawg** [comment]
Great ideas.  And one using `onEnter` is available at http://212.47.248.129:3406/QuadLine3D (top row has the improvements).

**Comment by ArnoldSmith86** [comment]
I changed the third in the top row to:

```
  "onEnter": {
    "parent": "pin13b",
    "movable": false
  }
```

Works.

**Comment by 96LawDawg** [comment]
Sure, leave it to a programmer to improve a non-programmer's code.  Show off!

**Comment by ArnoldSmith86** [comment]
My point is: it should work without the PR.

I'm not sure if I like it in general though. In Connect Four or Chess there's always one point in the game where one player is telling the other one: "You don't want to make that move." and you undo it.

**Comment by 96LawDawg** [comment]
Undo is something I've been thinking about a lot lately.  There is one game in the public library with an undo button (Splendid).  It uses arrays to store what is happening and allows you to go back (not sure if you can go back more than one or not).  Depending on the game, that would be easy to implement, but for some games, not so much.  I've been thinking about whether the game code could help automate that (i.e., what was the state before the last button click, but excluding x,y coord changes probably).  Haven't figured it out enough to make it an issue yet.

**Comment by ArnoldSmith86** [comment]
Hmm, interesting. I was thinking about adding "undo" to the JSON editor but maybe that's the wrong layer. Adding it to the entire room state would solve it for the editor _and_ the game.

I wanted to build a kind of "replay viewer" anyway so we can make traces of the room state, mark erroneous behaviour and then click through the game state changes to look at the deltas.

That might all be the same feature. Gotta give that some thought..

**Comment by RaphaelAlvez** [comment]
@ArnoldSmith86 and @96LawDawg do you still want this? If so please add this issue to pick and code

**Comment by 96LawDawg** [comment]
I think this has been resolved (except for the last idea about undoing things, which is unrelated).  If @ArnoldSmith86 agrees, he can close it.
