### ISSUE TITLE
Passing variables to CALLs

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#402]
The argument to a CALL must either be a literal or else passed as the contents of a variable whose name is agreed upon between caller and callee. The fact that there is no convenient way of getting a literal into a variable makes this difficult in the case where you wish to pass one of two literals depending on the results of an IF (say).

The best solution to this would be to allow `applyVariables` in the `arguments` list to a CALL. An alternative, which might be useful elsewhere, would be to provide a good way to get a literal value into a variable (or more generally moving the contents of a variable into a different variable).

**Comment by larkob** [comment]
PR #307 is aiming to allow for an easier way to set variables
