### ISSUE TITLE
"SET" cannot change widget ID

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#415]
I tried creating a new ID using SET.  It created really strange results that differed depending on whether I was looking at it in the old edit mode or the new JSON editor.  Demo room in https://virtualtabletop.io/nmhb.  Click on the clone button to create 2 clones and then the clean up button to try to change IDs and view the results.

**Comment by rogerl50** [comment]
Do you have a vtt file for this room, or can you tell me how to reset it?

**Comment by rogerl50** [comment]
This can be reproduced simply by having a button change the `id` of any widget using `SET`. The `SET` code changes `state.id`, which then confuses `sendPropertyUpdate`.
