### ISSUE TITLE
"SELECT" returns empty collection for non-default null parameters

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#416]
I'm trying to limit a selection by a parameter that does not existing by comparing it to null.  But that returns an empty collection.  Here's the details.  I have an original widget that is being cloned.  I need to select the original widget, but I cannot use IDs and because I can't use IDs I can't use "clonedFrom" setting the value to a known ID.  The ONLY difference between the two widgets will be the ID and the "clonedFrom" parameter (the original will not have it and the clones will have it).  So I can select them both based on another custom key ("vttChatID" in my example), but how do I distinguish between them and select the original in one grouping and the clone in another?  Here is what I've tried.  I've also tried "" and 0 in place of null.  But every time, the debug shows an empty collection.  See demo room at https://virtualtabletop.io/gsfc.  Should select the red checker, but debug shows an empty collection.

```{
      "func": "SELECT",
      "property": "vttChatID",
      "value": "mainChat"
    },
    {
      "func": "SELECT",
      "source": "DEFAULT",
      "property": "clonedFrom",
      "value": null
    },```

**Comment by robartsd** [comment]
Turns out only default properties could be `null`, setting non-default properties to `null` erases them so trying to retrieve those properties returned `undefined`.
