### ISSUE TITLE
Add support for video formats

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#418]
Since the timer won't be ideal for making animations, it would be pretty cool if we could have the possiblity to upload mp4/webm/gif that get looped over and over, or that you can start stop with routines.

**Comment by robartsd** [comment]
I would expect animated images (GIF or SVG) to work currently, but have not tested.

**Comment by Ingegneus** [comment]
you are right. i thought that i had tested this and determined that it doesnt work but i was wrong. still the other features would be nice

**Comment by RaphaelAlvez** [comment]
@Ingegneus  should this be closed?

**Comment by Ingegneus** [comment]
I would still like having the possiblility to upload other video formats and play/pause feature through routines or something

**Comment by 96LawDawg** [comment]
Will be closed by #1407, but I can't seem to get the issues to link.
