### ISSUE TITLE
full control over css for all widgets

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#419]
I experience this mostly wiht text. I would like to do something with text in a label, but it won't work in a labe but instead in a button or in a basic widget, which forces me to stack different widgets to get the what i want.

**Comment by robartsd** [comment]
Yes, styling is a challenge for widgets that are more than one DOM element (lable is a textarea inside of the div that is the root of the widget).

**Comment by robartsd** [comment]
My preferred solution is #154

**Comment by ArnoldSmith86** [comment]
We already decided to implement #154 so I feel like this can be closed as a duplicate.
