### ISSUE TITLE
JSON editor changeRoutine & elseRoutine

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#420]
It seems to me that changeRoutine should produce  
"change routine": [],
 rather than
"changeRoutine": null,

Also, ELSE appears to be getting placed in the wrong spot.
  "clickRoutine": [
    {
      "func": "IF",
      "thenRoutine": [
        {
          "func": "CLICK",
          "elseRoutine": []
        }
      ]
    }
  ],

instead of
  "clickRoutine": [
    {
      "func": "IF",
      "thenRoutine": [
        {
          "func": "CLICK",
        
        }
      ],
      "elseRoutine": []
    }
  ],

So it appears it is getting placed inside a function of the THEN routine instead of after the THEN routine.

**Comment by RaphaelAlvez** [comment]
this should be addressed in the PR as the feature is not launched yet. 

I do agree with you about the Null problem. It is not that simple though as any property can be a routine and properties' default is null.
elseRoutine and thenRoutine are properties of the IF function.

**Comment by ArnoldSmith86** [comment]
There's a special case for `clickRoutine` in the code already (inserting `[]` instead of the default `null`). I just forgot to make it more general. Thanks for reporting.

Please report PR issues in the PR itself though because that's where the author will look for unaddressed problems.

> It is not that simple though as any property can be a routine and properties' default is null.

That's exactly why we enforce the suffix "Routine". :)

**Comment by bjalder26** [comment]
There is still a minor issue with the placement of the `elseRoutine`.

Once something is added to a `thenRoutine`, if the cursor is below the `thenRoutine` the `elseRoutine` will be placed inside of the `thenRoutine`.  The way to avoid this is to place the cursor above the `thenRoutine`, or add the `elseRoutine` before adding anything inside of the `thenRoutine`.
![image](https://user-images.githubusercontent.com/78324099/121385618-e2feb300-c90e-11eb-99be-36d4692c2782.png)

**Comment by 96LawDawg** [comment]
I don't remember what fixed this, but I don't think any of these things are happening any more.  @bjalder26 okay to close?

**Comment by bjalder26** [comment]
Resolved at some point.
