### ISSUE TITLE
Compatibility issues with PCIO

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#421]
I tried uploading a few games from PCIO into VTT (namely: One Deck Dungeon, Res Arcana, Call to Adventure from Reddit by Cobberhead851) and they all triggered an error: "TypeError: Cannot read property 'includeBorder' of undefined".

**Comment by RaphaelAlvez** [comment]
we should be addressing this problem starting this week. probably this will be done in more than one step where seat and timer will come later.

**Comment by 96LawDawg** [comment]
This must have been fixed at some point in various PCIO compatibility updates.  I tested Res Arcana and it worked fine.
