### ISSUE TITLE
Cannot "play" an empty room

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#432]
After #422 , I was playing with it so I could update the newcomer's FAQ.  I saved an empty room from the new save button, but when pressing on play, the screen just flashes.  You can get into the room by clicking on one of the main blue and white icon buttons, but that is not obvious.  After adding a widget to the room, play worked normally.  When I deleted the widget from the room and it was again empty, pressing play again would not work.

**Comment by RaphaelAlvez** [comment]
Well, first of I want to point out that this points out we did a bad job reviewing here since we found the problem 5 min after merging. We need to keep in mind we are not yet on point with tests. I'll put this on the next meeting topics.
I don't really see how adding a button caused this. So I don't really know if this bug existed before the merging.

**Comment by ArnoldSmith86** [comment]
It's the feature that opens the game list when the room is empty. Might need a tweak but loading an empty game isn't exactly a representing use case.

**Comment by 96LawDawg** [comment]
> I don't really see how adding a button caused this. So I don't really know if this bug existed before the merging.

It probably didn't.  That was probably already there just there was no easy way to create and save an empty room so it never got discovered.

**Comment by bjalder26** [comment]
I think what is happening is that it sends you back to the "Games" screen whenever you enter an empty room (or rather variant).

**Comment by robartsd** [comment]
Yes, I have an empty room variant saved in the main room I use for development. I "Play" that variant when I want to start with an empty room state. Hitting 'Esc' dismisses the overlay, but we should have it not pop back up in the first place.
