### ISSUE TITLE
getUniqueWidgetID is undefined

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#445]
It's in use in the JSON editor but not defined

**Comment by rogerl50** [comment]
Why is it not in scope? It is declared in global scope in editmode.js.

**Comment by ArnoldSmith86** [comment]
It's not. `generateUniqueWidgetID` is.

**Comment by rogerl50** [comment]
Ack. That's a simple typo. I'll do a PR.
