### ISSUE TITLE
'all' is just a default collection to SELECT

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#449]
'all' is an option is SELECT's 'source' but it is not a default collection available to other functions

**Comment by robartsd** [comment]
What do you want to do with literally every widget in the room?

**Comment by RaphaelAlvez** [comment]
Could be useful to GET and COUNT but you never know if anyone can come up with other uses.
Just added this issue because I saw the inconsistency.

**Comment by ArnoldSmith86** [comment]
I don't see any use for this either TBH.

**Comment by robartsd** [comment]
I think we should close this issue until someone can provide an actual use case.
