### ISSUE TITLE
JSON editor paste error

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#455]
Place two buttons on the table using the old editor. Get some text in your system paste buffer. In the JSON editor, click on the [] in the `clickRoutine` and paste. It works correctly. In the other button, add another property, preceded by a newline (this is important). For example, after `"y": <whatever>,` add `\n  "z": 25,`. Then click on the [] and paste. It will go in the wrong place. After some experimentation, just entering `"z":25` without the newline will not break the paste.

**Comment by bjalder26** [comment]
I am having trouble recreating this issue.  Is it still happening?

**Comment by rogerl50** [comment]
Not reproducible.
