### ISSUE TITLE
replacing an asset in cardDefaults in card doesn't work

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#458]

**Comment by robartsd** [comment]
Do you mean the card doesn't get redrawn immediately when the property changes in `cardDefaults`?

**Comment by ArnoldSmith86** [comment]
No. When you edit the card itself the cardDefaults from its deck get displayed in the widget and you can change them right there. But if you use the "upload a new asset" feature in there, it fails.

**Comment by robartsd** [comment]
Sorry, I overlooked the JSON editor tag.

**Comment by ArnoldSmith86** [comment]
Example:
[cinnamon-2022-09-15T075723+0200.webm](https://user-images.githubusercontent.com/73538315/190325743-1a6d9835-90be-44b5-8650-8078fff53d6e.webm)

**Comment by 96LawDawg** [comment]
At some point this was fixed.  The problem no longer exists.
