### ISSUE TITLE
[Feature Request] Ranking system for games library

### ISSUE THREAD

**Issue by AZMCode** [ArnoldSmith86/virtualtabletop#465]
Perhaps a system to vote for games could help to pick out interesting/high quality games to play. Perhaps even an account system to make sure the site isn't spammed by bots.

**Comment by RaphaelAlvez** [comment]
accounts are definitely not in our plans. We could think in a way to use other platforms to validate the vote maybe in the discord server or here in Github

**Comment by AZMCode** [comment]
Why are accounts being ruled out again?

**Comment by RaphaelAlvez** [comment]
> Why are accounts being ruled out again?

our plan at the moment is to not host any user data and keep with the share a link and play style. Your room name is your space so most of us has a private room and a room we use to share stuff

**Comment by robartsd** [comment]
I think we could think about something to track how much each public library gets played. I'm thinking just counting the active player hours with the public library game loaded in a room. It would mean we would have to define what it means to have a public library game loaded in the room and keep track of how many players are actively participating in the room.

Currently public library just provides a state to load into the room, then anyone in the room can change the state in any way - including completely changing the nature of the game. Would we want to deem the room no longer the public library game as soon as anyone makes a change in an edit mode?

**Comment by 96LawDawg** [comment]
We have implemented as much of this as we are ever likely going to do in the new UI.  You can now search by number of times starred or by popularity.
