### ISSUE TITLE
Unable to interact with the room

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#467]
I had this bug at least twice yesterday (Firefox on Linux):

I was unable to interact with anything in the room. It wouldn't show any movement in my own browser except for highlighting the holder I wanted to drag a child out of.

When I then moved one card onto another (without seeing it move), it formed a pile and suddenly all my changes to the room became visible (for me and other players).

I did use Ghetto before this happened (don't know if immediately before) the second time (don't remember the first time).

Please comment here if this happens to you. Preferably with more details. Of course it would be amazing if anyone finds out how to reproduce this.

**Comment by bjalder26** [comment]
I've done this like a dozen times when I mess up the JSON somehow.  I'm not sure if that was your issue, but for me it has been routines that were broken.

**Comment by bjalder26** [comment]
To me this sounds a lot like #27 and #439.

**Comment by robartsd** [comment]
> To me this sounds a lot like #27 and #439.

Certainly unrelated to #439.

**Comment by 96LawDawg** [comment]
Probably this can be closed.  @ArnoldSmith86?

**Comment by ArnoldSmith86** [comment]
At least I haven't seen it since then..
