### ISSUE TITLE
Shortcuts not working in JSON editor

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#468]
Idk why I never reported this, but since the editor was introduced the keyboard shortcuts never worked on my pc. When I try using them they always trigger the browser shortcuts and not the editor ones.

**Comment by ArnoldSmith86** [comment]
Yeah and it only got worse.

My plan is to try to use `TAB` instead of `CTRL`.

**Comment by robartsd** [comment]
Won't TAB immediately change keyboard focus?

**Comment by ArnoldSmith86** [comment]
I'm pretty sure you can prevent that.

**Comment by 96LawDawg** [comment]
Resolved by #616
