### ISSUE TITLE
duplicating just created widget is broken

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#470]
If you click `add` and `duplicate` right after each other in JSON editor, the result is something like this:

```JSON
{
  "type": "pkkm",
  "id": "###SELECT ME###"
}
```

**Comment by bjalder26** [comment]
Has this been fixed? I wasn't able to replicate the issue.

**Comment by rogerl50** [comment]
I can't duplicate this today, either.

**Comment by ArnoldSmith86** [comment]
I might have fixed this, yeah. Closing...
