### ISSUE TITLE
Cannot use colon symbol with dynamic expressions

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#471]
I am trying to use the new dynamic expressions to update css.  I want to say something like "var newCSS = 'background: white'".  However, the colon causes the output to be 1.  I tried do something like "var newCSS = 'background'" and then "var newCSS = ${newCSS} +':'" but that causes the same problem.

**Comment by 96LawDawg** [comment]
So I found something from the fileupdater on a similar piece of code.  It change the colon to the escape code \\u003a.  That is a workaround, but I hope that we can add the ability to use colons inside of single quotes when defining a variable.

**Comment by rogerl50** [comment]
I believe that the only unescaped characters allowed in a string are alphanumerics, underscore, and hyphen. But I'm not completely sure that's correct.

**Comment by ArnoldSmith86** [comment]
Not much more at least.

We can collect a few more characters though and allow them. CSS is a good use case where we might need some more.

**Comment by robartsd** [comment]
If I'm reading the code correctly, these are the only characters currently allowed unescaped in strings:  `A` to `Z`, `a` to `z`, `0` to `9`, ` ,`, `.`, `(`, `)`, ` `, `_`, `-`

I think these should also be allowed: `!`, `"`, `$`, `%`, `&`, `:`, `;`, `?`, `@`

Might also consider: `/`, `+`, `*`, `<`, `=`, `>`, `~`

**Comment by RaphaelAlvez** [comment]
definitely consider the last lines for tutorials

**Comment by ArnoldSmith86** [comment]
It's probably really easy to provide a regex range that includes all non-control ASCII characters. Something like `[ -&(-~]*`?

**Comment by robartsd** [comment]
> It's probably really easy to provide a regex range that includes all non-control ASCII characters. Something like `[ -&(-~]*`?
> 
> Seems to work fine:
> 
> ```
> > "askjdIAUSDH12893742$%&/()=.,#+*~h".match(/^[ -&(-~]*$/)
> < Array [ "askjdIAUSDH12893742$%&/()=.,#+*~h" ]
> ```

Should only need to be careful around the escape character `\` and the string terminator character `'`. Of course we're talking about a quoted string within a quoted string, so `"` needs special attention in the JSON too. 

Why not this to match string literals: `'((?:[^'\\\\]|\\\\u[0-9a-fA-F]{4})*)'`

I'm absolutely okay with needing to escape `\` as `\u005c` as keeping track of the levels of escaping makes my head hurt. I'm not even sure I got it right in my suggested regex.

**Comment by ArnoldSmith86** [comment]
No specific reason but I would prefer sticking to whitelists instead of blacklists. But you're right, `"` and `\` should be excluded.
