### ISSUE TITLE
Nice to have JSON Editor feature - dragging widget without parent change

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#472]
The edit mode, and the edit mode available in the JSON editor, have a "feature" that I wish I could turn on or off.  That is, when physically dragging an object around in the room, it would be nice if there was an option to keep it assigned as relative to the same parent.  The default behavior as it currently exists is fine.  But if there were a toggle somewhere that would let me move an object relative to its current parent, without changing parent as it moves around the board, that would be a nice feature.

**Comment by ArnoldSmith86** [comment]
I added a `fixedParent` property today (only locally on my machine so far) that prevents the `parent` to change whenever you drag a widget.

Would you want an _additional_ feature in the editor that basically does that "on demand"?

**Comment by 96LawDawg** [comment]
Not necessary.  Your solution is fine as I can toggle the property whenever I want.  Great minds think alike!

**Comment by rogerl50** [comment]
Perhaps related to issue #11

**Comment by RaphaelAlvez** [comment]
I still think that this would be useful for editing games. You would be able to manually place widget in relative position instead of having to type coords.

**Comment by ArnoldSmith86** [comment]
But don't you think #521 solves this?

**Comment by RaphaelAlvez** [comment]
> But don't you think #521 solves this?

So should I be using fixed parent for every composed widget?

**Comment by ArnoldSmith86** [comment]
I don't see why not if the `parent` is not supposed to change.
