### ISSUE TITLE
Sort and Reverse functions in array do not work with numbers

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#473]
When using `sort` and `reverse` in an array, numbers get treated like strings, so you get results like 1, 11, 13, 5, 7, 71.  Numbers should be treated as such in arrays.  It is possible to workaround this issue by using leading 0s, but if it is possible to find a JavaScript coding solution, then we should do so.

**Comment by 96LawDawg** [comment]
Similar to #374

**Comment by bjalder26** [comment]
Adding this in case it makes things easier.
https://raddevon.com/articles/sort-array-numbers-javascript/#:~:text=How%20do%20I%20sort%20an%20array%20of%20numbers,is%202.%20...%204%20Sorting%20Other%20Data.%20

**Comment by larkob** [comment]
I've added numericSort in #469  - not sure about `reverse`: isn't this simply reversing the order of elements, irrespective what type the elements have? If you wanted a numeric reverse sort, you could just first do a numericSort followed by a reverse.

**Comment by bjalder26** [comment]
> I've added numericSort in #469 - not sure about `reverse`: isn't this simply reversing the order of elements, irrespective what type the elements have? If you wanted a numeric reverse sort, you could just first do a numericSort followed by a reverse.

I made a button that does a numericSort, then uses reverse, and that process works as expected.
http://212.47.248.129:3469/Interitus

The JSON looked like this:
    "var s = ${array} numericSort",
    "var r = ${s} reverse"
