### ISSUE TITLE
JSON editor doesn't show buttons to add operations to thenRoutine

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#501]

**Comment by 96LawDawg** [comment]
Same for elseRoutine

**Comment by bjalder26** [comment]
Has this issue been resolved?

**Comment by rogerl50** [comment]
Does this issue still exist? I can't reproduce it, but there is not really a good description of what the issue is, so...

**Comment by ArnoldSmith86** [comment]
I'm pretty sure this problem was very obvious at the time. So if it is hard to reproduce, it's probably fixed.
