### ISSUE TITLE
JSON editor doesn't trigger an update on property change

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#503]
The following `clickRoutine`
```
"clickRoutine": [
    "var inner = []",
    "var inner.0 = ${PROPERTY text OF l1}",
    "var inner.1 = ${PROPERTY text OF l2}",
    "var list = ${PROPERTY list}",
    "var list = push ${inner}",
    {
      "func": "SET",
      "property": "list",
      "value": "${list}",
      "collection": "thisButton"
    }
  ],
"list": []
```
works properly to update the list, but the JSON editor does not show the change unless you Ctrl-click the button again. Note that if the `SET` is removed, the property itself is updated (though not displayed), so that the variable `list` must actually point to the property value, not to a copy of the property value.

**Comment by ArnoldSmith86** [comment]
This is fixed now, right?

**Comment by rogerl50** [comment]
> Right, Roger? 😄

Right. Sorry, missed this one.
