### ISSUE TITLE
Deal Buttons that use CSS transitions

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#508]
LawDawg and I have been experimenting with using the CSS transitions to deal cards, and I wanted to pass on some of the issues I ran into in case it is decided that something like this should be integrated into the javascript. 

Here is an example of how the effect appears. https://virtualtabletop.io/j1ej

These are the major steps I used to work around to an imperfect solution.  They illustrate some of the issues.

Step 1) change parent to the new holder and assign new x/y so that the card appears to remain in the same place (over the deck). This happens immediately, and is not 'seen' other than the card is now "over" the pile handle.

I use a timer and a 0.1 sec interval to separate steps 1 and 2.

2) change CSS on cards (e.g. "transition: ease-out 1.5s") and change their x/y to place them in the correct spot in the holder. Can also apply other effects such as rotation. (currently, spin is limited to increments of 180 degrees (360 for non-symmetrical cards) because onEnter and enterRoutine cannot be used to "correct" the rotation). Additionally, I set a parentChangeRoutine used in step 4.

This step must be separate from the first step because the CSS transition needs to have a starting and stopping point that isn't applied at the same time.

The CSS transition is not desirable outside of dealing the cards because it makes dragging the cards delayed (especially when the transition is as high as I set it).  The CSS transition CANNOT be removed by enterRoutine or onEnter, because the cards technically enter (in the properties) before the CSS transition moves them there.

3) Apply ownership and flip the card.  Ownership cannot be applied in step 2 because then only the owner would see the card travel to their hand (which somewhat defeats the point of the effect).  Typically these are applied on entry, but they cannot otherwise they will be applied before the CSS transition moves the cards to the hand (i.e. the cards would disappear to other players, and flip before entering the hand).

For this step, I use another timer.  The timer receives an array of objects that holds which holder they are heading towards (because I store the eventual owner of the card as a property in the holder), the card's ID, and the time it was delt.  Then 1.6 seconds (slightly over the time I set for the CSS transition) the timer changes ownership of the card, flips the card, and deletes the entry from the array.
 
4) Remove the CSS when the player attempts to move the card. A parentChangeRoutine applied in step 1 deletes the CSS so the player can drag the card freely as soon as they click on it.

The CSS could be removed in step 3, but that would remove a nice effect of the cards seeming to slide together smoothly.  Instead, you get a jarring effect as the cards move over to make room for the next card.  Step 3 could also wait until all the cards have settled, but they would remain faced away from the player until all the cards are dealt.  Step 4 could also be done through a 3rd timer, but that seemed less simple than a parentChangeRoutine.

The negative effect of this process is that the holder will not flip the cards when they enter.  So if the holder has an onExit that flips the cards, they will not automatically flip back when they are placed in the holder again.  I've also had to lock the buttons for a period (using the 2nd timer to prevent clicks long enough for the transitions to take place).

There are three things that would greatly simplify this process.

1) a fraction of a second interval between when a card is removed from its holder to be dealt and when other properties could be applied (e.g. new x/y and new rotation)
2) an interval between when a card is dealt, and when onEnter & enterRoutine are applied.
3) A setting that allows the deletion of transition effects from cards as soon as they are picked up.

Other settings for a deal button that would be helpful but could also be done through the JSON:
1) a property that determines how many cards will be delt
2) a property that stores an array of holders that the button will deal to
3) a property that determines if the number of cards will be dealt to one player, the next player, or the player that clicked the button

I completely understand if it is decided that this is not worth integrating into the Javascript (I'm not sure that it is).  However, I wanted to show how it would look, and give a basic understanding of what the obstacles are.

**Comment by bjalder26** [comment]
> There are two possibilities that I think might be worth exploring for the vtt engine code.
> 
> * A default animation to move (probably a lot faster than 1.5s - however, the 1.6s should be changed to correspond)

It didn't really occur to me before, but I suppose the engine could move the cards in increments smaller than 0.1 seconds, which is the limit of the timers right now.  I'm not sure how smooth the animation would be though.  Also, the 1.5 seconds can easily be changed in my example if you want to look at other speeds.

> * A delayed action routine that could operate without a timer widget
> 
> Feedback on @bjalder26 's routine code: Why not delay the changing of parent.
> 
> * You'd set the x,y to move the card over its destination holder without changing parent using css transition to animate.
> * The destination holder can set owner, flip the card, and set the css transition to use for sliding cards around in the holder.
> * The card's onParentChange can remove any css transition.

That should work.  And really it does NEED to be that way to prevent owner issues when people drag cards in/out.  However, I can't use the button to change the parent, otherwise, I don't think I can send multiple cards at once, which means the cards have to move really fast, or the second timer will have to be repurposed into changing the parent (and the x/y) rather than performing the actions that would normally happen on a parent change (which is what I will do).  That would get rid of the issue of holders not being able to flip cards dragged into them.

**Comment by robartsd** [comment]
> > There are two possibilities that I think might be worth exploring for the vtt engine code.
> > 
> > * A default animation to move (probably a lot faster than 1.5s - however, the 1.6s should be changed to correspond)
> 
> It didn't really occur to me before, but I suppose the engine could move the cards in increments smaller than 0.1 seconds, which is the limit of the timers right now. I'm not sure how smooth the animation would be though. Also, the 1.5 seconds can easily be changed in my example if you want to look at other speeds.

If we build it into the engine, I'd still have CSS do the actual annimation, the engine would simply set some timeout functions to make clean up after the CSS annimation. If built into the engine we could even have the shared state change directly from the state prior to transition to the state following transition, keeping the transition as only a display feature of the client.

> That should work. And really it does NEED to be that way to prevent owner issues when people drag cards in/out. However, I can't use the button to change the parent, otherwise, I don't think I can send multiple cards at once, which means the cards have to move really fast, or the second timer will have to be repurposed into changing the parent (and the x/y) rather than performing the actions that would normally happen on a parent change (which is what I will do). That would get rid of the issue of holders not being able to flip cards dragged into them.
> 
> After trying: I've realized delaying the parent change causes the same card to be selected over and over. I now remember that part of the reason why I changed the parent right away was so that I could select another card. I don't think this is something that I can't overcome, I just need a new way to select the "top card" (which won't actually be on top anymore).

Could set a property on the card that the deal routine filters out. The delayed routine could remove that property when setting the parent. The property could even contain the destination parent so less information is needed to be transferred directly to the delayed routine. If the destination parent has `alignChildren:true` then the delayed routine doesn't need to know anything about position.

**Comment by robartsd** [comment]
> Apparently, they will smooth out an x/y change, but not a movement due to a parent change

Yes, changing parent moves the widget in the DOM, from the CSS perspective the widget is removed from the one parent then a new widget appears in the new parent.

> I would love for VTT to have some eye candy that encourages people to migrate games, but I don't really care what form that takes.

I'd love some eye candy too.

**Comment by RaphaelAlvez** [comment]
I'll consider this for PR #466

**Comment by bjalder26** [comment]
I noticed today that PCIO put a css transition on their decks.  When a card is picked up it appears to get turned off and the card is slightly rotated and enlarged.  You can see the transition when a card is dealt, and when you drag around a holder, because the deck lags behind.  I'm not sure how long they've had these features.

**Comment by robartsd** [comment]
PCIO has had a short transition smoothing movement since I first started using it last summer.

**Comment by flackr** [comment]
I believe the PR that I am putting together #1423 supports this use case. Please try it out and let me know if it works for this issue as well.
