### ISSUE TITLE
Players overlay looks empty and very basic

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#51]
one idea is to add "user" icons to players

maybe this overlay can aggregate more features like score and teams.

**Comment by robartsd** [comment]
I'd like player overlay to provide a count of number of items in hand (a total of all items owned by the player, possibly expandable to a list of holders with "childrenPerOwner" and a count of that player's items in each holder, some games would even benefit from being able to see a count of items from each deck in a player's hand). Could have a new property for holders allowing them to be hidden from the count int he players overlay.

I'd also like a way to keep the player overlay active in the margins of the page during gameplay.

Would be nice to be able to play in hotseat mode (switch players in same browser window between turns). Currently this is possible (change player name and items in hand continue to be owned by the prior name, change back and you see the hand); but you don't see the names of other players who are using the same browser. Would be good to be able to explicitly choose between renaming the current player (update the owner of all items) and switching to another player (items owned by the old player name remain owned by that name). The player list should list the name of any owner of items at all times.

**Comment by robartsd** [comment]
Grouping other player issues here:
 - #50 Adding Teams

**Comment by rogerl50** [comment]
> Would be nice to be able to play in hotseat mode (switch players in same browser window between turns). Currently this is possible (change player name and items in hand continue to be owned by the prior name, change back and you see the hand); but you don't see the names of other players who are using the same browser. Would be good to be able to explicitly choose between renaming the current player (update the owner of all items) and switching to another player (items owned by the old player name remain owned by that name). The player list should list the name of any owner of items at all times.

I just posted a note in #tech about a similar issue. In addition to what you are proposing here, there is no way to add a new player other than by renaming an existing player (who may or may not be in use).

In general, it seems to me that there should be a tighter link between players and browser tabs. I'd like to be able to open a new browser tab on a room and affirmatively state that I want player "x", or I want a new player.

**Comment by RaphaelAlvez** [comment]
done
