### ISSUE TITLE
CLONE cannot assign IDs to clones

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#513]
When a widget is cloned, the id is generated randomly, and cannot be set as one of the properties.

For example, this JSON will not set the id to 'newID':
"clickRoutine": [
    {
      "func": "SELECT",
      "property": "id",
      "value": "cloneme"
    },
    {
      "func": "CLONE",
      "xOffset": 40,
      "yOffset": 40,
      "properties": {
        "id": "newID"
      },
      "collection": "myClones"
    }
  ],

This room demonstrates the issue. https://virtualtabletop.io/tarj

**Comment by 96LawDawg** [comment]
Sort of related to #415 which I opened because of a similar scenario.  Although there is obviously a difference between CLONE and SET.
