### ISSUE TITLE
Redesign for piles menu overlay

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#53]
As discussed on 07/01 meeting:

![Pile menu](https://user-images.githubusercontent.com/73476656/103977834-d6f0a880-5158-11eb-9753-69854d043802.jpg)

[Ideally, the counter for the split would be a dropdown in mobile as it would trigger the keyboard otherwise](https://miro.medium.com/max/408/1*9Uhd_dTbDOMG6SfcMdMTCA.gif) ([original link](https://medium.com/@kollinz/dropdown-alternatives-for-better-mobile-forms-53e40d641b53)). Not sure if it's possible to create this kind of differentiation 

(SVG on discord https://discordapp.com/channels/770758631146782780/795328026333937704/796973954505506846)

Anyone wanting to implement please assign yourself to the issue. Feedback before implementation is welcome.

**Comment by larkob** [comment]
A dropdown in mobile is actually not ideal for a large amount of values. I believe a better approach is a slider or dial with a +/- button for precision:
![image](https://user-images.githubusercontent.com/35028592/103993447-e5a98080-5195-11eb-8424-28a93dc87523.png)

**Comment by RaphaelAlvez** [comment]
I'm actually not a fan of a slider all by itself because for large amounts it's hard to get the right value.
I DO like the combination of buttons and slider

**Comment by 96LawDawg** [comment]
So it isn't a proper UI interface, but what Ingegneus came up with today is pretty awesome.  See https://discord.com/channels/770758631146782780/862352981747695616/917075619966234664 and the Demo Library at https://virtualtabletop.io/DemoLibrary.  Something like that could be made into a composed widget if we don't get UI changes we are satisfied with.
