### ISSUE TITLE
add any css var

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#532]
so sometimes I find myself needing more than one css var (only "color" --> --color at the moment).
I don't like the approach of having to set the whole "css" property if I want to change only one thing. This is even worse when I need to change 2 variables depending on conditions. I have already used --color to set a display wich only by itself is a bit ridiculous.
My initial suggestion was going to be one extra "joker" css property but I think the best solution would be to have something like "exampleCSSVAR" and this would be converted into something like "--example"

**Comment by bjalder26** [comment]
So basically anytime a CSS variable was changed the engine would create new CSS on the fly?

**Comment by robartsd** [comment]
We really need to add game stylesheets; of course that would probably leave us will a similar issue managing the classes list.

If we do have a dynamic custom property name, would we want it as a prefix or a suffix. Should we just have a "css-" prefix for property names to use as part of the inline styles, then concatenate them all together? "css-example":"--example:value;"

I suppose we could solve the classes problem in the same way using a "classList-" prefix for property names. There'd be less issues with the class list because order doesn't matter in css classes, but order of declarations of inline styles does matter if they set the same property.

**Comment by RaphaelAlvez** [comment]
@bjalder26 
>So basically anytime a CSS variable was changed the engine would create new CSS on the fly?

No. you set a property in the widget that is passed to the css as a css variable. There are already some properties that set css variables but the only ones that are flexible are color and the button colors properties. Whatever you set to color it passed to css as --color.
I'm proposing to add the possibility to create custom properties that are passed to CSS as variables which would automatically change the widget visually. those properties would have a suffix or prefix that the code would read and include that property to the list of properties that go to css

>If we do have a dynamic custom property name, would we want it as a prefix or a suffix. Should we just have a "css-" prefix for property names to use as part of the inline styles, then concatenate them all together? "css-example":"--example:value;"

not sure if that is the best solution but it would be an easy solution

>I suppose we could solve the classes problem in the same way using a "classList-" prefix for property names. There'd be less issues with the class list because order doesn't matter in css classes, but order of declarations of inline styles does matter if they set the same property.

for that I would prefer the suffix "ClassCSS" that would be compatible with the other CSS properties.

so if I was to implement this I would use "VarCSS" and "ClassCSS" as suffixes.

**Comment by robartsd** [comment]
> so if I was to implement this I would use "VarCSS" and "ClassCSS" as suffixes.

I'd prefer prefixes over suffixes so that sorting by property name would group them together, but we've already established a pattern of suffices with Routine so maybe suffixes would be more consistent with current style.

**Comment by robartsd** [comment]
Prefer a generalized solution for CSS rather than a variable specific solution. Of course a generalized CSS solution would have to guarantee a specific order of application, but a variable specific solution would not because there'd be no way to declare the same variable twice in the same widget.
