### ISSUE TITLE
add automated test with production environment

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#534]
PR #530 was working fine everywhere we tested it but when merged it crashed the server because the minifier didn't like the change.

There should be an automated test that actually runs the same minified code that the production server runs.

**Comment by robartsd** [comment]
Would it be possible to switch the PR test server based on if the PR is marked ready for review or not. Draft PRs would continue running in debug mode, but once marked ready for review the PR test server would switch to production environment build.
