### ISSUE TITLE
Fn keys always multiselect

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#541]
On my Mac, if I Ctrl-click some widget, then select another with a function key, I always end up with both widgets selected.  Also, Shift-Ctrl-click still brings up a context menu.

**Comment by robartsd** [comment]
Function keys should only be multi-select if shift key is down when function key is pressed. I don't really see why it should, but see if #542 fixes this.

**Comment by rogerl50** [comment]
This is very odd, now they work properly both with #542 and in production. There must have been some other key combination that I used before that caused the problem. I'm going to close this until I have a better problem statement/diagnosis.

**Comment by ArnoldSmith86** [comment]
You probably switched away from the VTT browser tab while SHIFT was active. Then it gets stuck until you press it again.

That problem should be fixed with #542 though.

**Comment by rogerl50** [comment]
That could well be the problem. I was trying to see if SHIFT worked now in production (it didn't), and at one point I pressed a key combination that led Firefox to switch the active tabs.
