### ISSUE TITLE
JSON Copy and Paste is Broken

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#543]
Something in one of the recent merges (#525 #520 or #523) broke copy and paste.

**Comment by ArnoldSmith86** [comment]
Anything specific? Just copying parts of the text works for me.

Also, please add label `JSON editor` if appropriate.

**Comment by 96LawDawg** [comment]
Done.  And the JSON Editor crashes if I copy an entire function.  For example:

```
    {
      "func": "SET",
      "property": "clickable",
      "value": false
    },

**Comment by robartsd** [comment]
Is this editing a single widget or a multi-select?

**Comment by 96LawDawg** [comment]
Single widget.  And I just checked and it is only happening in Edge.  Not in Chrome.

**Comment by ArnoldSmith86** [comment]
Pfft. Edge. Weird. I don't think I can test in Edge. I'll check the log.

**Comment by 96LawDawg** [comment]
I tried to look at what was happening in the console, but if flashes red text so fast and resets the room that I can't see it long enough to read it.

**Comment by 96LawDawg** [comment]
Okay, I figured out how to "preserve the log" in Console.  This is what I got:

**Comment by 96LawDawg** [comment]
Uncaught TypeError: Cannot read property 'toString' of undefined
    at jeGetLastKey (lawdawg4:16)
    at Object.show (lawdawg4:16)
    at jeShowCommands (lawdawg4:16)
    at jeGetContext (lawdawg4:16)
    at lawdawg4:16

**Comment by ArnoldSmith86** [comment]
Can you reproduce this on any PR test server (maybe after updating them)? Then we at least get proper line numbers.

**Comment by 96LawDawg** [comment]
On test server #542 

Uncaught TypeError: Cannot read property 'toString' of undefined
    at jeGetLastKey (lawdawg:1884)
    at Object.show (lawdawg:1548)
    at jeShowCommands (lawdawg:2026)
    at jeGetContext (lawdawg:1878)
    at lawdawg:2227

**Comment by ArnoldSmith86** [comment]
Hmm. That probably won't help. `jeGetLastKey` only has one `toString`. Something in the context detection changed.

Can someone try "break on exception" in Edge dev tools and see if you can find out what's wrong?

**Comment by ArnoldSmith86** [comment]
> #525 #520 or #523

How sure are you about that?

**Comment by 96LawDawg** [comment]
No.  But it was working fine 12 hours ago and those all impacted the JSON Editor in some way.  It works fine on an older test server that hasn't been brought up to date.

**Comment by ArnoldSmith86** [comment]
Please check if this still happens in #547.

**Comment by 96LawDawg** [comment]
Problem is gone in #547
