### ISSUE TITLE
Update recall, timer, and counter button clickRoutine defaults in editmode to use a dynamic expression 

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#549]
If the default clickRoutine in recall buttons used ${PROPERTY parent}, then changing the holder's ID would not affect the function.
   ` {
      "func": "RECALL",
      "holder": "${PROPERTY parent}"
    },
    {
      "func": "FLIP",
      "holder": "${PROPERTY parent}",
      "face": 0
    },
    {
      "func": "SHUFFLE",
      "holder": "${PROPERTY parent}"
    }
  ],`

![image](https://user-images.githubusercontent.com/78324099/121550871-be6d0e80-c9d4-11eb-8b86-93821ca9a217.png)

Likewise, the default label for counter buttons could be changed to "${PROPERTY parent}"
  `"clickRoutine": [
    {
      "func": "LABEL",
      "label": "7rdx",
      "mode": "inc",
      "value": 1
    }
  ]`

![image](https://user-images.githubusercontent.com/78324099/121553751-2d4b6700-c9d7-11eb-861f-7f7922e95792.png)

And the default timer for timer buttons could be changed to  "${PROPERTY parent}".

 `"clickRoutine": [
    {
      "func": "TIMER",
      "timer": "ky04",
      "mode": "reset"
    }
  ],`
![image](https://user-images.githubusercontent.com/78324099/121554270-a21ea100-c9d7-11eb-9142-641534244baf.png)

**Comment by bjalder26** [comment]
My guess is that these would be the required changes to editmode.js.  However, I may have the quotation marks wrong.  I couldn't figure out how to do a PR, otherwise, I would have tried it out myself.

Lines 138-141
      clickRoutine: [
        { func: 'RECALL',  holder: '${PROPERTY parent}' },
        { func: 'FLIP',    holder: '${PROPERTY parent}', face: 0 },
        { func: 'SHUFFLE', holder: '${PROPERTY parent}' }
      ]

Line 225
  const r = { func: 'LABEL', label: '${PROPERTY parent}', mode: 'dec', value: 1 };

Lines 260-265
      clickRoutine: [
        {
          func: "TIMER",
          timer: "${PROPERTY parent}"
        }
],

**Comment by robartsd** [comment]
> My guess is that these would be the required changes to editmode.js. However, I may have the quotation marks wrong. I couldn't figure out how to do a PR, otherwise, I would have tried it out myself.

I don't think it matters if the values are quoted with double qoutes `"` or single quotes `'`' in the .js file. The values should show up as double quotes in JSON either way. Code style for this project seems to prefer single quotes in js files.
