### ISSUE TITLE
Deleted widgets are not removed from pile handle count

### ISSUE THREAD

**Issue by robartsd** [ArnoldSmith86/virtualtabletop#554]
I just noticed this in the updated Reward. If a routine removes cards from a pile, then deletes the cards, the pile handle does not get updated (same behavior observed for both RECALL and SET parent where the new holder deletes the card in the enterRoutine). Count does appear correctly after refresh.

**Comment by bjalder26** [comment]
Yeah, I'm seeing that a lot on the testing I've been doing that is posted in #477 and I would also say it relates to #380.
