### ISSUE TITLE
Confirmation on variant removal

### ISSUE THREAD

**Issue by minotalen** [ArnoldSmith86/virtualtabletop#556]
There's a confirmation dialog for deleting a widget, removing a variant is more impactful than that. Also when you delete one variant, the button for deleting the next one is right under your cursor.  
(also don't worry didn't remove anything accidentally, just think it can happen too easily atm)

**Comment by 96LawDawg** [comment]
You could probably also include the need for a confirmation to update a variant also.  I hate pressing extra buttons.  But I lost an hour's worth of work the other day because I saved (updated) the changes in the wrong variant.

**Comment by minotalen** [comment]
Just realized removing the whole game also doesn't require any confirmation (not the hard way).

**Comment by RaphaelAlvez** [comment]
> You could probably also include the need for a confirmation to update a variant also.  I hate pressing extra buttons.  But I lost an hour's worth of work the other day because I saved (updated) the changes in the wrong variant.

That's the worst for me because sometimes you can get confused in which variant are you loading the current room state

**Comment by bjalder26** [comment]
I feel like ideally 'update variant' should also trigger an automatic download of the variant to a virtualtabletop folder but with an increasing file number.  These files are tiny, and downloading 100 of them won't matter.  Also, I don't particularly like that the word 'save' is used to update the text, or that it is on the same line as a button that removes the entire game from the room.

**Comment by 96LawDawg** [comment]
Pretty much everything about this part of the UI is awful (sorry ArnoldSmith; I know you were just trying to put something functional together).  BUT, a major rewrite of (which is what we are talking about here) really gets to the whole idea of a major rewrite of the whole UI and not just patching the existing system.  This is the one area where our skilled staff is the weakest and we haven't had anybody around long enough to want to take this on.  There are some mock ups that would make all this better, but that's about it.

**Comment by RaphaelAlvez** [comment]
@ArnoldSmith86 this is in #1223 right?

**Comment by ArnoldSmith86** [comment]
It does address the things mentioned in here.

If this issue is not fixed by #1223, we screwed up.
