### ISSUE TITLE
setting function block parameter to `${PROPERTY name OF missingWidget}` crashes client

### ISSUE THREAD

**Issue by robartsd** [ArnoldSmith86/virtualtabletop#565]
Originally noticed with crashes related to `${PROPERTY propName OF invalidWidgetID}`.

Testing by bjalder26 indicates that this is returning to null to the parameters as designed, but the following parameters evaluating to null causes a crash:
- SELECT:property
  - ${PROPERTY name OF missingWidget} crashes client
  - ${PROPERTY missingProperty OF widget} property parameter is null
  - ${missingVariable} property parameter receives default value
- SELECT:value
  - ${PROPERTY name OF missingWidget} crashes client
- CALL:routine
- CALL:variable
- CALL:widget
- CALL:arguments
- CLICK:collection

Additionally, SET:property=null will delete the widgets.

**Comment by bjalder26** [comment]
It seems like if it is in a dynamic expression you get an error, but if it is in a function, then you typically get a crashed client.  In SET/value it sets the value to null, but in SET/property it deletes the widget (setting a null property to whatever value).

**Comment by robartsd** [comment]
Looks like the property retrieval is working as designed (returns null) but some functions crash when some arguments are null.

**Comment by ArnoldSmith86** [comment]
I just had the client crash because `widgetID` should have been `$widgetID`. It did crash though because the `problems` array was `undefined`.

```JSON
{
  "id": "uqow",

  "x": 438,
  "y": 266.5,
  "width": 75,
  "height": 75,

  "css": "border-radius:50%;",
  "image": "/assets/1695948041_6197",
  "reset": true,
  "resetProperties": {
    "x": 438,
    "y": 266.5
  }
}


{
  "type": "button",
  "id": "b",

  "clickRoutine": [
    {
      "func": "SELECT",
      "property": "reset",
      "value": true
    },
    {
      "func": "FOREACH",
      "loopRoutine": [
        {
          "func": "FOREACH",
          "in": "${PROPERTY resetProperties OF widgetID}",
          "loopRoutine": [
            {
              "func": "SET",
              "property": "${key}",
              "value": "${value}"
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by bjalder26** [comment]
I did some contact tracing for this issue in case it helps.
`Crashed client by using function with ${PROPERTY name OF missingWidget}`

**Comment by bjalder26** [comment]
Tracing does not appear to be helpful.
  {"time":1626458307989,"deltaID":0,"type":"click","payload":{"id":"0pj9","mode":"respect"},"player":"Guest241","servertime":1626458307990,"source":"client","serverDeltaID":15},
  {"time":1626458307990,"deltaID":0,"type":"evaluateRoutine","payload":{"id":"0pj9","property":"clickRoutine"},"player":"Guest241","servertime":1626458308062,"source":"client","serverDeltaID":15},

This is what the browser debugger showed.
![image](https://user-images.githubusercontent.com/78324099/125991075-09e1a17e-96fd-49ca-8e14-b5e965617130.png)

**Comment by ArnoldSmith86** [comment]
Don't spend too much time here. It's pretty clear what the problem is.

**Comment by 96LawDawg** [comment]
Fixed.  Probably by #893
