### ISSUE TITLE
Support array indexes in dynamic expressions

### ISSUE THREAD

**Issue by robartsd** [ArnoldSmith86/virtualtabletop#567]
We can get object indexes in the form "var object.index =", but this does not work for "var array.index =".

**Comment by ArnoldSmith86** [comment]
It doesn't? `var array.0 = 1` should work.

**Comment by bjalder26** [comment]
Shouldn't 'getting' them look like this?
"var c = ${a.1}",

**Comment by ArnoldSmith86** [comment]
Yes.

**Comment by robartsd** [comment]
> It doesn't? `var array.0 = 1` should work.

I got problems stating array is not an object when trying `var array.$index =`

**Comment by bjalder26** [comment]
> > It doesn't? `var array.0 = 1` should work.
> 
> I got problems stating array is not an object when trying `var array.$index =`

I get that error when trying to do that on a string.  Are you sure it isn't a string?

**Comment by robartsd** [comment]
I'll do some testing and see if I can generate any test cases. I was pretty frustrated with string values being converted to numbers at the time it came up, so I wasn't as focused on this issue as I could have been.

**Comment by robartsd** [comment]
I think I was trying to get the value at an index of an array stored in a property. "var v = {PROPERTY property.index}" does not do "var v = {PROPERTY property} getIndex index" I think this is beyond the level of dereferencing that is supported.
