### ISSUE TITLE
Default layers in JSON Editor

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#570]
I was working on some wiki things and noticed in the widget properties there is a discrepancy between the wiki default layers and what the JSON editor shows.  For example, a holder says it has a default layer of -3.  No layer is displayed in the JSON editor.  When you click on layer, you get a 1.  Same thing for labels, timer, and maybe others.  The wiki also says that the default for layer is 0, but maybe it is 1?  I'm not sure if this is a wiki issue, a code issue, or a JSON editor issue.

**Comment by bjalder26** [comment]
Is this the same issue or is it different?
https://github.com/ArnoldSmith86/virtualtabletop/issues/562

**Comment by RaphaelAlvez** [comment]
Not really. The other issue is about updating the  defaults when setting a type

**Comment by RaphaelAlvez** [comment]
It is an extension of #459

**Comment by 96LawDawg** [comment]
Yeah, this is covered by #459 and the additional comments there about other widgets.  I did a brief search, but didn't notice because it was about buttons.  I will close this one.
