### ISSUE TITLE
SORT error with null sort values

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#574]
I was testing out a sort button on a custom deck.  I created sort keys for two of the suits just to see how things went.  I created a collection of a subset of items in a holder and then did a sort based on that.  What I discovered is an error if the sort value/key is missing from a card in the collection that is being sorted.  Console shows the following:

Uncaught (in promise) TypeError: Cannot read property 'localeCompare' of null
    at VM22 lawdawg:5592
    at Array.sort (<anonymous>)
    at Button.sortWidgets (VM22 lawdawg:5588)
    at VM22 lawdawg:5144
    at w (VM22 lawdawg:4594)
    at Button.evaluateRoutine (VM22 lawdawg:5143)
    at Button.click (VM22 lawdawg:4452)
    at inputHandler (VM22 lawdawg:3611)
    at VM22 lawdawg:3645

**Comment by robartsd** [comment]
Possibly similar to #565

**Comment by 96LawDawg** [comment]
I think null being lowest makes the most sense.  But part of me wants it the other way.  It doesn't really matter because a designer can easily fix the problem by not having null sort values.  So I'm with David and vote that null widgets come before the widgets with sort values.

**Comment by bjalder26** [comment]
Default values aren't going to be assessed as null are they?

**Comment by 96LawDawg** [comment]
Well, I guess the answer depends on what you mean by default values.  I tested the current production server with width as the SORT key and scale.  Width shows up as a gray property on all widgets.  Scale does not.  Worked fine for both of those.  What is causing the problem is custom properties that are null or undefined (I don't really know the difference, so just using both words here).  I don't know of other kinds of default properties to test.  If you can think of any, let me know.

**Comment by robartsd** [comment]
I think I'll put together an implementation that sorts null first (lowest) by default. I might try to also add an option to switch that to sort null as highest.

**Comment by robartsd** [comment]
Looks like javascript's native sorting of array elements:
- arrays based on their first element (empty arrays are first, second index)
- Number.NEGATIVE_INFINITITY
- string sort order
- Number.POSITIVE_INFINITITY
- NaN
- Objects
- null

We have definite plans to add numerical sort in compute operations and we should consider doing that in 'SORT' as well.
