### ISSUE TITLE
SORT collections do not work

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#575]
I'm trying to create a SORT button that only sorts cards owned by a certain player.  The cards are in the hand (childrenPerOwner: true).  I want a SORT button that will only impact what the person pressing the button sees and not the other players.  But the SORT collection does not work properly.  Both of these JSON excerpts give the same sort result (and every player's hand is sorted; not just the player pressing the button):

```
 {
      "func": "SORT",
      "key": "sortNum",
      "holder": "theHand"
    }
```
And this:
```
 {
      "func": "SELECT",
      "property": "parent",
      "value": "theHand"
    },
    {
      "func": "SELECT",
      "source": "DEFAULT",
      "property": "owner",
      "value": "${playerName}"
    },
    {
      "func": "SORT",
      "collection": "DEFAULT",
      "key": "sortNum",
      "holder": "theHand"
    }
```

**Comment by robartsd** [comment]
What happens if you remove "holder" from the last block?

**Comment by 96LawDawg** [comment]
Strange results.  I tried that.  See before and after pics where I remove "holder".  It just changes the overlaps to something odd.

<img width="363" alt="Before" src="https://user-images.githubusercontent.com/76912527/122308159-7583f100-ced1-11eb-926e-ad9887e0affe.png">

<img width="364" alt="After" src="https://user-images.githubusercontent.com/76912527/122308161-774db480-ced1-11eb-8a4a-f3dce83a3dba.png">

**Comment by robartsd** [comment]
Sort changes z order, but not x/y. Probably needs a call to the holder's align children routine.

**Comment by 96LawDawg** [comment]
Yeah, it does look like that.  So is that something that needs to be added to the Javascript (I think so), or is there an additional step I need to take?

**Comment by robartsd** [comment]
> Yeah, it does look like that. So is that something that needs to be added to the Javascript (I think so), or is there an additional step I need to take?

Yes. I have a plan for fixing this in widget.js.
