### ISSUE TITLE
one property to combine all OH properties

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#580]
I think its quite restrictive to only have `borderColorOH` `backgroundColorOH` and so on. a lot of cool things could be made, if there was a `cssOH` or even a `propertiesOH` made available to all widgets. `cssOH` would be closer to what the OH properties can do now, but `propertiesOH` would be more powerful. what i imagine them doing at the moment is to just change the appearance of the widget that they are in. so for example something like `"propertiesOH":{"type":"holder"}` would be ignored, but something like `"propertiesOH" : {"image" : "/newImage", "width" : 10}` would be applied (maybe as some sort of overlay or idk)

**Comment by robartsd** [comment]
It would be nice, but would require major work to implement. The current OH properties are implemented by setting specific CCS variables that are written into the stylesheet's selector for the hover pseudo class. The browser's native hover code takes over from there. Implementing this idea would require us to write our own hover code (we have something line this in JSON editor for the Fx keys, but it is far from perfect - load Tangrams to see examples of widgets not being correctly identified).
