### ISSUE TITLE
SET arrays and Label arrays set differently

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#581]
It appears that when you `SET` an array it is not being set properly.  When you use `LABEL` to set an array it receives spaces in-between the values, however, when you use `SET` it does not.  This picture shows the difference.
![image](https://user-images.githubusercontent.com/78324099/122474812-56e13100-cf89-11eb-88bf-d8d5506690d7.png)

This room holds the example above.
https://virtualtabletop.io/0sdj

It appears that line 1282 of widgets.js doesn't 'capture' the when `SET` is used to set an array.
![image](https://user-images.githubusercontent.com/78324099/122474609-184b7680-cf89-11eb-9c6b-467f2c581ff6.png)
https://github.com/ArnoldSmith86/virtualtabletop/blob/797c152f8168f5f6dcb8a2056e609e37031f3ba2/client/js/widgets/widget.js#L1282

**Comment by bjalder26** [comment]
I'm also not sure if line 1284 is capturing anything at all.

**Comment by robartsd** [comment]
1284 is converting numerical strings to numbers.

**Comment by bjalder26** [comment]
> 1284 is converting numerical strings to numbers.
Yeah, I realized later that it was capturing the numerical strings for `LABEL`, it just doesn't do anything for `SET` text (which is what I had tested).

**Comment by robartsd** [comment]
I personally think treating these differently is a feature not a bug. LABEL should make it easy for game designers to set the label text in a way that is as user friendly as possible, SET should give game designers more control over how the property gets set, so it should copy the value parameter provided as directly as possible to the property.

**Comment by bjalder26** [comment]
> I personally think treating these differently is a feature not a bug. LABEL should make it easy for game designers to set the label text in a way that is as user friendly as possible, SET should give game designers more control over how the property gets set, so it should copy the value parameter provided as directly as possible to the property.

I think you have a good point.  `SET` text will retain the array as an actual array, whereas `LABEL` will turn it into a string.  However, that leads me to believe there is another issue.  The eventListener will indiscriminately change the text to a string if there is a keyup event within the textarea.

https://github.com/ArnoldSmith86/virtualtabletop/blob/797c152f8168f5f6dcb8a2056e609e37031f3ba2/client/js/widgets/label.js#L20 

So perhaps this is really just the same issue as #399.
