### ISSUE TITLE
`twoRowBottomAlign` does not work

### ISSUE THREAD

**Issue by robartsd** [ArnoldSmith86/virtualtabletop#589]
This was broken by #563. Code to check label height overrides the `textarea` `height` property, but this is failing to resize the textarea due to the new `min-height` property.

**Comment by bjalder26** [comment]
Could importing games be part of the TestCafe?

**Comment by robartsd** [comment]
Doesn't matter, TestCafe wouldn't catch this because the problem isn't in the state.
