### ISSUE TITLE
Make card-hover-border of holders customizable

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#597]
title says everything. properties that would be nice to edit would be border-width, border-color and color gradients

**Comment by robartsd** [comment]
Repeating that my preferred solution to this whole category of issues is game stylesheets #154

**Comment by RaphaelAlvez** [comment]
> Repeating that my preferred solution to this whole category of issues is game stylesheets #154 

But this should anyway be customizable per widget.

Btw do you know how to do that stylesheet PR? I believe this is just lacking a coder.

**Comment by robartsd** [comment]
My first step would be to determine if the server needs changes to serve up user supplied content with the correct mime type; but I haven't looked into that yet.

**Comment by RaphaelAlvez** [comment]
> My first step would be to determine if the server needs changes to serve up user supplied content with the correct mime type; but I haven't looked into that yet.

I would imagine that simply having it be applied to the room/table css would enough as everything is a child of the table (don't remember the correct name)

**Comment by robartsd** [comment]
It needs to be served as text/css or we would run into the same issue people have with custom stylesheets using url properties.
