### ISSUE TITLE
FOREACH loop on two consecutive collections freezes/slows client

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#602]
A FOREACH loop on two consecutive collections appears to freeze or slow the client.

Clearing out the DEFAULT collection between each FOREACH by selecting for nothing and putting that in the DEFAULT collection appears to be a workaround.

Issue demonstrated here: https://virtualtabletop.io/2xe7

**Comment by ArnoldSmith86** [comment]
How much are we talking? For me it's barely noticeable. What OS/browser are you using?

**Comment by ArnoldSmith86** [comment]
There's an error though in the console. I'll check.

**Comment by bjalder26** [comment]
> How much are we talking? For me it's barely noticeable. What OS/browser are you using?

For me all the buttons except the one where I clear out the DEFAULT collection freeze the client or severely slow it down.  I am on Windows 10 and use Brave (basically Chrome).

**Comment by ArnoldSmith86** [comment]
Does this still happen in #598? Because that seems to be the error in the console. I don't experience any freezing though. Tested in Firefox on Linux and Windows and Chrome on Linux and Windows.

**Comment by bjalder26** [comment]
> Does this still happen in #598? Because that seems to be the error in the console. I don't experience any freezing though. Tested in Firefox on Linux and Windows and Chrome on Linux and Windows.

No, it does NOT happen in #598.  Not at all.
