### ISSUE TITLE
Some Labels are Still Odd

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#607]
Since the merger of #563 and #591 (not sure which one), some labels with borders look off.  For example, in the Arrays tutorial (Evaluating variant) there are 3 arrays at the bottom of the screen with 2px dashed border.  The letters overhang the border and when you select the textarea (can't show that in a screenshot), the textarea is a bit larger than the border.  I don't have an image of what they looked like before, but it was cleaner than it is now.  I added twoRowBottomAlign to see what happened.  Results of with and without that.

Without
<img width="649" alt="Without BottomAlign" src="https://user-images.githubusercontent.com/76912527/123483393-3ab64300-d5cc-11eb-80f2-5e69f10ebcf4.png">

With
<img width="635" alt="With BottomAlign" src="https://user-images.githubusercontent.com/76912527/123483399-3db13380-d5cc-11eb-8812-20cc59659218.png">

**Comment by ArnoldSmith86** [comment]
Also the text is a few pixels lower now. Compare https://virtualtabletop.io/w558 vs http://212.47.248.129:3479/w558 .

**Comment by rogerl50** [comment]
Did you test with PR #595 ?

**Comment by 96LawDawg** [comment]
No, but thank you.  It made it worse.  I will post a comment there.
