### ISSUE TITLE
Improvements to SELECT function

### ISSUE THREAD

**Issue by larkob** [ArnoldSmith86/virtualtabletop#61]
I decided to group these change requests in a single issue because they appear to be quite easy to implement.

1) SELECT should allow to use a list of value for making a "=" comparison with the property:
```
{
  "func": "SELECT",
  "property": "id",
  "relation": "=",
  "value": ["<holderID>", "<holderID>"]
}
```

Alternatively, add an "in" relation for comparison against a list of values:
```
{
  "func": "SELECT",
  "property": "id",
  "relation": "in",
  "value": ["<holderID>", "<holderID>"]
}
```

Reason: A common case of selecting multiple objects by ID would otherwise require multiple operations.

2) SELECT should allow to use a "type" parameter in addition to the regular filter criteria (property, relation and value):
```
{
  "func": "SELECT",
  "type": "card",
  "property": "rank",
  "relation": ">=",
  "value": 10
}
```

Reason: Oftentimes, you need to match with two criteria, one for the type and the other for some property. Also, you rarely want to create a collection of various types for subsequent operations.

3) The "max" parameter should be renamed to "limit" (alternatively: preserve "max" as equivalent to the new "limit", but use only  "limit" in wiki and tutorials).

Reason: A limit of 0 is easier to understand as meaning "no limit". Also, many people are familiar SELECT and LIMIT in SQL and would find this parameter very easy to understand. 

4) For sake of consistency, also introduce "limit" to all other functions that currently use "count" in a way that actually means "limit": FLIP, MOVE, MOVEXY, ROTATE (don't change "count" in CLICK because it does not mean a limit here).

**Comment by ArnoldSmith86** [comment]
I think adding `in` is better because we have array functions now so maybe someone actually wants to compare with arrays (not sure if it would work without changes though because it would be different instances).

**Comment by ArnoldSmith86** [comment]
The `type` also has a problem: the default should be `null` but BasicWidgets also have `type == null`.
