### ISSUE TITLE
Writable playerColor does not work

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#611]
#560 made playerName and playerColor writable.  Name works.  However, I cannot get color to work on production server.  Have tried:
```
"var playerColor = 'red'" 
"var playerColor = red"  
"var playerColor = '#ff0000'"  
"var playerColor = #ff0000"  
```

**Comment by bjalder26** [comment]
The hashtag is the problem.

 "var playerColor = '\\u0023ff0000'",
   
 or pass it in as a variable.
  
 "clickRoutine": [
    "var playerName = 'Bob'",
    "var playerColor = ${PROPERTY color}"
  ],
  "color": "#5077e4"

**Comment by 96LawDawg** [comment]
Oh yeah.  I forgot about the limit on characters in dynamic expressions.  Someone want to take on issue #471?  That would solve some of these problems.

**Comment by 96LawDawg** [comment]
So I will close this issue since it DOES work, but not in a nice, clean way.

**Comment by robartsd** [comment]
We need to whitelist the hashtag. Format must be hex (this is required for the new player color functions).
