### ISSUE TITLE
JSON Editor Anomaly so strange I can't describe it. 

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#618]
In my poker room that uses playerNames for certain seating and dealing things, if I personally try to occupy two seats, then simply use the JSON editor to drag something using ctrl-mouse, it triggers a card to be dealt.  This only happens in the latest version of my room, so clearly I did something odd.  But it only happens when I try to occupy multiple seats for testing.  But simply dragging a widget (doesn't matter which one, even an empty brand new one) should not trigger anything in the room to happen.  Video of normal behavior:

https://user-images.githubusercontent.com/76912527/123689520-ed7ae100-d818-11eb-850a-8d09fd22a02b.mp4

Video of strange behavior:

https://user-images.githubusercontent.com/76912527/123689554-f5d31c00-d818-11eb-8b96-0036c2ed94ec.mp4

**Comment by bjalder26** [comment]
The JSON editor works in mysterious ways.
![image](https://user-images.githubusercontent.com/78324099/123745434-e7ffb400-d875-11eb-89c4-18a2f2ee953d.png)

**Comment by ArnoldSmith86** [comment]
Where can I try to reproduce it? I just tried in the room of your video but it didn't happen for me.

**Comment by 96LawDawg** [comment]
> Where can I try to reproduce it? I just tried in the room of your video but it didn't happen for me.

Yeah, I changed the room since then.  But you can do it here:  https://virtualtabletop.io/aojx.  It will only work once, then you have to reset it.  Use the next to last variant called "playerName and Color" again.

**Comment by bjalder26** [comment]
> > The JSON editor works in mysterious ways.
> 
> How do you get HTML there again?

Just type it in.  The JSON editor is a div that expresses HTML. 
![image](https://user-images.githubusercontent.com/78324099/123812186-7f3a2b00-d8b9-11eb-9cf8-49d9de3e6c11.png)
Pressing enter causes it to update and express the html.

**Comment by bjalder26** [comment]
> > Where can I try to reproduce it? I just tried in the room of your video but it didn't happen for me.
> 
> Yeah, I changed the room since then. But you can do it here: https://virtualtabletop.io/aojx. It will only work once, then you have to reset it. Use the next to last variant called "playerName and Color" again.

I took a look, and the card had a z value of  9921.  So I reduced the z value, and it did not happen.  I reset the room and put a button in there that will reduce the z value by 5k.  Please check and see if that is what was causing the problem.  I suspect this is some very strange result of the z values getting reset.

**Comment by 96LawDawg** [comment]
When I reset the room, the button was gone (button wasn't saved in the variant).  I tried creating a button to do the same thing but I don't think it worked.  I still get the problem, but maybe because my z button didn't work.

**Comment by bjalder26** [comment]
> When I reset the room, the button was gone (button wasn't saved in the variant). I tried creating a button to do the same thing but I don't think it worked. I still get the problem, but maybe because my z button didn't work.

This is baffeling.  The best clue I can give is that it appears to have something to do with layers.  When I changed the layer of a button then moved it, it did not trigger the card, but the next button I moved did.  When I changed the layer of every item on layer -1 to layer 10, then the card was triggered.  When I changed the layer from -1 to 10 and changed their z values to 1 at the same time, then it was not triggered, but then when I started clicking on the cards, it was triggered.

Does anything have an enter or exitRoutine that might be triggering when cards change layer or something like that?

**Comment by 96LawDawg** [comment]
There are only a few `enterRoutines` and `exitRoutines` in the entire room and they have to do with clicking a button and setting the y value of a widget.

**Comment by bjalder26** [comment]
Now that I've seen more of the room.  I have to wonder if this had something to do with the timers.  Perhaps one of the timers had stopped, but did not properly restart when people reentered the room, then an error caused the room to refresh, thus restarting the unpaused timer.

**Comment by 96LawDawg** [comment]
Maybe, but I don't think so.  In any event, the behavior is now gone probably due to some changes in the JSON Editor, so I'll close this issue.
