### ISSUE TITLE
Improvements to FLIP

### ISSUE THREAD

**Issue by larkob** [ArnoldSmith86/virtualtabletop#62]
1) Add "reverse" as a third option to the faceCycle property of widgets. The widget should then be flipped to the _previous_ face instead of the next.

Reason: This is useful for multi-faced widgets like dice, as some games need to flip it to previous face rather than always to the next.

2) Allow FLIP to temporarily override the widgets faceCycle property by adding a faceCycle parameter:
```
{
    func: “Flip”,
    holder: "<holderId>",
    faceCycle: "random"
}
```

Reason: In some games, the widget's faceCycle setting may not be valid for all situations in which a FLIP should be made.

**Comment by UltimateGeek** [comment]
The opposite of reverse is forward, and suggests there is more than just one more in order to flip to. Perhaps “prior” would be a better name for the additional option?

**Comment by larkob** [comment]
Perhaps we could rename faceCycle "ordered" to "next" and then the logical opposite would be "previous". Not sure about implications for import from pcio.
