### ISSUE TITLE
custom functions in pile overlay

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#621]
i would like to be able to set custom functions that i can writen in the JSON editor to piles. something like put the top card at the bottom of the deck or mix the top card into the deck without shuffeling the entire thing. or there should be at least some more operations ne can do with piles that you can hide if you don't need them for a specific game.

**Comment by robartsd** [comment]
I like this idea. We could have a way to define a routine that would get added to all piles in the room as an option in the overlay.

**Comment by 96LawDawg** [comment]
Closed by #646 and #905 as the user can now do this customization.
