### ISSUE TITLE
JSON editor lacks Icons

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#630]
@rogerl50 complained to me about this

![image](https://user-images.githubusercontent.com/73476656/123835763-50cf4680-d8df-11eb-839b-c0981f3d49b9.png)

so here is my suggestions:
- Z: https://fontawesome.com/v5.15/icons/search?style=solid 
![image](https://user-images.githubusercontent.com/73476656/123837268-077ff680-d8e1-11eb-9944-adf2a78d2d51.png)

- C: https://fontawesome.com/v5.15/icons/file-export?style=solid 
![image](https://user-images.githubusercontent.com/73476656/123837294-1070c800-d8e1-11eb-92e2-688b99d1e178.png)

- M: https://fontawesome.com/v5.15/icons/terminal?style=solid 
![image](https://user-images.githubusercontent.com/73476656/123837319-18c90300-d8e1-11eb-8778-f5b13166e55b.png)

- S: https://fontawesome.com/v5.15/icons/eye?style=solid 
![image](https://user-images.githubusercontent.com/73476656/123837346-1ff01100-d8e1-11eb-8464-558ecf7d4409.png)

- T: https://fontawesome.com/v5.15/icons/code-branch?style=solid 
![image](https://user-images.githubusercontent.com/73476656/123837377-27171f00-d8e1-11eb-9a21-3426751e7c72.png)

- A: https://fontawesome.com/v5.15/icons/plus?style=solid (same as in side bar) 
![image](https://user-images.githubusercontent.com/73476656/123837400-2da59680-d8e1-11eb-951e-9496839a8503.png)

- D: https://fontawesome.com/v5.15/icons/copy?style=regular 
![image](https://user-images.githubusercontent.com/73476656/123837420-34340e00-d8e1-11eb-9be3-28313677bfb0.png)

- R: https://fontawesome.com/v5.15/icons/trash-alt?style=solid 
![image](https://user-images.githubusercontent.com/73476656/123837444-39915880-d8e1-11eb-813d-df62fdb4b14b.png)

- F: https://fontawesome.com/v5.15/icons/edit?style=regular (same as in side bar) 
![image](https://user-images.githubusercontent.com/73476656/123837469-4150fd00-d8e1-11eb-8d4c-6285f7a58cd4.png)

- I: https://fontawesome.com/v5.15/icons/sort-amount-up-alt?style=solid  
![image](https://user-images.githubusercontent.com/73476656/123837487-4746de00-d8e1-11eb-9196-c252dbc12109.png)

edit: added images

**Comment by 96LawDawg** [comment]
Well, the stuff that is there is Unicode and we've mostly all agreed that is not a best practice.  I'm not sure about (T) tree, but everything else is fine.  If I come up with a better suggestion, I'll post.  But I can live with tree as is.

**Comment by RaphaelAlvez** [comment]
> I'm not sure about (T) tree
Me neither that was the best I found so far. I'm open for suggestions

**Comment by robartsd** [comment]
I like https://thenounproject.com/term/tree-view/900283/ or we can roll our own similar.

**Comment by rogerl50** [comment]
The icons from your screenshot actually look OK. Mine look like this:
<img width="315" alt="Screen Shot 2021-06-26 at 6 43 54 PM" src="https://user-images.githubusercontent.com/63379656/123841504-a30f6800-d8dd-11eb-93b7-d09f6a816fe4.png">
which makes the images over T and A pretty much invisible.

**Comment by robartsd** [comment]
I think I'd choose file-import for C rather than file-export.
https://fontawesome.com/v5.15/icons/file-import?style=solid

**Comment by RaphaelAlvez** [comment]
> I like https://thenounproject.com/term/tree-view/900283/ or we can roll our own similar.
> ![image](https://user-images.githubusercontent.com/368796/123840643-6df61c00-d8c3-11eb-8485-95ee6782f8ff.png)

I'm not very motivated to make an SVG for this.

this was the best I could find on fontawesome
>but I like this the most:
>https://fontawesome.com/v5.15/icons/sitemap?style=solid

about:
>I think I'd choose file-import for C rather than file-export.
>https://fontawesome.com/v5.15/icons/file-import?style=solid

you are right I misread this should be an import Icon

**Comment by bjalder26** [comment]
Something like this might be nice, but it is not a free icon.
![image](https://user-images.githubusercontent.com/78324099/123981187-c2fb6600-d987-11eb-9452-3e7254345458.png)

**Comment by RaphaelAlvez** [comment]
> Something like this might be nice, but it is not a free icon.
> ![image](https://user-images.githubusercontent.com/78324099/123981187-c2fb6600-d987-11eb-9452-3e7254345458.png)

was it on fontawesome? a link would be helpful

**Comment by RaphaelAlvez** [comment]
btw you all realise that there is an on hover description right? the icons don't NEED to be perfect
and we can always change it later without breaking anything

**Comment by robartsd** [comment]
> > I like https://thenounproject.com/term/tree-view/900283/ or we can roll our own similar.
> > ![image](https://user-images.githubusercontent.com/368796/123840643-6df61c00-d8c3-11eb-8485-95ee6782f8ff.png)
> 
> I'm not very motivated to make an SVG for this.

The one I linked to is available under CCBY

**Comment by bjalder26** [comment]
> > Something like this might be nice, but it is not a free icon.
> > ![image](https://user-images.githubusercontent.com/78324099/123981187-c2fb6600-d987-11eb-9452-3e7254345458.png)
> 
> was it on fontawesome? a link would be helpful
Hopefully, this link will show it.
https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=list&s=solid

**Comment by RaphaelAlvez** [comment]
> > > I like https://thenounproject.com/term/tree-view/900283/ or we can roll our own similar.
> > > ![image](https://user-images.githubusercontent.com/368796/123840643-6df61c00-d8c3-11eb-8485-95ee6782f8ff.png)
> > 
> > I'm not very motivated to make an SVG for this.
> 
> The one I linked to is available under CCBY

Ok so I'll make modifications ok this one to better fit the other ones

**Comment by robartsd** [comment]
> > > > I like https://thenounproject.com/term/tree-view/900283/ or we can roll our own similar.
> > > > ![image](https://user-images.githubusercontent.com/368796/123840643-6df61c00-d8c3-11eb-8485-95ee6782f8ff.png)
> > > 
> > > 
> > > I'm not very motivated to make an SVG for this.
> > 
> > 
> > The one I linked to is available under CCBY
> 
> Ok so I'll make modifications ok this one to better fit the other ones

Is it just that you want rounded corners?

**Comment by bjalder26** [comment]
> Is it just that you want rounded corners?

Personally, I like how the one I posted looks kind of like a list, and wouldn't mind the one below either.  When you think of the top button you probably think of the concept of it going to the top (which may be more accurate), but I tend to think of it as showing a list of widgets.  The one I posted above kind of communicates both things.  I don't have a strong opinion on this subject though.  Just trying to find something everyone is happy with.

![image](https://user-images.githubusercontent.com/78324099/125176139-c3b9a680-e196-11eb-9d45-483a7327746e.png)
https://fontawesome.com/v6.0/icons/list?s=solid

**Comment by robartsd** [comment]
I agree that the list aspect is nice. Perhaps I'll make one.

**Comment by robartsd** [comment]
How about this:
```svg
<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' viewBox='0 0 16 16' fill='currentColor'>
  <rect x='1' y='1' width='4' height='4' rx='1' />
  <rect x='6' y='2' width='9' height='2' rx='1' />
  <rect x='3' y='6' width='4' height='4' rx='1' />
  <rect x='8' y='7' width='7' height='2' rx='1' />
  <rect x='3' y='11' width='4' height='4' rx='1' />
  <rect x='8' y='12' width='7' height='2' rx='1' />
</svg>
```

**Comment by 96LawDawg** [comment]
Just to save other people the trouble of actually getting it to draw on the screen ....

<img width="570" alt="New Icon" src="https://user-images.githubusercontent.com/76912527/125211468-2cbf1e00-e26c-11eb-9983-69f715c7559a.png">

I like it.  Thumb's up.

**Comment by bjalder26** [comment]
I like it too.  I think it will look nice really small as well.

**Comment by robartsd** [comment]
> Just to save other people the trouble of actually getting it to draw on the screen ....

Thanks, I was having trouble figuring out how to get an image in here again, then got interrupted.
