### ISSUE TITLE
Improvements to GET

### ISSUE THREAD

**Issue by larkob** [ArnoldSmith86/virtualtabletop#65]
GET currently has only two aggregations: "first" and "sum". Some additional useful aggregations would be:

1. last (property value of last widget in collection)
2. min (lowest property value of widgets in collection)
3. max (highest property value of widgets in collection)
4. average (average property value of widgets in collection)
5. median (median property value of widgets in collection)

GET should also allow to make use of the holder parameter instead of making a prior selection, for sake of consistency and also because it seems quite useful to be able get an aggregated property value of widgets in a holder.

**Comment by robartsd** [comment]
I think a good generalization for all routines that act on collections would be to be able use either an explicit collection or a holder that is a shortcut for the collection of items in the holder.

**Comment by ArnoldSmith86** [comment]
Another aggregation function should be `array` that just returns all the values as one array.

**Comment by robartsd** [comment]
I'll work on adding aggregations (last, min, max, average, median, array).
