### ISSUE TITLE
Using CLONE/properties to set x/y to zero using a variable doesn't work

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#653]
If you clone a widget, and try to use the `properties` of `CLONE` to set the x or y to zero using a variable, then instead of setting the x or y to zero, the clone will simply inherit the x or y of the widget it is cloned from.

Using CLONE/properties to set x or y to zero using the digit 0 instead of a variable works.  So does setting the x or y to zero after the CLONE has been created.

This room demonstrates this issue.
https://virtualtabletop.io/2uk2

In the debug it will even say something like this when a variable is used:
OPERATION: 
{
  "func": "CLONE",
  "source": "thisButton",
  "properties": {
    **"x": 0**
  },
  "count": 1,
  "xOffset": 0,
  "yOffset": 0,
  "collection": "DEFAULT"
}

However, the clone will inherit the x value of the widget it is cloned from instead.

**Comment by rogerl50** [comment]
@ArnoldSmith86 In the code
```
             if(!parent || !widgets.get(parent).get('alignChildren')) {
                await cWidget.set('x', (a.properties.x || w.get('x')) + a.xOffset * i);
                await cWidget.set('y', (a.properties.y || w.get('y')) + a.yOffset * i);
                await cWidget.updatePiles();
              }
```
I believe the line setting x should be
```
await cWidget.set('x', a.xOffset *i + (a.properties.x == null) ? w.get('x') : a.properties.x
```
and similarly for y.
