### ISSUE TITLE
Pressing enter after digit in label does not trigger textChangeRoutine

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#659]
Inputting a digit or letter in a label triggers the textChangeRoutine.  Pressing enter after inputting a letter triggers the textChangeRoutine.  However, hitting enter after a letter does not trigger the textChangeRoutine.  I believe it used to trigger it, but does not now.

This room has a label that moves right every time the textChangeRoutine is triggered.
https://virtualtabletop.io/Labels

The \n will not update in the JSON editor until after another letter or number is pressed.

If the window is refreshed after pressing a number, then enter, then only the number will remain.  I have to wonder if this is an undefined delta.text or if the issue is with setText.

**Comment by 96LawDawg** [comment]
That only happens in the JSON editor though, right?  It seems to work fine if you don't have the JSON editor open.  If you think this is a recent change, I wonder if it has to do with #645?  Just a guess.
