### ISSUE TITLE
ROTATE should allow to set wigets to specific rotation

### ISSUE THREAD

**Issue by larkob** [ArnoldSmith86/virtualtabletop#66]
ROTATE should have a mode with "set" or "add" (defaults to "add" for backwards compatibility)

Example for setting the rotation of widgets within holder to 90 degrees (irrespective of their current rotation):
```
{
    func: “ROTATE”,
    holder: "<holderId>",
    angle: 90,
    mode: "set"
}
```

Reason: Currently, ROTATE only allow to change the current rotation by adding a value. It would be even more useful if ROTATE could also set the rotation of widgets to a particular value, for instance to align cards that may have been various individual rotation property values.

**Comment by RaphaelAlvez** [comment]
Why not inc to keep like the other function?

**Comment by larkob** [comment]
"inc" (or "add") is how ROTATE currently works. What's missing is "set"

**Comment by RaphaelAlvez** [comment]
Ok agree if no there is no inc then just use add
