### ISSUE TITLE
Conditions in clickRoutines

### ISSUE THREAD

**Issue by larkob** [ArnoldSmith86/virtualtabletop#67]
1) Add special parameter "if" to operations which only executes the operation if a condition is met

```
{
  "func": "FLIP",
  "holder": "<holderID>",
  "face": 0,
   "if": "myVariableName"
}
```

Reason: Currently, the only option to make conditional operations in clickRoutines is to use the skip parameter, which prevents an operation from executing if the value evaluates to `true`. However, oftentimes the opposite is needed: An operation should only be executed if a certain condition is met. When "if" and "skip" are used in parallel, "skip" should override "if".

2) Introduce a new function JUMP which jumps to a particular routine without losing the clickRoutine's state (variables and collections). Like any other operation, it can be combined with "if" and "skip". The routine would simply be defined as a custom property of the button widget.

Probably not the most realistic example, but should help to illustrate:

```
{
  "type": "button",
  "text": "myButton",
  "clickRoutine": [
    {
        "func": "INPUT",
        "header": "A header text for the overlay.",
        "fields": [
           {
               "type": "checkbox",
               "label": "Do you want to shuffle?",
               "variable": "shuffle",
               "value": true
           }
        ]
    },
    {
      "func": "JUMP",
      "routine": "doShuffle",
      "if": "shuffle"
    },
  ],
  "doShuffle": [
    {
      "func": "SHUFFLE",
      "holder": "<holderID>",
    }
  ],
  "x": 758,
  "y": 721,
  "z": 11,
  "id": "2zye",
  "layer": 1
}

```

Reason: Conditional branching is extremely useful but quite difficult to implement. A "jump" is one of the easiest programming concepts and together with "if" and "skip" could accomplish most of what "if/else" conditions can do.

**Comment by robartsd** [comment]
I like the idea of named routines as custom properties. Should it be called "jump"? To me "jump" is a goto where execution transfers to the other routine and never comes back. We could use "call" or "doRoutine" to call a subroutine and have the current routine contine once the called routine is completed.

**Comment by ArnoldSmith86** [comment]
I second a rename from `JUMP` to `CALL`.

**Comment by larkob** [comment]
A CALL would be very useful, though we'd still need a JUMP with no return option. Let's give this function a `continue` parameter. If that evaluates to true, then the clickRoutine continues, otherwise it doesn't. It should default to false.

**Comment by larkob** [comment]
I you still prefer CALL as a name for the function, the continue parameter should default to true.

**Comment by ArnoldSmith86** [comment]
I think it would be very nice if the `JUMP`/`CALL` operation also supports a `variables` parameter so you can easily set variables on top of inheriting the ones currently set.

**Comment by ArnoldSmith86** [comment]
The PR only implemented parts of this. An `IF` is still missing.
