### ISSUE TITLE
Deck editor doesn't support \n

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#673]
you can add it in JSOn but the editor breaks it

**Comment by bjalder26** [comment]
Are we talking about dynamic properties in the faceTemplate for which values can be entered in Edit deck?

**Comment by bjalder26** [comment]
I assume it is because it is `<input>` type text. 

![image](https://user-images.githubusercontent.com/78324099/125351635-eb8b4480-e325-11eb-81b7-9cb3c3a68ceb.png)
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input

**Comment by ArnoldSmith86** [comment]
We should probably just display them as `\n` in the textbox? Which of course isn't as easy as it sounds...

**Comment by robartsd** [comment]
> We should probably just display them as `\n` in the textbox? Which of course isn't as easy as it sounds...

Would we also all entry of \n to insert a line break?

**Comment by ArnoldSmith86** [comment]
I think a pretty simple solution would be to use `JSON.stringify` and `JSON.parse` and just not to display the enclosing quotes. Maybe replacing any `\` that is not followed by valid JSON escapes by `\\`.

I'm pretty sure that newlines aren't the only thing the deck editor messes up though. It might also add empty strings to `cardTypes` and it probably converts any non-string values to strings.

The question is how much time we want to invest here instead of building the _proper_ deck editor. Although we will probably face the same problems there.

**Comment by bjalder26** [comment]
Why not use a textarea or div?

**Comment by bjalder26** [comment]
> It might also add empty strings to `cardTypes` 

It does, and it is easy enough to convert the empty strings to null values, but is that preferable, or should the dynamic property be deleted from the cardTypes?

![image](https://user-images.githubusercontent.com/78324099/127747970-562762de-a85f-414d-944f-3367777b65d4.png)

**Comment by ArnoldSmith86** [comment]
The thing is: it shouldn't change _anything_ in the deck if you just add cards. Or if you edit one specific card type, _everything_ else should stay untouched.

**Comment by bjalder26** [comment]
> The thing is: it shouldn't change _anything_ in the deck if you just add cards. Or if you edit one specific card type, _everything_ else should stay untouched.

I've attempted to address that.  I'm sure a revamped deck editor would be a better solution, but I doubt there is anything I could contribute to that process except testing it when it is done.

As far as it converting non-string values to strings, my current opinion is that if we are setting it to the text type input, then everything is a string.  So, I haven't tried to fiddle with that.  I figure that once something has been input into a text input, then it might become difficult to determine the intent of the person (e.g. did they want 'true' or '123' to be a string?)

However, I think it might be beneficial for it to be able to support other input types.  I figure there could also be `"type": "number",` object in faceTemplates, which could be a number type input (if limited to integers) or another text type input that was converted to a float.  I also figure there could also be a `"type": "boolean",` which could be a radio type input or a text type input.  However, if the boolean is text, then we would need to deal with typos somehow.

Alternatively, I suppose we might be able to convert any number to a string, and true/false to booleans, with the exception being when they input them with quotation marks (perhaps that was your point above).  That seems fairly easy and workable.  I think the only odd thing about that would be that anything that isn't a number, true, or false, would be converted to a string regardless of whether or not it had quotation marks, but I don't see that as a negative.
