### ISSUE TITLE
cards disappearing when editing label

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#678]
the label in question ist from a counter. this behaviour appeared while manually editing the label as well as clicking the +/- buttons. it seemed as if the label would trigger a recall so the cards from a friend (essentially two separate decks where the cards were mixed in a separate holder by hand) disappeared from his draw pile as well as all the cards in play on the board. i activated tracing. is this enough info? idk

**Comment by bjalder26** [comment]
Date: 7/14
Game:  smash up

**Comment by rogerl50** [comment]
Is this issue reproducible? If so, can someone post the steps to make it happen?

**Comment by Ingegneus** [comment]
Nope I never encountered this issue again

**Comment by robartsd** [comment]
Are you sure it wasn't a conflict resolution reset?

**Comment by Ingegneus** [comment]
I am very sure. But since I can't recreate it and it never happened again, it's quite useless

**Comment by rogerl50** [comment]
Well, then perhaps you should just close it. Thanks.
