### ISSUE TITLE
Cards show width and height

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#680]
When editing cards in the JSON editor they show width and height as though they are set in the widget. It's because they differ from the default values of the type card but they are probably set in cardDefaults so they should be grey.

**Comment by robartsd** [comment]
I've never set x or y in `cardDefaults` since ordinarily cards have their x and y set in play.

**Comment by bjalder26** [comment]
Did you mean width and height?

**Comment by robartsd** [comment]
`width` and `height` make much more sense

**Comment by ArnoldSmith86** [comment]
> Did you mean width and height?

I did.

**Comment by bjalder26** [comment]
It appears that setting a width or height on the card will override the width or height in cardDefaults (width and height in faceTemplates appears to do nothing).  Also a width or height in cardTypes overrides the width or height in cardDefaults.  If the card doesn't have a width or height set (or if you delete it), then it will show the width or height it is inheriting from either cardDefaults or cardTypes.

Maybe a simple solution would be to have a separate jeOrder for cards that doesn't have an asterisk by width and height.
