### ISSUE TITLE
Add fixed placement for buttons in Deck Editor

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#682]
The bottom buttons in the deck editor scroll out of view if there are enough cards.  It would be more convenient to edit decks if those buttons had a fixed placement and did not scroll when you move the scrollbar.

![image](https://user-images.githubusercontent.com/78324099/126054982-940275f0-4e52-4929-b32a-62e271fb5c92.png)

**Comment by RaphaelAlvez** [comment]
I did test that but it was very bad on mobile

we can change that if people don't mind

**Comment by bjalder26** [comment]
> I did test that but it was very bad on mobile
> 
> we can change that if people don't mind

Oh, well then maybe this wouldn't be a good idea.  I thought it would be more convenient, but if it is a problem on mobile, then maybe it isn't worthwhile.

**Comment by RaphaelAlvez** [comment]
we can definitely look for solutions. Just saying it is not just that simple.
We can maybe add some media query

**Comment by robartsd** [comment]
> we can definitely look for solutions. Just saying it is not just that simple.
> We can maybe add some media query

I think a media query based on viewport height would be a good idea.

**Comment by 96LawDawg** [comment]
No longer relevant with the new UI.
