### ISSUE TITLE
Client crash when from dynamic expression click duplicate, then select widget

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#687]
In the JSON editor: 
Clicking inside a dynamic expression => clicking on duplicate widget => pressing ctrl => clicking on the same widget => releasing ctrl 
causes the client to crash

This error occurs both when I click on duplicate widget, and when I release the ctrl.
![image](https://user-images.githubusercontent.com/78324099/126193198-65c7a60f-cf0c-44d6-9fd0-5b14575f71dd.png)

**Comment by 96LawDawg** [comment]
I cannot duplicate this problem following the steps above.  Should consider closing unless someone else can.

**Comment by rogerl50** [comment]
I could not reproduce either.

**Comment by 96LawDawg** [comment]
Cannot be duplicated.  Closed.
