### ISSUE TITLE
Creating room from link need update and documentation

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#70]
creating a room from link disable the game list and public library.
Probably would be better to redirect the player to a normal URL once the link has been processed

![image](https://user-images.githubusercontent.com/73476656/104112311-15f33b00-52cc-11eb-9d59-0d28126a2f1d.png)

this feature also need some kind of documentation or generator

**Comment by ArnoldSmith86** [comment]
Documentation is now here: https://github.com/ArnoldSmith86/virtualtabletop/wiki/URL-Properties

I gotta fix some bugs though, it seems.

**Comment by rogerl50** [comment]
That's great, thanks. It would be nice if there were a discussion about how to get a link to a specific variant as well.
