### ISSUE TITLE
Default deck card back slow to load

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#702]
The XML file for the default deck card back looks really complicated with a bunch of transform/translate instructions.  It seems to cause a minor lag when cards are pulled from a deck.  Below shows about 1/5th of the xml.  I suggest we create a less-complicated svg for the default deck, and possibly even replace the current file with it.

![image](https://user-images.githubusercontent.com/78324099/127514205-97c286d6-d4c0-4976-b003-9767cc1c2566.png)

**Comment by robartsd** [comment]
Here's an optimized version using my go to [SVG optimization](https://jakearchibald.github.io/svgomg/) tool:
[2B.zip](https://github.com/ArnoldSmith86/virtualtabletop/files/6903850/2B.zip)

The zipped size is nearly the same, but the decompressed size is about 37% the original size (those transform commands zip up well).

**Comment by RaphaelAlvez** [comment]
That van be changed directly into files and make a PR. Good job figuring it out
