### ISSUE TITLE
Zoom Problem

### ISSUE THREAD

**Issue by Casbuild** [ArnoldSmith86/virtualtabletop#71]
In chrome on my mac, with a screen resolution of 1650x1050 or lower, if I use 2 finger zoom: the page becomes unusable and therefore needs to be reloaded once I zoom out.

Before trying to zoom:
![Screen Shot 2021-01-09 at 5 50 02 PM](https://user-images.githubusercontent.com/77217120/104112453-e6303d00-52a3-11eb-9a90-d183c2e880fa.png)

After trying to zoom:
<img width="1248" alt="Screen Shot 2021-01-09 at 5 53 06 PM" src="https://user-images.githubusercontent.com/77217120/104112458-ed574b00-52a3-11eb-8db5-ed9ab223a3a0.png">

**Comment by UltimateGeek** [comment]
1. What version of Chrome?
2. What other browsers have you tried on Mac that didn’t exhibit this behavior?

**Comment by UltimateGeek** [comment]
Please provide a room or vtt file that can be used to reproduce this issue.

**Comment by Casbuild** [comment]
> Please provide a room or vtt file that can be used to reproduce this issue.

It happens to every room but here is an example of one it happens in: [https://virtualtabletop.io/omvz](https://virtualtabletop.io/omvz) . I am using Version 87.0.4280.88 (Official Build) (x86_64) of chrome. Firefox and Safari did not have this problem. It sometimes can recover and fix itself but not always. It does not effect other players

**Comment by UltimateGeek** [comment]
Yes, I can reproduce it. Interesting that it happens in Chrome but not Chromium.

It appears to me that Chrome is dropping the events to repaint.

I am able to get it to repaint the room successfully without having to reload the page:
1. Zoom in & then out, and observe the problem
2. Zoom part way in. Look for all the visible items repainting fully. If they don't zoom out partially, and then in partially again until they do
3. Then zoom all the way out, and the full room is visible.

Can you try that @Casbuild ?

**Comment by UltimateGeek** [comment]
@ArnoldSmith86 please view [this video](https://youtu.be/UaEOflbo0ZU) that demonstrates the problem, and then let me know how you would debug it.

**Comment by ArnoldSmith86** [comment]
Does it even run any of our code while doing that? Is `window.onresize` being fired?

Looks to me like a Chrome bug and should be reported there. If you can find a workaround, fine..

**Comment by Casbuild** [comment]
> Yes, I can reproduce it. Interesting that it happens in Chrome but not Chromium.
> 
> It appears to me that Chrome is dropping the events to repaint.
> 
> I am able to get it to repaint the room successfully without having to reload the page:
> 
> 1. Zoom in & then out, and observe the problem
> 2. Zoom part way in. Look for all the visible items repainting fully. If they don't zoom out partially, and then in partially again until they do
> 3. Then zoom all the way out, and the full room is visible.
> 
> Can you try that @Casbuild ?

It seems like that works. At that point it may just be easier to reload the page though. @ArnoldSmith86 it could be a chrome bug, but I have never experienced this problem on any other site and I use this method to zoom quite frequently.

**Comment by bjalder26** [comment]
This issue can be recreated by adding a ton of cards to a room that has a CSS radial-gradient background.

https://virtualtabletop.io/zszm

It seems that it is a rendering problem when there are a LOT of cards being zoomed.

**Comment by bjalder26** [comment]
It appears to be the `will-change: transform;` that is causing this issue.  You can compare these 2 rooms on the production server:

https://virtualtabletop.io/zszm
https://virtualtabletop.io/p2z5

To the 2 games in this room (on the PR #400 server).

http://212.47.248.129:3400/Interitus

I suggest we merge PR #400.

**Comment by robartsd** [comment]
Lots of widgets with "will-chage" set could very well be causing issues. From [https://developer.mozilla.org/en-US/docs/web/css/will-change](url)

> The will-change CSS property hints to browsers how an element is expected to change. Browsers may set up optimizations before an element is actually changed. These kinds of optimizations can increase the responsiveness of a page by doing potentially expensive work before they are actually required.

> Important: will-change is intended to be used as a last resort, in order to try to deal with existing performance problems. It should not be used to anticipate performance problems.

> Don't apply will-change to too many elements. The browser already tries as hard as it can to optimize everything. Some of the stronger optimizations that are likely to be tied to will-change end up using a lot of a machine’s resources, and when overused like this can cause the page to slow down or consume a lot of resources.
