### ISSUE TITLE
Support URL Prefix for http and websocket

### ISSUE THREAD

**Issue by tsankuanglee** [ArnoldSmith86/virtualtabletop#712]
Could we add support for `process.env.HTTP_URL_PREFIX` (for http), and `process.env.WS_URL_PREFIX` (for websocket)?

I'm new to the code base but I'm wondering:

1. Can we just add these to `app.get/put/post/use/etc` in `server.mjs` (either with concatenation or express Router)? Any other places?
2. Can we pass these to the client, and add to URL related properties in `client/`? Do we make another call? Or can we include these variables in some initial call?
3. Any other places, e.g. save function/format?

Thanks for this awesome project!

**Comment by bjalder26** [comment]
That's an interesting question.  You may have to wait a while for a response though.  I think there are only a couple or a few of us that can answer that question.

**Comment by tsankuanglee** [comment]
This turned out to be easier than I thought. I was able to move the app under a prefix without many changes.

This is what I did:

1. For the server, I used express Router to add a global prefix.
2. For the client code, I passed the PREFIX variables to the browser via `room.html` by modifying `minify.mjs` to replace `{{HTTP_URL_PREFIX}}` in the html template. (I could do the same thing for the CSS files.)

If there are no objections from the dev, I can start working on a PR.

**Comment by bjalder26** [comment]
>  Could you please explain it so a non-coder like me understands?
I believe what he proposes it to make it possible to have urls like https://interitus/virtualtabletop.io/checkers

> If there are no objections from the dev, I can start working on a PR.
Personally I think it is a good idea, and if it isn't too much work to do the PR then I would go ahead.  We somewhat work as a committee though, so there is no guarantee that it won't get voted down in the end.  However, if you get a PR done, then we can test it and make sure there aren't any problems.

**Comment by tsankuanglee** [comment]
> I don't know what your code changes do. Could you please explain it so a non-coder like me understands?

Without the changes, we can only host the server under the root path of a server, e.g. `https://myGameServer.com/`. It means we need a dedicated domain name to host the server.

 With the changes, it is possible to host the game under a directory, e.g. `https://myGameServer.com/virtualTabletop`, allowing the server for other uses under other directories.

**Comment by ArnoldSmith86** [comment]
I added a comment to the referenced library issue. Should have probably posted it here.
