### ISSUE TITLE
JSON Editor takes focus when first opened

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#723]
If you have a room with a label and you open the JSON Editor but do not CTRL-select a widget, then when you start to type in the label, one letter goes into the label and the rest go into the JSON Editor.  This is not a problem if you CTRL-select any widget in the room.  It's only a problem when you first open the editor.

**Comment by bjalder26** [comment]
Does #683 address this issue?

**Comment by bjalder26** [comment]
This one seems complicated.  I think it might require a windows variable that gets set and deleted.

![image](https://user-images.githubusercontent.com/78324099/130134483-fe18c147-2b85-4cf0-b03f-e94cf14dad1d.png)

**Comment by bjalder26** [comment]
I added a fix for this issue to PR #683, and I am linking them.

**Comment by 96LawDawg** [comment]
Not sure which change to the JSON Editor resolved this, but this error no longer occurs.  Closed.
