### ISSUE TITLE
Scaled cards don't stack or drop in holders as expected

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#729]
Large card has a scale of 2.0.  Holder is oversized by doubling the height and width.
![image](https://user-images.githubusercontent.com/78324099/129452471-e8abbf80-98c1-4f25-a8be-8482ec508f3b.png)

When the scale is changed the x/y doesn't change & doesn't represent the upper left corner of the card anymore.  I the issue with borders is also related #664.

This issue can be seen in the following room: https://virtualtabletop.io/Issues
Game: #729 Scaled cards

This is a workaround that seems to work for holders.
  "enterRoutine": [
    {
      "func": "GET",
      "property": "type",
      "collection": "child",
      "variable": "type"
    },
    {
      "func": "IF",
      "operand1": "${type}",
      "relation": "==",
      "operand2": "pile",
      "thenRoutine": [
        {
          "func": "GET",
          "property": "id",
          "collection": "child",
          "variable": "childId"
        },
        {
          "func": "SELECT",
          "property": "parent",
          "value": "${childId}",
          "collection": "dropped"
        }
      ],
      "elseRoutine": [
        {
          "func": "SELECT",
          "property": "id",
          "value": null,
          "relation": "!=",
          "source": "child",
          "collection": "dropped"
        }
      ]
    },
    {
      "func": "GET",
      "property": "scale",
      "collection": "dropped",
      "variable": "scale"
    },
    {
      "func": "GET",
      "property": "width",
      "collection": "dropped",
      "variable": "width"
    },
    {
      "func": "GET",
      "property": "height",
      "collection": "dropped",
      "variable": "height"
    },
    "var diff = ${scale} - 1",
    "var halfWidth =  ${width} / 2",
    "var halfHeight =  ${height} / 2",
    "var xOffset = ${diff} * ${halfWidth}",
    "var yOffset = ${diff} * ${halfHeight}",
    {
      "func": "SET",
      "collection": "child",
      "property": "x",
      "relation": "+",
      "value": "${xOffset}"
    },
    {
      "func": "SET",
      "collection": "child",
      "property": "y",
      "relation": "+",
      "value": "${yOffset}"
    }
  ]

**Comment by robartsd** [comment]
CSS defaults the transform origin to the center of the bounding box, so card is being positioned in the top left corner, then scaled from its center.

**Comment by bjalder26** [comment]
> CSS defaults the transform origin to the center of the bounding box, so card is being positioned in the top left corner, then scaled from its center.
> 
> I added a variant to your test room with the `transform-origin` set to `0 0`.

Nice, I think that is the best solution, so I am going to close this issue.
