### ISSUE TITLE
SET parent changes order of top 2 cards in pile

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#741]
If cards are piled 1, 2, 3, 4, 5 and you SET a new parent then the order they will wind up in is 4, 5, 3, 2, 1, always switching the top card (5) and the second card (4).

The issue is visible here: https://virtualtabletop.io/Issues
Game: #741 SET order
(red buttons)

Not sure if this is technically a 'bug' (since we have MOVE and other ways of accomplishing the same thing while retaining the order), or if it would be considered an enhancement IF changed.

**Comment by bjalder26** [comment]
I'm thinking that this would straighten out the order, and I'm kind of guessing that nobody is depending on the top two cards flipping order to make one of their games work.  I'm also thinking this MIGHT be related to some of the issues Ingegneus was having maintaining the order of cards (though most likely not). 

```js        
if(widget.get('type') == 'card' && this.get('type') == 'card') {
  const pile = {
    type: 'pile',
    parent: this.get('parent'),
    x: widget.get('x'),
    y: widget.get('y'),
    width: this.get('width'),
    height: this.get('height')
  };
  if(this.get('owner') !== null)
    pile.owner = this.get('owner');
    addWidgetLocal(pile);
    await widget.set('parent', pile.id);
    await this.bringToFront();
    await this.set('parent', pile.id);
    break;
  }
```

**Comment by Ingegneus** [comment]
During my efforts to keep the card order, this was something that drove me crazy. I encountered exactly this issue with one of my many attempts.
