### ISSUE TITLE
uploading cards is weird atm

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#757]
when i upload a bunch of cards to a deck at first everything is fine, but when i reload the room the cards in the deck suddenly have a different count from before. now i can use the -1 button to reduce them again and then it works

**Comment by bjalder26** [comment]
I'm making a guess here.  Did you upload cards, then exit the deck editor without first pressing `update widget`?

If not, can you explain how to replicate the issue?

**Comment by rogerl50** [comment]
@Ingegneus Have you been able to reproduce this issue? If not, or if you know it is no longer an issue, we should close this.

**Comment by 96LawDawg** [comment]
Original poster could not duplicate.  Closed.
