### ISSUE TITLE
Apply css properties to faceTemplate objects

### ISSUE THREAD

**Issue by robartsd** [ArnoldSmith86/virtualtabletop#76]
Apply css properties to faceTemplate objects.

For widgets, arbitrary element css (appears in DOM style attribute) can be added by giving the widget a "css" property. This does not work for object layers of a faceTemplate.

Specifically I'm trying to make rotated text and round the corners of an image layer. Of the two rotating text is more important to me. Simply providing the "rotation" property that widgets have to faceTemplate objects would be enough to get this job done, but providing the "css" property would provide a lot more power.

```
  "faceTemplates": [
    {
      "objects": [
        {
          "type": "image",
          "x": 0,
          "y": 0,
          "valueType": "static",
          "color": "#080",
          "value": "/assets/-1848626211_133",
          "width": 142,
          "height": 216,
          "css":"border-radius:10px"
        },
        {
          "type": "text",
          "x": 28,
          "y": 20,
          "fontSize": 15,
          "valueType": "dynamic",
          "value": "label",
          "textAlign": "center",
          "textFont": "interstate",
          "width": 106,
          "rotation": 90
        },
        {
          "type": "text",
          "x": 28,
          "y": 64,
          "fontSize": 14,
          "valueType": "dynamic",
          "value": "extra",
          "textAlign": "center",
          "textFont": null,
          "width": 106
        }
      ],
      "border": false,
      "radius": false
    }
  ],
```

**Comment by UltimateGeek** [comment]
Please edit you original comment and provide more details. You could start by repeating the title inside the body, and including a code snippet of an example.

**Comment by RaphaelAlvez** [comment]
Cards in particular need css in i had this problem to and reported it in the old feature request channel. 

Not only that we need to have css for the faces themselves.
