### ISSUE TITLE
JSON editor has inaccurate selections with ${}, {}, [] and {"property": "value"}

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#763]
Selects entire [] instead of just placing the cursor inside.
![image](https://user-images.githubusercontent.com/78324099/136674138-aa0a8b9a-910f-4285-a4c0-e48fa28332c6.png)

Selects entire {} instead of just placing the cursor inside.
![image](https://user-images.githubusercontent.com/78324099/136674152-44e2a676-bb78-4330-ac22-a85d4977d7bc.png)

Selects the entire portion in quotation ${} instead of placing the cursor inside.
![image](https://user-images.githubusercontent.com/78324099/136674173-9bd6cb11-c332-4db6-9526-84e7bfc4bb7c.png)

Looks like it selects a range equal to the length of {"type": "card"}, instead of `card` and also **does not adjust the selection for indentations**.
![image](https://user-images.githubusercontent.com/78324099/136674110-90edc423-1905-43a9-b514-0ad8c2dd5e13.png)

**Comment by rogerl50** [comment]
The same comment (though perhaps not the same fix) applies to adding a routine. Currently, the `[]` is selected, and you have to click out then click between the brackets to get what you most likely want.

**Comment by RaphaelAlvez** [comment]
Oh that's so annoying. Would love to see that implemented

**Comment by bjalder26** [comment]
> Oh that's so annoying. Would love to see that implemented

I made a PR if you want to look it over.
