### ISSUE TITLE
"return":false causes "Show Routine Debug Output" to drop some levels of output

### ISSUE THREAD

**Issue by AlanDeSmet** [ArnoldSmith86/virtualtabletop#767]
While in the Ctrl-J editor, when you `CALL` another routine and specify `"return":false`,  the output "Show Routine Debug Output" is missing a lot of stuff.

### To reproduce:

1. Load the attached vtt file [return_false_bug_demonstration.zip](https://github.com/ArnoldSmith86/virtualtabletop/files/7229124/return_false_bug_demonstration.zip) (I changed the extension to .zip so GitHub would accept it.) A full copy of the JSON file from the VTT is inline below as well.
2. "Play"
3. Ctrl-J to enter the editor
4. Click the `"return": true` button.
5. Hover over "Show Routine Debug Output"
6. Observe output that looks something like this (which is expected):

```
      ▼ bug-trigger1: clickRoutine
        ▼ CALL anotherRoutine and return result => 1
          ▶ Original and applied operation
          ▶ var result = 1 => 1
          ▶ Variables and collections afterwards
```

7. Click the `"return": false` button.
8. Hover over "Show Routine Debug Output"

### Observed behavior:

Show Routine Debug Output looks like this:

```
      ▶ var result = 1 => 1
```

### Expected behavior:

Show Routine Debug Output looks something like this:

```
      ▼ bug-trigger: clickRoutine
        ▼ CALL anotherRoutine and no return
          ▶ Original and applied operation
          ▶ var result = 1 => 1
          ▶ Variables and collections afterwards
```

In more complicated examples, the incorrect output is more complex and different, but there are definitely problems.

### Reproduction script

```
{
  "_meta": {
    "version": 3,
    "info": {
      "name": "return false bug demonstration",
      "image": "",
      "rules": "",
      "bgg": "",
      "year": "0",
      "mode": "vs",
      "time": "30",
      "players": "2-4",
      "language": "US",
      "variant": "",
      "attribution": ""
    }
  },
  "bug-trigger": {
    "type": "button",
    "text": "\"return\": false",
    "clickRoutine": [
      {
        "func": "CALL",
        "routine": "anotherRoutine",
        "return": false
      }
    ],
    "anotherRoutine": [
      "var result = 1"
    ],
    "x": 0,
    "y": 0,
    "id": "bug-trigger"
  },
  "bug-trigger1": {
    "type": "button",
    "text": "\"return\": true",
    "clickRoutine": [
      {
        "func": "CALL",
        "routine": "anotherRoutine",
        "return": true
      }
    ],
    "anotherRoutine": [
      "var result = 1"
    ],
    "x": 0,
    "id": "bug-trigger1",
    "y": 100
  }
}
```

**Comment by AlanDeSmet** [comment]
Initial investigation suggests that in this case `jeLoggingRoutineOperationStart` is being called, but there is no matching call to `jeLoggingRoutineOperationEnd`

**Comment by AlanDeSmet** [comment]
On my much larger script, I have an enterRoutine that generates this:
![bad-routine](https://user-images.githubusercontent.com/610177/134757740-9001e0d2-b7b0-4a06-a817-70c696d39df1.png)

There should be a single `FOREACH` (completely missing) with 8 `loopRoutine`s inside, each eventually `CALL`ing `describeRoutine` for `describe-step-X-label` for X 1 through 8.

**Comment by bjalder26** [comment]
AlanDeSmet, Roger appears to have fixed this, but if you wouldn't mind uploading your "larger script" to the PR server to check to see if it also catches the 8 loopRoutines, that would be appreciated.  The buttons you provided as an example appear to have their debug property displayed in the test server.

 http://212.47.248.129:3771

**Comment by AlanDeSmet** [comment]
On the 212.47.248.129 server, "Show Routine Debug Output" looks correct for my larger script. I dug into it in a few spots and it matches what I think my code is supposed to be doing. Thank you very much!
