### ISSUE TITLE
server failed to start SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by pounamu** [ArnoldSmith86/virtualtabletop#768]
I followed exactly the instructions to download this repository and get all dependencies for debian based linux and when I ran 'npm start' I got the following error:
```
$ npm start

> virtualtabletop@0.1.0 start
> node server.mjs

file:///home/gringer/install/vtt/virtualtabletop/server/room.mjs:129
      this.trace('broadcast', { func, args, exceptPlayer: exceptPlayer?.name });
                                                                       ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
npm ERR! code 1
npm ERR! path /home/gringer/install/vtt/virtualtabletop
npm ERR! command failed
npm ERR! command sh -c node server.mjs

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gringer/.npm/_logs/2021-09-25T03_54_11_286Z-debug.log
```

I tried 'node server.mjs' and got the following error:
```
$ node server.mjs
file:///home/gringer/install/vtt/virtualtabletop/server/room.mjs:129
      this.trace('broadcast', { func, args, exceptPlayer: exceptPlayer?.name });
                                                                       ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
```

I ran git bisect and traced the issue back to this commit 3f11ff73370e2d0a155c5b409359ceeb979b5a90 as the first bad one.

I am running 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux, I have nodejs at version 12.22.5~dfsg-5 and vtt commit b0071d1faf46a076d77b93393b1e216450accc96

**Comment by bjalder26** [comment]
I'm thinking that the question mark is a mistake. 
![image](https://user-images.githubusercontent.com/78324099/134758165-258b3fe3-882b-4d08-afdc-35bc06725b32.png)

**Comment by pounamu** [comment]
I noticed that too. I tried just deleting it and then the server started, but when I looked at the player list there no player names listed.

**Comment by bjalder26** [comment]
Oh, maybe it's supposed to be a Ternary Operator.

**Comment by rogerl50** [comment]
I *think* you are using a *much* older version of node.js than is used by the production server. FYI, downloading the current build, doing an `npm install` and `npm start` works for me (MacOS 15).

**Comment by ArnoldSmith86** [comment]
Yeah, that Node version is too old. Distributions have pretty old versions. That's why the instructions include this:

`curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash -`

Downloading something straight into a root shell is pretty stupid but either you know enough to install it manually or you just copy-paste stuff blindly from somewhere else which is pretty much the same.

**Comment by pounamu** [comment]
I updated to Node version 16, because when I tried to install version 15 it told be that that version is no longer supported and either 14 or 16 should be used instead.

The update fixed the issue.

Thank you all for your help.
