### ISSUE TITLE
Add dice, chooser and token variants for cards

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#770]
Basically I propose we create those widget using the card widget as a base. This is mostly for pcio compatibility.

For dices and choosers would probably only have a special click action.

Tokens' uniqueness is still a question mark for me

**Comment by 96LawDawg** [comment]
This came up in a discussion of a PCIO import today.  https://discord.com/channels/770758631146782780/793626318037975081/1054980952012619776

Dmajor's game imported well, but was missing the chooser widget type.  PCIO has defaults of bidding, suit, dice, in/out. and custom choosers.  We should try to add those for compatibility.

**Comment by 96LawDawg** [comment]
This has mostly been done in #1871, but the PCIO importer still needs to be implemented for full compatibility.

**Comment by 96LawDawg** [comment]
The last remaining part of this was fixed by #1914.
