### ISSUE TITLE
onEnter and onLeave don't resolve piles

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#82]
If you put a pile of cards into a holder, the `onEnter` properties get added to the pile; not the cards.

**Comment by rogerl50** [comment]
How does this relate to the overall discussion of piles and cards that was ongoing a week or two ago? On a quick scan of the issues list, I don't see  an open issue related to piles.

**Comment by ArnoldSmith86** [comment]
As far as I'm concerned it doesn't relate because this has nothing to do with buttons.

Piles won't go away so this has to work. They will just be made "transparent" for button operations.
