### ISSUE TITLE
Duplicate widget command options will not decrease x to 0

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#846]
When duplicating a widget, the command options menu pre-populates with the "# Copies X" as 1.  Sometimes I want to duplicate only in the Y direction.  The +/1 buttons in the box do not let the X value go below 1.  But they do work for Y.  So I have to manually type 0 in the X box.  Not a big deal, just a minor annoyance.

**Comment by 96LawDawg** [comment]
Probably a very minor change to line 356 in the jsonedit.js from

```label: '# Copies X',      type: 'number',   value: 1,   min:     1, max:  100```

to 

```label: '# Copies X',      type: 'number',   value: 1,   min:     0, max:  100```

**Comment by ArnoldSmith86** [comment]
Huh. Yeah, that.
