### ISSUE TITLE
inheritFrom seems to have an issue with default values

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#847]
My Colonies (see #public-library on Discord) uses inheritFrom to inherit the color of a seat to game pieces which in turn use it in svgReplaces.

Inheriting the actual player color seems to work fine but when loading the game with empty seats, some game pieces are grey (correct) and some are black.

**Comment by ArnoldSmith86** [comment]
Hmm, I just wanted to look at it but it doesn't seem to happen anymore. Can anyone reproduce it?

**Comment by rogerl50** [comment]
Should this be closed? Is it reproducible?

**Comment by 96LawDawg** [comment]
Related to #1092 and fixed by #1093.  Also see Discord discussion at https://discord.com/channels/770758631146782780/793626590848352306/937172585999908924.
