### ISSUE TITLE
Cursor icon does not disappear during INPUT

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#855]
When an INPUT function is used, the player that activated the button to call the function has his cursor stay on the screen in the same place it was until the INPUT function process is completed (the player presses Go or Cancel).

**Comment by 96LawDawg** [comment]
Also, if you wait long enough (as long as it took for me to prepare the original issue), then even if the user presses Cancel, the original cursor icon remains on the screen.  I didn't test this for Go or for other time periods.

**Comment by robartsd** [comment]
I think the mousedown event is updating the cursor for other players, but the mouseup event is not sending an update and the fade out is only happening for inactive cursors in the mouse up state.

**Comment by robartsd** [comment]
Simplest solution would be to change the CSS so that even a cursor in the "pressed" state fades out when inactive (no changes to JS would be needed just style `.cusrosr.active.pressed` instead of `.cussor.pressed`). This would also mean the cursor would fade out if a player stops moving in the middle of a drag (without releasing the mouse button). To maintain current behavior while dragging, but change behavior while interacting with an overlay, the JS would need to change.

**Comment by 96LawDawg** [comment]
> if a player stops moving in the middle of a drag

Would the cursor fade back in/reactivate if the user started moving again?  Or would it take another mouse press?

**Comment by robartsd** [comment]
The cursor always comes back immediately upon motion. If the button is pressed it would come back to 50% opacity as soon as any movement is detected.

**Comment by 96LawDawg** [comment]
Then it seems like your easy solution is fine.  I mean, who cares, if the cursor goes out during the middle of a drag when stopped as long as it shows back up upon movement.  That's my opinion anyway.

**Comment by ArnoldSmith86** [comment]
I would prefer if it wouldn't fade when clicked. That would reintroduce the problem where you don't know if a player let go of the card if they are just "resting". Came up a few times in my games..

**Comment by robartsd** [comment]
> I would prefer if it wouldn't fade when clicked. That would reintroduce the problem where you don't know if a player let go of the card if they are just "resting". Came up a few times in my games..

Okay, I'll have to figure out where to send a broadcast message to let other clients know that the mouse is no longer clicking the button. I'm thinking that a message should be broadcast when the overlay is opened which would have other clients mark the mouse as inactive without the button pressed.
