### ISSUE TITLE
Seat clickRoutine customization

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#865]
Just like my recent issue with piles, `clickRoutines` are not active for seats.  May want to consider making that available so that additional steps can be taken when someone sits besides the default ones of turning the seat a color and changing visibility of linked items.  For now (and maybe this is a fine forever solution), you can just add a `playerChangeRoutine` that will sense when a player comes or goes.  It just seems less obvious that is the way to go than a `clickRoutine`.  But I'm fine if this issue just dies.

**Comment by ArnoldSmith86** [comment]
Hmm? I used seat `clickRoutine` in my latest two public library submissions.

**Comment by 96LawDawg** [comment]
In https://virtualtabletop.io/bzmx I added a simple `clickRoutine` to flip a checker.  It does that, but doing so overrides the default behavior of adding a player to the seat.  I don't know why there is a difference in Foreign Affairs and wht I did.

**Comment by ArnoldSmith86** [comment]
Because it uses `CLICK` on itself with the appropriate mode.

**Comment by 96LawDawg** [comment]
Okay.  So I tried that.  Mode:
  "ignoreClickable" locks up the room
  "ignoreClickRoutine" adds the player to the seat but doesn't flip the checker
  "ignoreAll" adds the player to the seat but doesn't flip the checker
  "respect" locks up the room

What am I missing?

**Comment by ArnoldSmith86** [comment]
> What am I missing?

`CLICK`ing your `DEFAULT` collection. :smile:

**Comment by 96LawDawg** [comment]
Well, I'm eleven kinds of stupid.  But that is better than the usual 15.  Issue closed.
