### ISSUE TITLE
JSON editor copies inherited `cardTypes` and `cardDefaults`

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#871]
If a deck uses `inheritFrom` on another deck to get its `cardTypes`, they get copied every time you open a card of the inheriting deck in the JSON editor.

The problem is that it loads the `cardDefaults` and `cardType` into the card widget so you can edit the values directly in the card. And every time the widget is saved (which even happens before you make any changes, I think) the `cardTypes` and `cardDefaults` get written to the deck. But that mechanic doesn't know about `inheritFrom` yet.

**Comment by bjalder26** [comment]
So it stops inheriting the cardTypes and cardDefaults because the inherited properties are written to the inheriting deck directly?

**Comment by ArnoldSmith86** [comment]
Exactly.
