### ISSUE TITLE
The position of the card placed in MOVEXY shifts

### ISSUE THREAD

**Issue by jippless3024** [ArnoldSmith86/virtualtabletop#872]
If you expand the cards using the code below, you'll see that only the last card in the collection is out of coordinates and overlaps with the other cards.
However, for example, "var x = 20" and "vary = 20" were fine.
```
{
  "type": "button",
  "text": "spread",
  "x": 0,
  "y": 90,
  "z": 305,
  "id": "spread",
  "debug": false,
  "movableInEdit": false,
  "parent": "length",
  "width": 40,
  "height": 40,
  "clickRoutine": [
    {
      "func": "SELECT",
      "property": "parent",
      "value": "temp",
      "type": "card",
      "collection": "spreadDeck",
      "sortBy": {
        "key": "z",
        "reverse": true
      }
    },
    "var x = 10",
    "var y = 10",
    "var offsetX = 120",
    "var offsetY = 200",
    "var count = 1",
    {
      "func": "FOREACH",
      "collection": "spreadDeck",
      "loopRoutine": [
        {
          "func": "MOVEXY",
          "from": "temp",
          "face": 0,
          "x": "${x}",
          "y": "${y}",
          "z": 100
        },
        {
          "func": "IF",
          "operand1": "${count}",
          "relation": ">=",
          "operand2": "${PROPERTY text OF length}",
          "thenRoutine": [
            "var count = 1",
            "var x = 10",
            "var y = ${y} + ${offsetY}"
          ],
          "elseRoutine": [
            "var count = ${count} + 1",
            "var x = ${x} + ${offsetX}"
          ]
        }
      ]
    }
  ]
}
```
![spread](https://user-images.githubusercontent.com/93677046/140988987-ac9c7daa-893e-4e56-a7ab-4471f5c17802.jpg)

**Comment by rogerl50** [comment]
Can you post a link to a room containing all of this?

**Comment by rogerl50** [comment]
The problem is that that last card is actually in the pile that has appeared at top left. Its coordinates are relative to the pile. (This doesnt' really answer your question, just trying to explain the situation further).

**Comment by 96LawDawg** [comment]
After further experimentation, this only happens for absolute y values <14 for the first card.  Doesn't matter what x is.  At least, in the upper left corner.  Something similar may happen on other sides of the room.  I have no idea what is going on, but wanted to provide that additional data.

**Comment by 96LawDawg** [comment]
Correction to what I just said.  x is a player.  So if either value is above 13, then a pile does not form and the problem does not happen.

**Comment by rogerl50** [comment]
I think the issue is that the 'parent' attribute of the first card moved is cleared, and then the pile forming code concludes that the new x-y coordinates of the moved first card are close enough to the (current) coordinates of the unmoved second card that a new pile is formed.

**Comment by bjalder26** [comment]
> After further experimentation, this only happens for absolute y values <14 for the first card. Doesn't matter what x is. At least, in the upper left corner. Something similar may happen on other sides of the room. I have no idea what is going on, but wanted to provide that additional data.

I don't quite understand this whole thing, but 10 + 4 = 14.  And I THINK rogerl50 is saying that when it loses its parent it winds up at 4,4 in the room initially (because it still has it's x and y) it will form a pile with any card within 10 (because that is in the JS code).

**Comment by rogerl50** [comment]
> > After further experimentation, this only happens for absolute y values <14 for the first card. Doesn't matter what x is. At least, in the upper left corner. Something similar may happen on other sides of the room. I have no idea what is going on, but wanted to provide that additional data.
> 
> I don't quite understand this whole thing, but 10 + 4 = 14. And I THINK rogerl50 is saying that when it loses its parent it winds up at 4,4 in the room initially (because it still has it's x and y) it will form a pile with any card WITHIN 10 (because that is in the JS code).

I don't really understand it either, but yes, that's exactly what I'm saying. :)
