### ISSUE TITLE
holder scale and movable child coordinates

### ISSUE THREAD

**Issue by jippless3024** [ArnoldSmith86/virtualtabletop#877]
If I put child in a holder made under the following conditions, there will be a gap between the place where I leave child and the place where you store it.
alignChildren:false
scale:!= 1

Check the example
https://virtualtabletop.io/xtvl

**Comment by robartsd** [comment]
Yes, the code mapping room coordinates to local widget coordinates can use some work. I believe there are similar issues with rotated holders.

**Comment by jippless3024** [comment]
As a workaround, I created a routine to address this issue in the json editor
The placement is based on the upper left corner of the widget
However, it is arguable whether this change is made on a routine or as a basic operation of the widget.

Check the example
https://virtualtabletop.io/xtvl

**Comment by ArnoldSmith86** [comment]
I think I have a local branch somewhere that improves the behavior. Unfortunately it is a recursive problem with arbitrary layers of `scale` and `rotation` and the "correct" solution would be total overkill.

I'll try to remember to make it into a draft PR.

**Comment by robartsd** [comment]
I've added a draft PR with recursive coordinate conversion functions. #882

**Comment by robartsd** [comment]
#903 should fix this issue. Please test.
