### ISSUE TITLE
INPUT is not working

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#883]
The `INPUT` function does not collect and store the variable.  It works in the sense that it creates a pop up and asks for input, but the input is not stored.  Demo at https://virtualtabletop.io/kl87.  Look at the debug and see the variables remain undefined.

**Comment by rogerl50** [comment]
It works properly for me...

**Comment by rogerl50** [comment]
The "undefined" you see is the return from INPUT. If you look at "Collections and variables afterwards", you will see that the variables are correctly defined. Probably there shouldn't even be an orange part to the INPUT debugging info.

**Comment by 96LawDawg** [comment]
Well, I did say somewhere else that I'm usually 15 kinds of stupid.  It is one of those days.
