### ISSUE TITLE
Reduce wasted screen space in editor mode

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#891]
could this be reduced? on the rare occasion were i need it, it's really annoying that it's so small 
![image](https://user-images.githubusercontent.com/78076361/142203043-8cc084aa-22c3-4940-a784-348ed7af1d31.png)

**Comment by ArnoldSmith86** [comment]
Please tell me you didn't use that editor to create your Mistborn House War...

**Comment by Ingegneus** [comment]
Hahahaha no don't worry XD 
I use it sometimes to edit decks when I need to remove a card type entirely (in my experience I need to first make the card count in the deck editor 0 and then delete the cardType). I know the JSON editor can do this too but opening it takes a while since the tree view of that game is laggy as hell and so for a quick edit I use the normal editor.

**Comment by bjalder26** [comment]
Above the text and below the buttons is space from padding in .overlay
