### ISSUE TITLE
Seats force font css attributes on children

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#894]
Children of a seat automatically inherit the font size and color and possibly other untested attributes.  It is almost like there is an automatic `inheritFrom` relationship.  You can override the behavior by explicitly setting css on the child, but this shouldn't happen.

Demo room in https://virtualtabletop.io/6r92.  Click on the basic widget under the seat and set its parent to "seat1" and watch the result.

**Comment by ArnoldSmith86** [comment]
Isn't that the case for all widgets?

**Comment by RaphaelAlvez** [comment]
This is intended.

All css is inherited by children. The children will only use the css properties it doesn't has stated.

**Comment by 96LawDawg** [comment]
I guess I just never noticed before.  Still not sure why that would be the intended behavior, but now that I know, I can deal with it.

**Comment by ArnoldSmith86** [comment]
I'm not sure if I would call it "intended". It is "expected" though if you know how HTML works. I'm not sure if we want to do anything about it or not.

**Comment by 96LawDawg** [comment]
I most definitely do NOT know how HTML works.  But changing it would be a breaking change.  Definitely not worth it.
