### ISSUE TITLE
Allow onHover CSS for seats

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#906]
To the user, seats look for all the world like buttons - you click on them to do something. It would be nice to be able to provide the same kind of onHover visual feedback that you can with buttons. How hard would it be to migrate the *OH CSS code from button.js to seat.js?

**Comment by RaphaelAlvez** [comment]
I agree. I'll assign myself to it.
At least some sort of feedback is needed
