### ISSUE TITLE
Expose an array of all active player names as button variables

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#91]
Now that `COMPUTE` is merged, this could be used to iterate through all players.

**Comment by pf-lkobbe** [comment]
Great idea! We'd still need some kind of for-each to really make use of it, right?

**Comment by ArnoldSmith86** [comment]
Would make it easier but you can make counters, get the array length and read array entries at an index. Should be everything you need. I didn't try it yet though.
