### ISSUE TITLE
Canvas composed widget needs a way to prevent drawing

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#911]
A room designer may not always want the players to be able to use the canvas widget.  We need an easier way to deny access than putting a transparent widget on top.  A `"clickable":false` property should be added to make that task simple.

**Comment by bjalder26** [comment]
Maybe a "writable" property that can be set to true, false, a playerName, or an array of playerNames.

**Comment by robartsd** [comment]
How about a property that works just like owner. An empty array would prevent any player from drawing; null would allow any player to draw. Could name the property `artist`.

**Comment by ArnoldSmith86** [comment]
See #913. :smile:
