### ISSUE TITLE
Other overlays interfere with dynamic properties updating in deck editor.

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#928]
These are the steps to reproduce this issue.
1) Open a deck editor (and leave it open, stay in edit mode)
2) Open the deck in the JSON editor
3) Change the value of a dynamic property in faceTemplates (e.g. "value": "text" to "value": "text2")
4) Close the JSON editor
5) Click on one of the other overlay buttons such as players and settings or add widgets twice to close the deck editor
6) Reopen the deck editor by clicking on the deck while still in edit mode

**Comment by 96LawDawg** [comment]
Superseded by new UI.
