### ISSUE TITLE
Face parameter for MOVE does not work

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#934]
Title says it all.  Setting the optional `face` parameter for MOVE does not work.  Widgets always get face 0.  Works fine for MOVEXY.

**Comment by bjalder26** [comment]
Could you have an active enterRoutine or onEnter on the holder, or a changeRoutine on the card.

**Comment by 96LawDawg** [comment]
Yes, so I am an idiot.  I was testing something out for another PR and used a room I previously set up.  It had onEnter in the holder I was moving to.  Thank you!

**Comment by bjalder26** [comment]
You're welcome, and you are not an idiot.  I didn't know what JSON was or any JavaScript before coming here.  Everything I have learned has been from all of you and 1/2 of an online lesson that I still have to finish.
