### ISSUE TITLE
Have "unlimited" operands when doing simple math

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#944]
it is really annoying when doing some calculations, that every `+`, `-`, `*` and `/` operation has to be in its own line. especially in cases where you have something like `(a + b) / (c + d)`. could it be possible to enable more operands for the basic math operations?

**Comment by ArnoldSmith86** [comment]
It's not exactly easy. I'm not sure if I want to.

**Comment by RaphaelAlvez** [comment]
Not an easy task.

But if anyone wants to tackle it I would so something like this:

- Get the most nested ( )
- check if it has an operation or variable inside of it (or if it is only a string or only a number
- resolve ( ) content into a string or in a number
- check if ( ) is preceded of a function (tan( ) cos, sin...) and apply value to the function
- if not replace '( content )' by the value you got in step 3
- repeat until there is no more ( )

**Comment by robartsd** [comment]
I could see doing something like this but allow only one operation per parenthetical group. To calculate `a + b + c` we'd require syntax of `(a + b) + c` or `a + (b + c)`. This requirement would somewhat simplify implementation.

**Comment by rogerl50** [comment]
The large hammer solution would be to use a javascript-emitting parser generator. Probably not that hard, and it would greatly improve expression handling.

**Comment by 96LawDawg** [comment]
Implemented by #1791
