### ISSUE TITLE
Countries are not languages

### ISSUE THREAD

**Issue by mavit** [ArnoldSmith86/virtualtabletop#96]
The edit game page invites me to enter a country code in the language field.  This seems odd, given that there exists no one to one mapping between countries and languages: some countries speak many languages, and some languages are spoken in many countries.  If we need to know the language, it would seem simpler to ask directly for the language.

The most user-friendly solution may be to auto-complete this field based on a list of languages, e.g., from https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by RaphaelAlvez** [comment]
Hi this was implemented this way so we could use the flags unicode on devices that support them. I believe you must be using Windows? For some devices those two letters are converted into the flags automatically. 

On top of that for some languages the country you come from may do some difference on how to speak and write. For example in wordy I made the translation to portuguese but I'm Brasiliam. We used BR to make sure the translation wouldn't have any conflict with european or african portuguese

**Comment by mavit** [comment]
> Hi this was implemented this way so we could use the flags unicode on devices that support them. I believe you must be using Windows? For some devices those two letters are converted into the flags automatically.

Ah, yes, now that you point them out, on Linux I do see the flags on the Games page.  Itʼs the public library and the edit game page where I donʼt see them.

[Using flags for languages is tricky](http://www.flagsarenotlanguages.com/blog/why-flags-do-not-represent-language/), but no-one seems to have come up with another symbology.

> On top of that for some languages the country you come from may do some difference on how to speak and write. For example in wordy I made the translation to portuguese but I'm Brasiliam. We used BR to make sure the translation wouldn't have any conflict with european or african portuguese

FWIW, the IETF have thought about this and come up with a standard called [BCP 47](https://tools.ietf.org/html/bcp47).  TL; DR: there is code specifically for Brazilian Portuguese which is `pt-BR`.

**Comment by RaphaelAlvez** [comment]
The problem I foresee with including BCP 47 is that the size would be inconsistent. I do agree that your point is valid but flags and 2 letter codes are a convenience.
If you are in the discord, I'm going to include this on the meetings channel as talk points for the next meeting.

**Comment by RaphaelAlvez** [comment]
This problem has been addressed at the meeting and accepted.
We are going to transition to languages codes.

**Comment by robartsd** [comment]
> We are going to transition to languages codes.

What standard will be used?
