### ISSUE TITLE
Storage space for raw files

### ISSUE THREAD

**Issue by mousewax** [ArnoldSmith86/virtualtabletop#960]
Create submodule? or separate repository? for raw creative files.

**Comment by robartsd** [comment]
Could simply be a folder, but it would be nice not to copy all the creative files to containers that are just for working on code.

**Comment by mousewax** [comment]
That's why I am asking for a separate repository. If we start including raw files for game graphics, things might get very large very quickly.

**Comment by RaphaelAlvez** [comment]
I agree with this. I have some raw files that I'm always afraid to lose as it is the only copy.

Now that we are changing the assets I'm less worried as this is no longer my problem

**Comment by robartsd** [comment]
New repo has been created [virtualtabletop-misc](https://github.com/ArnoldSmith86/virtualtabletop-misc)
