### ISSUE TITLE
Create Automatic Test Servers for each open PR

### ISSUE THREAD

**Issue by robartsd** [ArnoldSmith86/virtualtabletop#963]
Create automatic servers at https://test###.virtualtabletop.io for each open PR that is not in the Automatic Beta Server. Unlike the http://212.47.248.129:xxxx servers, these should attempt to merge main and the PRs in the Automatic Beta Server. For PRs in the Automatic Beta server https://test###.virtualtabletop.io could be the PR merged with main but no other PRs (intended to isolate problems discovered on Beta).

**Comment by mousewax** [comment]
Since these are on a subdomain and not a different port, will they be using ssl?

**Comment by robartsd** [comment]
Of course this assumes that automatic DNS authentication with certbot is available to automatically maintain valid Lets Encrypt certificates for `*.virtualtabletop.io.`

[https://certbot.eff.org/faq#does-let-s-encrypt-issue-wildcard-certificates](https://certbot.eff.org/faq#does-let-s-encrypt-issue-wildcard-certificates)

**Comment by robartsd** [comment]
Using WHOIS tools, I've determined that virtualtabletop.io is registered with and resolved through NameCheap DNS. Unfortunately direct DNS domain authentication is not possible there, but apparently there is a workaround:

https://blog.bryanroessler.com/2019-02-09-automatic-certbot-namecheap-acme-dns/
