### ISSUE TITLE
CANVAS function, mode: setPixel needs error checking

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#964]
The values of x and y in the setPixel mode are scaled percentages from 0 to 99.9.  If a user puts a value that is negative or 100 or more, the room freezes.  I'm working on a canvas tutorial and I thought the values were absolute coordinates, which is how I discovered this.  the wiki entry was unclear, so I changed that.  But still need to catch this error in the JSON.

**Comment by ArnoldSmith86** [comment]
They are percentages? I'm pretty sure I made them pixel values. Or did @robartsd change that in his coordinates PR?

The issue is probably just as valid either way.

**Comment by 96LawDawg** [comment]
So, not percentages.  It just worked out that way because I was using the default resolution of 100.  As the resolution changes, the valid max number for x and y change.  But yes, still a valid issue because numbers outside the canvas cause a freeze.

**Comment by robartsd** [comment]
> Or did @robartsd change that in his coordinates PR?

Didn't touch the CANVAS code function code. Only touched the code that maps mouse input to pixels.
