### ISSUE TITLE
Feature request:Uploading a card back image

### ISSUE THREAD

**Issue by jippless3024** [ArnoldSmith86/virtualtabletop#969]
Currently, the front side of the card can be uploaded from the standard editor, but the back side needs to be rewritten directly in json.
A friend of mine who doesn't know json was confused by this, so I think making it possible to upload the back side from the standard editor will make it easier to create cards.

**Comment by bjalder26** [comment]
So buttons in the Deck Editor that will change the image of any image type objects in faceTemplates?

**Comment by jippless3024** [comment]
That's right.

**Comment by robartsd** [comment]
There are hopes/plans to make a much better deck editor, though developer efforts have not been focused there much lately.

**Comment by 96LawDawg** [comment]
Implemented by a few PRs (like #1482 and #1756).
