### ISSUE TITLE
Landing page for each game in the library

### ISSUE THREAD

**Issue by mavit** [ArnoldSmith86/virtualtabletop#97]
I run an [online boardgame finder](https://www.mavit.org.uk/boardgames-online/), and Iʼd like to link to games playable at VirtualTabletop.io.  At present I can link to the front page, which currently shows the entire library, but as the library grows this will become unweildy.

Perhaps there could be a page for each game.  It could show some basic information about the game, maybe some screenshots, and a “play now” button.

**Comment by RaphaelAlvez** [comment]
Yes there is a way. you can set you link to contain a file location in it. @ArnoldSmith86 do we have some kind of documentation for this yet?

**Comment by rogerl50** [comment]
Is it time for a more traditional  home page for the site, more like the pcio home page in content, that contains links to the various playable games, tutorials, and wiki material?

**Comment by ArnoldSmith86** [comment]
What you can do atm is now documented here: https://github.com/ArnoldSmith86/virtualtabletop/wiki/URL-Properties

That's not a landing page though. We'll have something similar soonish though and we should add URLs to games then.
