### ISSUE TITLE
Feature request:Properties for a group of cards

### ISSUE THREAD

**Issue by jippless3024** [ArnoldSmith86/virtualtabletop#970]
Currently, I believe that properties for cards need to be set on a per-card basis.

>   "cardTypes": {
>     "T 1J": {
>       "image": "/i/cards-default/1J.svg",
>       "enlarge": 2
>     },
>     "T 2J": {
>       "image": "/i/cards-default/2J.svg",
>       "enlarge": 2
>     },
>     "C 01": {
>       "image": "/i/cards-default/AC.svg",
>       "enlarge": 2
>     }

However, there are many properties that you might want to apply to all of your cards, for example, enlerge above.
In that case, as the number of cards increases, it seems redundant to apply the same property to all of them.
So I thought it would be nice to have a property for the whole card. For example, the following.

>   "cardTypes": {
>     "cards": {
>       "T 1J": {
>         "image": "/i/cards-default/1J.svg"
>       },
>       "T 2J": {
>         "image": "/i/cards-default/2J.svg"
>       },
>       "C 01": {
>         "image": "/i/cards-default/AC.svg"
>       }
>     },
>     "enlarge": 2
>   }

**Comment by bjalder26** [comment]
Isn't that accomplished with cardDefaults?

**Comment by jippless3024** [comment]
Sorry, I missed that property.
Close.
