### ISSUE TITLE
faces do not trigger changeRoutines properly

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#979]
only activeFace triggers it

properties set by faces do not trigger change routines not even propertyChangeRoutines

this is totally going to be a breaking change

**Comment by robartsd** [comment]
Is this a duplicate of #863?

**Comment by RaphaelAlvez** [comment]
I did catch that but that issue is talking about some similar but not the same. that issue is about those properties not even being available for the routines. I may delete this one if you feel it should go together.

**Comment by robartsd** [comment]
Properties set by a face change are not supposed to trigger change routines. Detect the changes to activeFace or faces instead and check the properties you are interested in.

**Comment by RaphaelAlvez** [comment]
> Properties set by a face change are not supposed to trigger change routines. Detect the changes to activeFace or faces instead and check the properties you are interested in.

I'm ok with that
