### ISSUE TITLE
Problems with JSON Editor after new icons

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#982]
In addition to the problems already noted in Discord (duplicate widget not working and multiselect not working), I discovered something else strange with the SET command.  The relation "in" seems to be missing.  It used to appear as a context sensitive option.  Now all that shows up are the mathematical symbols.  By the way, the ctrl key functionality for those MUST go away.  They are unreadable with the underline.  See attached.
<img width="235" alt="Screenshot 2021-12-06 223108" src="https://user-images.githubusercontent.com/76912527/144975092-a10abfac-31b4-4e5c-919e-9f6909505b58.png">.

The duplicate widget and multiselect need to be fixed ASAP.  It is not worth having the new icons if it means we lose that functionality.
.

**Comment by 96LawDawg** [comment]
Okay, disregard part of that.  SET does not have "in."  That is SELECT.  But I stand by the rest of it.

**Comment by ArnoldSmith86** [comment]
Multiselect seems to work for me. What's the problem? The `Add property` is probably broken.

**Comment by RaphaelAlvez** [comment]
Ops forgot to open and issue

**Comment by RaphaelAlvez** [comment]
> Multiselect seems to work for me. What's the problem? The `Add property` is probably broken.

Try to add a property
