### ISSUE TITLE
URGENT - Update game is all kinds of screwed up

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#983]
Create a room.  Add a file from the public library.  Update that variant.  It disappears.  If we can't figure out what's causing this right away, then we need to revert #935, #974, and/or #975.  It is still possible to save your progress, but you have to save the room state again and reenter the data into the variant information.

**Comment by mousewax** [comment]
Of the three of those, only #935 is not purely cosmetic. I am looking into this.

**Comment by mousewax** [comment]
I found it. It's in #935 but I don't understand what's going on.  It's in `room.html`  My guess it's in the code that comes back to update stuff and it's looking for a specific element that's not there and just gives up. It should be fixable by someone familiar with the area without rolling back the entire thing.

This is the older working code:
```          <button class="update">Update variant using current room state</button><button class="prettyButton download">Download variant</button><button class="prettyButton remove">Remove variant</button>```

This is the code that breaks things:
```          <div class="editOverlayButtonBar">
            <button class="ui-button green update update-current-state">Update variant using current room state</button>
            <button class="ui-button download download-variant">Download variant</button>
            <button class="ui-button red remove remove-variant">Remove variant</button>
          </div>```

**Comment by robartsd** [comment]
Can we patch that change in and have things work, why we figure out why this broke?

**Comment by ArnoldSmith86** [comment]
Gonna check it out.
