### ISSUE TITLE
Debug should support normal click and onEnter, onLeave and onPileCreation

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#990]
even though these are not properly routines, they are part of the general automation tools we have.

here is a list of things that should be included:

- basicWidget:
   - activeFace
   - properties set by faces: do not trigger change routines and are only updated after the change routines. should return a message informing that

- spinner:
   - angle
   - value

- seat:
    - player
    - color

- timer:
   - paused
   - milliseconds

- onEnter
- onLeave
- onPileCreation

**Comment by rogerl50** [comment]
What do you mean by the first four? I haven't checked all of them, but I know that for timer, you do get debug information when you use the TIMER command from a button, or when you click either of the buttons in the composed timer widget?

**Comment by 96LawDawg** [comment]
I don't know that I personally need or want all of the above, but something I think we must have are all the "routines."  For example, let's say you have a button that moves a card from one holder to the other.  If you click the button and review the debug report, you see the clickRoutine.  But if the holders have `enterRoutine`, `leaveRoutine`, `parentChangeRoutine`, and/or `parentGlobalUpdateRoutine`, none of that shows up in the debugger.  If you manually drag a card, the most recent event (such as a `leaveRoutine` will display in the debugger.  But we need it so show every routine that happens during exeuction.  I have repeatedly missed things when troubleshooting because it was in an enterRoutine that didn't show up on the debugger.

**Comment by rogerl50** [comment]
Can you give a little more explanation of what you'd like to see?

- basic widgets: I'm not sure what you mean. When do you want to see additional things displayed? And what?
- spinner: I'm guessing you want a line of debug output saying that the spinner was spun and what the result was. 
- seat: I'm guessing you want to know when the active player changes
- timer: I'm guessing you want to know when the timer is paused or when `milliseconds` is reached
- onEnter, onLeave, onPileCreation: I'm guessing you want a list of properties that are changed when these actions are taken.

At present, the debugger responds only when a routine is being executed. Thus even if the debugger is open, manually moving a card from one holder to another will not produce any debug output, even if the holders had an `enterRoutine` or a `leaveRoutine`. Are you proposing to change that behavior for just the above cases, or are you asking for the debugger to provide information about what happens any time there is a manual change in the room state? Or, are you asking to have the things above displayed as part of the debugger when these actions happen during routine execution?

**Comment by 96LawDawg** [comment]
If this gets done, for seats, I would also add `turn`.

**Comment by RaphaelAlvez** [comment]
ok first of all for timer milliseconds probably shouldn't be added due to the frequency of the updates

As an example if you add a checker piece and click it you don't get any kind of debug even though there is some automation happening behind that changes one property

![image](https://user-images.githubusercontent.com/73476656/179026954-98a93a58-c4b4-4e3c-bc12-070d8796d9ec.png)
`activeFace changed with no debug`

Similarly, if you put a card in a holder you may flip all cards and have no debug. there is even more crazy automation you could do with onEnter and onLeave that have absolutely 0 information in debug.

**Comment by rogerl50** [comment]
@RaphaelAlvez Here's what I'm trying to get at: currently the debugger runs only when a routine is being executed - it is kicked off by the top-level call to `evaluateRoutine` in `widgets.js`. It appears that you are asking for debug information to be given not only for actions started programmatically, but also for manual actions (things done directly by the user). Is that right?

I can see adding `onEnter` information (for example) for things moved under routine control, but expanding debugging to handle user interactions is (I think) a much larger project.

**Comment by RaphaelAlvez** [comment]
I believe it should also be triggered by normal click, onEnter, onLeave and onPileCreation

Dragging exceptions would be x, y and milliseconds only because of the frequency they update.

**Comment by RaphaelAlvez** [comment]
Yes

Actually I think the best way to describe the issue would be: "debug should cover most player interactions"

**Comment by 96LawDawg** [comment]
Debug now supports all of this.
